/-
  StaticEquilibrium.lean
  ======================

  Formalizes the witness of static equilibrium for a discrete system of forces
  and moments. In a rigid body context, equilibrium is achieved when the
  vector sum of all external forces and the sum of all moments about any point
  are zero.

  This module defines the EquilibriumWitness structure and proves that
  a system with no applied loads is in a state of trivial equilibrium.

  Style: Rustic Church (Init-only).
-/

import Init

namespace Gnosis.Civil

/-- A 3D vector in discrete space. -/
structure Vec3 where
  x : Int
  y : Int
  z : Int

def Vec3.zero : Vec3 := ⟨0, 0, 0⟩

def Vec3.add (v1 v2 : Vec3) : Vec3 :=
  ⟨v1.x + v2.x, v1.y + v2.y, v1.z + v2.z⟩

instance : Add Vec3 where
  add := Vec3.add

/-- A force applied at a specific position. -/
structure AppliedForce where
  magnitude : Vec3
  position  : Vec3

/-- 
  The moment (torque) generated by a force about the origin:
  M = r × F
-/
def cross_product (r f : Vec3) : Vec3 :=
  ⟨ r.y * f.z - r.z * f.y,
    r.z * f.x - r.x * f.z,
    r.x * f.y - r.y * f.x ⟩

/-- 
  Equilibrium Witness: 
  A collection of forces satisfies equilibrium if their sums vanish.
-/
def IsInEquilibrium (forces : List AppliedForce) : Prop :=
  let total_force := forces.foldl (λ (acc : Vec3) (f : AppliedForce) => acc + f.magnitude) Vec3.zero
  let total_moment := forces.foldl (λ (acc : Vec3) (f : AppliedForce) => acc + cross_product f.position f.magnitude) Vec3.zero
  total_force.x = 0 ∧ total_force.y = 0 ∧ total_force.z = 0 ∧
  total_moment.x = 0 ∧ total_moment.y = 0 ∧ total_moment.z = 0

/-- 
  Theorem: Empty System Equilibrium.
  An empty list of forces trivially satisfies the equilibrium witness.
-/
theorem empty_system_is_in_equilibrium : IsInEquilibrium [] := by
  unfold IsInEquilibrium
  simp [List.foldl]
  repeat constructor
  repeat (exact rfl)

end Gnosis.Civil
