import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.LayerTest
import BuleyeanMath.DevilDetailer
import BuleyeanMath.NamingBeforeReduction

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false