import Init
import BuleyeanMath.EquivalentExchange
import BuleyeanMath.ConstraintPowerDuality
import BuleyeanMath.NegationInvolution
import BuleyeanMath.IdentityBinding
import BuleyeanMath.DomainEnclosure
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.NegotiationRefusalTopology
import BuleyeanMath.PisotDilationResidue

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false