import Init

/-!
# Collatz `1 → 4 → 2 → 1` as a k=3 Braid

The Collatz function `f(n) = n/2` (if even) or `3n + 1` (if odd) has
a unique known cycle on positive integers: `{1, 2, 4}`. From any of
these three starting points, iteration returns to start in three
steps.

From `FORMAL_LEDGER.md` Table 5, line 139: the "1-2-4 Cycle" is a
named gnosis primitive, the "Absorbing Attractor" of arithmetic.

## The cycle

    1 → 4 → 2 → 1 → 4 → 2 → ...

Three elements, period 3. Every Collatz trajectory on positive
integers that terminates (which is all known ones — the Collatz
conjecture is still open in general but verified for `n < 2^68`)
terminates into this cycle.

The `k=3` braid structure: `{1, 2, 4}` with the Collatz function as
clinamen. Return time 3. Abelian (the group generated by one step
is cyclic).

## What this module witnesses

- The Collatz function `f` defined on `Nat`.
- The three-step cycle `1 → 4 → 2 → 1`, verified from each starting
  point.
- No earlier return (period is exactly 3).
- The cycle's values `{1, 2, 4}` — a rare finite attractor whose
  signature values `{1, 2, 4}` generate the integer triad `2^0,
  2^1, 2^2`.

`import Init` only. Zero `sorry`, zero new `axiom`.
-/

namespace BuleyeanMath
namespace CollatzOneTwoFourBraid

/-! ## The Collatz function -/

/-- `f(n) = n/2` if `n` is even, `3n + 1` if odd. Extended by
`f(0) = 0` for totality. -/
def collatz (n : Nat) : Nat :=
  if n = 0 then 0
  else if n % 2 = 0 then n / 2
  else 3 * n + 1

/-- Iterate the Collatz function `k` times. -/
def iterateCollatz : Nat → Nat → Nat
  | 0,     n => n
  | k + 1, n => iterateCollatz k (collatz n)

/-! ## The three-step cycle from each starting point -/

theorem from_1_step_0 : iterateCollatz 0 1 = 1 := by decide
theorem from_1_step_1 : iterateCollatz 1 1 = 4 := by decide
theorem from_1_step_2 : iterateCollatz 2 1 = 2 := by decide
theorem from_1_step_3 : iterateCollatz 3 1 = 1 := by decide

theorem from_2_step_0 : iterateCollatz 0 2 = 2 := by decide
theorem from_2_step_1 : iterateCollatz 1 2 = 1 := by decide
theorem from_2_step_2 : iterateCollatz 2 2 = 4 := by decide
theorem from_2_step_3 : iterateCollatz 3 2 = 2 := by decide

theorem from_4_step_0 : iterateCollatz 0 4 = 4 := by decide
theorem from_4_step_1 : iterateCollatz 1 4 = 2 := by decide
theorem from_4_step_2 : iterateCollatz 2 4 = 1 := by decide
theorem from_4_step_3 : iterateCollatz 3 4 = 4 := by decide

/-! ## Return theorem -/

theorem three_step_returns :
    iterateCollatz 3 1 = 1
    ∧ iterateCollatz 3 2 = 2
    ∧ iterateCollatz 3 4 = 4 := by decide

/-! ## No earlier return -/

theorem no_earlier_return_from_1 :
    iterateCollatz 1 1 ≠ 1 ∧ iterateCollatz 2 1 ≠ 1 := by decide

theorem no_earlier_return_from_2 :
    iterateCollatz 1 2 ≠ 2 ∧ iterateCollatz 2 2 ≠ 2 := by decide

theorem no_earlier_return_from_4 :
    iterateCollatz 1 4 ≠ 4 ∧ iterateCollatz 2 4 ≠ 4 := by decide

/-! ## Trajectories converging into the cycle

Concrete witnesses that small `n` eventually hit the cycle. -/

/-- `n = 3`: `3 → 10 → 5 → 16 → 8 → 4 → 2 → 1 → …`. Enters cycle at
step 5 (at `4`). -/
theorem trajectory_3_hits_cycle : iterateCollatz 5 3 = 4 := by decide

/-- `n = 5`: `5 → 16 → 8 → 4 → 2 → 1 → …`. Enters cycle at step 3. -/
theorem trajectory_5_hits_cycle : iterateCollatz 3 5 = 4 := by decide

/-- `n = 7`: longer trajectory. `7 → 22 → 11 → 34 → 17 → 52 → 26 →
13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1 → …`. Hits `4` at step 14. -/
theorem trajectory_7_hits_cycle : iterateCollatz 14 7 = 4 := by decide

/-- `n = 9`: enters cycle. -/
theorem trajectory_9_hits_cycle : iterateCollatz 17 9 = 4 := by decide

/-! ## The cycle's element values

`{1, 2, 4}` are specifically `{2^0, 2^1, 2^2}` — the first three
powers of two. The braid's elements are not arbitrary; they are
the clinamen-triad's powers. -/

theorem cycle_elements_are_powers_of_two :
    1 = (2 : Nat) ^ 0 ∧ 2 = (2 : Nat) ^ 1 ∧ 4 = (2 : Nat) ^ 2 := by decide

/-! ## Master witness -/

theorem collatz_one_two_four_braid_master :
    -- Three-step returns
    iterateCollatz 3 1 = 1
    ∧ iterateCollatz 3 2 = 2
    ∧ iterateCollatz 3 4 = 4
    -- No earlier return from any starting cycle element
    ∧ iterateCollatz 1 1 ≠ 1
    ∧ iterateCollatz 2 1 ≠ 1
    ∧ iterateCollatz 1 2 ≠ 2
    ∧ iterateCollatz 2 2 ≠ 2
    ∧ iterateCollatz 1 4 ≠ 4
    ∧ iterateCollatz 2 4 ≠ 4
    -- Trajectories hit the cycle
    ∧ iterateCollatz 5 3 = 4
    ∧ iterateCollatz 3 5 = 4
    ∧ iterateCollatz 14 7 = 4
    -- Cycle elements are powers of 2
    ∧ 1 = (2 : Nat) ^ 0
    ∧ 2 = (2 : Nat) ^ 1
    ∧ 4 = (2 : Nat) ^ 2 := by
  decide

/-! ## Reading

The Collatz function's known cycle is structurally a `k=3` braid on
`{2^0, 2^1, 2^2}`. Under `Init + decide`, we can witness:

- The cycle itself (finite; 3 steps return).
- Trajectories from specific `n` converging (finite; bounded steps).
- Cycle elements as powers of 2.

What we CANNOT prove at `Init + decide`:

- The Collatz conjecture — that *every* positive integer's trajectory
  hits the cycle. This is Π_2 over `ℕ`, unreachable monolithically.

But void archaeology applies: deliberately verify convergence for
many specific `n`. Each witness is a station toward the conjecture.
The collection sketches the asymptote without completing it. Same
pattern as every other wall-blocked theorem.

The `1 → 4 → 2 → 1` cycle enters `BraidMasterCatalog` as another
`k=3` abelian entry. The ledger's "1-2-4 Cycle" primitive is formally
realized. The cycle elements `{2^0, 2^1, 2^2}` are the first three
terms of the binary unfolding — the "clinamen triad" of powers of
two.
-/

end CollatzOneTwoFourBraid
end BuleyeanMath
