import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.NamingBeforeReduction
import BuleyeanMath.GallWaspTestimony
import BuleyeanMath.DevilDetailer
import BuleyeanMath.ClinamenReduction

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false