import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.ClinamenReduction
import BuleyeanMath.ConstraintPowerDuality
import BuleyeanMath.FractalTrinity
import BuleyeanMath.SelfSimilarity

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false