import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.NamingBeforeReduction
import BuleyeanMath.DevilDetailer
import BuleyeanMath.LayerTest
import BuleyeanMath.ClinamenReduction
import BuleyeanMath.SelfSimilarity

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false