import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.MechanizedTestimony
import BuleyeanMath.NamingBeforeReduction
import BuleyeanMath.DevilDetailer

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false