import Init
import BuleyeanMath.ClinamenReduction
import BuleyeanMath.MechanizedTestimony
import BuleyeanMath.EquivalentExchange
import BuleyeanMath.ConstraintPowerDuality

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false