import Init
import BuleyeanMath.MeshCharismaAttention
import BuleyeanMath.MeshAttentionAsVoting
import BuleyeanMath.QuantumArrow

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false