import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.NegotiationRefusalTopology

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false