import Init
import BuleyeanMath.MechanizedTestimony
import BuleyeanMath.VoidTagging
import BuleyeanMath.ClinamenReduction

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false