import BuleyeanMath.StandardModelReplacementClosure
import BuleyeanMath.StrongCPClosure
import BuleyeanMath.YangMillsMassGap
import BuleyeanMath.HierarchyProblemClosure
import BuleyeanMath.BaryogenesisClosure
import BuleyeanMath.DarkMatterIdentityClosure
import BuleyeanMath.CosmologicalConstantClosure

namespace BuleyeanMath

noncomputable section