import Init
import BuleyeanMath.MechanizedTestimony
import BuleyeanMath.ClinamenReduction
import BuleyeanMath.PoePowerOfWords

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false