import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.TriadTopology

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false