import BuleyeanMath.LocalGravityLaw
import BuleyeanMath.ResidualNuclearForce
import BuleyeanMath.MeasuredFlavorClosure
import BuleyeanMath.PerturbativeScatteringClosure
import BuleyeanMath.DarkSectorForceLawClosure
import BuleyeanMath.PrecisionFlavorClosure
import BuleyeanMath.DarkSectorClosure
import BuleyeanMath.RunningCouplingClosure
import BuleyeanMath.ElectroweakScatteringClosure
import BuleyeanMath.ScatteringAmplitudeClosure
import BuleyeanMath.AnomalyCancellationClosure
import BuleyeanMath.ProtonRestMassCandidate

namespace BuleyeanMath

noncomputable section