import Init
import BuleyeanMath.FightingTechniques
import BuleyeanMath.InductiveReidemeister
import BuleyeanMath.NegotiationTopology
import BuleyeanMath.TimeSpentWaiting
import BuleyeanMath.TechniqueAsAntidote
import BuleyeanMath.DeescalationTechniques

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false