import Init
import BuleyeanMath.NegationInvolution
import BuleyeanMath.SinWithoutDevil
import BuleyeanMath.MechanizedTestimony
import BuleyeanMath.ClinamenReduction
import BuleyeanMath.NamingBeforeReduction
import BuleyeanMath.GallWaspTestimony

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false