import BuleyeanMath.DarkSectorClosure
import BuleyeanMath.KinematicScatteringClosure
import BuleyeanMath.PerturbativeBetaClosure
import BuleyeanMath.PrecisionFlavorClosure
import BuleyeanMath.ResidualStrongForceClosure
import BuleyeanMath.GaugeMassShellClosure

namespace BuleyeanMath

noncomputable section