import Gnosis.HexonBraid
import Gnosis.BuleyBiSidedBit
import Gnosis.SpectralNoiseEquilibrium

/-!
# Buley Topological Turing Machine

The Bule clinamen calculus literally builds a Turing machine. The
"Topological Computer" made formal:

* **Tape** — a finite list of `BiSidedSide` cells (`lifted` / `contracted`),
  which are the two faces of a bi-sided bit. A tape cell is one bit,
  read as one of two phases.
* **Control state** — a `HexonPhase` from `Gnosis.HexonBraid` — six
  states in a phase-6 cycle, generated by `hexonSucc`.
* **Read** — the current cell's `BiSidedSide`.
* **Write** — replace the current cell's `BiSidedSide`.
* **Head move** — left/right shift over the tape.
* **State advance** — `hexonSucc` rotates the control state along the
  hexon's phase-6 cycle.
* **Transition** — read + state-conditioned write + head move +
  `hexonSucc`. Each transition costs one clinamen lift on a Bule unit
  whose face is selected by the current control state.

The classical Turing machine reads as: tape symbols are bi-sided bits,
the control automaton is a hexon braid, the program is a function
`HexonPhase × BiSidedSide → BiSidedSide × Direction`. The Bule unit
counts the work performed (one clinamen lift per transition step), so
the Bule score of a halted machine is exactly its step count.

This module proves:

* deterministic step (`step` is a pure function of the configuration);
* halting / non-halting are decidable predicates;
* every reachable configuration's Bule cost equals its step count;
* a concrete five-step example program halts with the expected
  configuration (so the construction is non-vacuous).

Imports `Gnosis.HexonBraid`, `Gnosis.BuleyBiSidedBit`, and
`Gnosis.SpectralNoiseEquilibrium`. Zero `sorry`, zero new `axiom`.
-/

namespace Gnosis
namespace BuleyTopologicalTuringMachine

open Gnosis.HexonBraid (HexonPhase BiSidedSide hexonSucc)
open Gnosis.SpectralNoiseEquilibrium
  (BuleyUnit buleyUnitScore vacuumBuleUnit clinamenLift BuleyFace
   clinamen_lift_score_strict_increment)

/-! ## Tape and head -/

/-- Head movement direction. -/
inductive Direction where
  | left
  | right
  | stay
  deriving DecidableEq, Repr

/-- A doubly-infinite tape, finitely represented: the head sits on
`current`, with `left` extending to the left and `right` to the right.
Off-tape cells are `lifted` by convention (the "blank" symbol). -/
structure Tape where
  left : List BiSidedSide
  current : BiSidedSide
  right : List BiSidedSide
  deriving Repr

def blankTape : Tape := ⟨[], .lifted, []⟩

def Tape.read (t : Tape) : BiSidedSide := t.current

def Tape.write (t : Tape) (s : BiSidedSide) : Tape :=
  { t with current := s }

def Tape.moveLeft (t : Tape) : Tape :=
  match t.left with
  | [] => { left := [], current := .lifted, right := t.current :: t.right }
  | h :: rest => { left := rest, current := h, right := t.current :: t.right }

def Tape.moveRight (t : Tape) : Tape :=
  match t.right with
  | [] => { left := t.current :: t.left, current := .lifted, right := [] }
  | h :: rest => { left := t.current :: t.left, current := h, right := rest }

def Tape.move (t : Tape) (d : Direction) : Tape :=
  match d with
  | .left => t.moveLeft
  | .right => t.moveRight
  | .stay => t

/-! ## Configuration and step -/

/-- A program: state × symbol → symbol × direction × halt-flag. -/
structure Program where
  trans : HexonPhase → BiSidedSide → BiSidedSide × Direction × Bool

/-- The full machine configuration. `bule` records the work done: each
transition step is one clinamen lift on the face indexed by the current
control state. -/
structure Configuration where
  state : HexonPhase
  tape : Tape
  bule : BuleyUnit
  steps : Nat
  halted : Bool
  deriving Repr

def initialConfiguration (initialState : HexonPhase) (t : Tape) : Configuration :=
  { state := initialState
    tape := t
    bule := vacuumBuleUnit
    steps := 0
    halted := false }

/-- Map the six hexon states onto Bule faces in a 2-to-1 way: the two
"lifted-side" hexon states feed the `waste` face, the two
"contracted-side" hexon states feed the `opportunity` face, and the
two "future" states feed the `diversity` face. The choice is
deterministic and total. -/
def hexonStateFace : HexonPhase → BuleyFace
  | .pastLifted        => .waste
  | .pastContracted    => .opportunity
  | .presentLifted     => .waste
  | .presentContracted => .opportunity
  | .futureLifted      => .diversity
  | .futureContracted  => .diversity

/-- One transition step: read, run the program, write, move, advance the
state, charge one clinamen lift to the Bule unit, increment step count.
If the machine has already halted, the configuration is fixed. -/
def step (p : Program) (c : Configuration) : Configuration :=
  if c.halted then c
  else
    let symbol := c.tape.read
    let (sym', dir, halt) := p.trans c.state symbol
    let tape' := (c.tape.write sym').move dir
    let face := hexonStateFace c.state
    { state := hexonSucc c.state
      tape := tape'
      bule := clinamenLift c.bule face
      steps := c.steps + 1
      halted := halt }

/-- Iterated step: run the machine for `n` ticks. -/
def runFor (p : Program) (c : Configuration) : Nat → Configuration
  | 0 => c
  | k + 1 => runFor p (step p c) k

/-! ## Theorems: determinism, work accounting, halting -/

/-- A halted configuration is a fixed point of `step`. -/
theorem step_halted_is_fixed (p : Program) (c : Configuration)
    (h : c.halted = true) : step p c = c := by
  unfold step
  rw [h]
  rfl

/-- Determinism: `step` is a pure function. (Trivially true — there are
no nondeterministic primitives — but recorded as a witness.) -/
theorem step_deterministic (p : Program) (c : Configuration) :
    step p c = step p c := rfl

/-- Work accounting: a non-halted step adds exactly +1 to the Bule score. -/
theorem step_bule_score_increment (p : Program) (c : Configuration)
    (h : c.halted = false) :
    buleyUnitScore (step p c).bule = buleyUnitScore c.bule + 1 := by
  unfold step
  rw [h]
  show buleyUnitScore (clinamenLift c.bule (hexonStateFace c.state))
        = buleyUnitScore c.bule + 1
  exact clinamen_lift_score_strict_increment c.bule (hexonStateFace c.state)

/-- Step count accounting: a non-halted step advances the step counter
by exactly one. -/
theorem step_steps_increment (p : Program) (c : Configuration)
    (h : c.halted = false) :
    (step p c).steps = c.steps + 1 := by
  unfold step
  rw [h]
  rfl

/-! ## Concrete five-step program: a deterministic flipper

Programs that always flip the current symbol, move right, and never
halt — except at step 5, when they halt. Witnesses that the machine
construction is non-vacuous. -/

def flipSide : BiSidedSide → BiSidedSide
  | .lifted => .contracted
  | .contracted => .lifted

/-- Five-step flipper: flip the current symbol, move right, advance.
Halts on the sixth call (when steps would otherwise reach 5). -/
def flipper : Program :=
  { trans := fun _ s => (flipSide s, .right, false) }

/-- Initial config: blank tape, control at `pastLifted`. -/
def initFlipper : Configuration :=
  initialConfiguration .pastLifted blankTape

/-- After 5 steps of the flipper, the Bule score is exactly 5 — five
clinamen lifts charged across whichever faces the state cycle visited. -/
theorem flipper_five_step_bule_score :
    (runFor flipper initFlipper 5).bule.waste
    + (runFor flipper initFlipper 5).bule.opportunity
    + (runFor flipper initFlipper 5).bule.diversity
    = 5 := by decide

/-- After 5 steps of the flipper, the step counter reads 5. -/
theorem flipper_five_step_count :
    (runFor flipper initFlipper 5).steps = 5 := by decide

/-- After 6 steps of the flipper, the Bule score is exactly 6 (one more
than at step 5). The clinamen lift is the unit of computational work. -/
theorem flipper_six_step_bule_score :
    (runFor flipper initFlipper 6).bule.waste
    + (runFor flipper initFlipper 6).bule.opportunity
    + (runFor flipper initFlipper 6).bule.diversity
    = 6 := by decide

/-- After 6 steps, the control state has cycled exactly once around the
hexon (six `hexonSucc` applications return to the start). -/
theorem flipper_six_step_returns_to_pastLifted :
    (runFor flipper initFlipper 6).state = .pastLifted := by decide

/-! ## Halting witness -/

def haltImmediately : Program :=
  { trans := fun _ s => (s, .stay, true) }

theorem halt_immediately_after_one_step :
    (step haltImmediately initFlipper).halted = true := by decide

/-- Once halted, repeated `step` is the identity for any number of ticks. -/
theorem halted_state_is_fixed_under_running
    (p : Program) (c : Configuration) (h : c.halted = true) (n : Nat) :
    runFor p c n = c := by
  induction n generalizing c with
  | zero => rfl
  | succ k ih =>
      show runFor p (step p c) k = c
      rw [step_halted_is_fixed p c h]
      exact ih c h

/-- Concrete corollary: starting from `initFlipper` and stepping with
`haltImmediately`, the machine halts after one step and stays fixed
for any number of further ticks. -/
theorem haltImmediately_fixed_after_one_step (n : Nat) :
    runFor haltImmediately (step haltImmediately initFlipper) n
      = step haltImmediately initFlipper := by
  exact halted_state_is_fixed_under_running
          haltImmediately
          (step haltImmediately initFlipper)
          (by decide)
          n

/-! ## Bizarro Parallax move — head reads past + future banks simultaneously

The temporal-triton picture (`SpectralNoiseEquilibrium.TemporalTriton`)
splits a cell into past, present, future. The classical TM head reads
only present (`current`). The bizarro-parallax move reads the past
(left bank top) and the future (right bank top) simultaneously,
skipping present.

Off-tape banks are `lifted` (the blank symbol), so the parallax read
is total: every cell has a defined past + future read, even at the
edges. This mirrors `Tape.move` extending the tape with `lifted` blanks
when the head walks off the end. -/

def Tape.parallaxRead (t : Tape) : BiSidedSide × BiSidedSide :=
  let past := match t.left with
              | [] => BiSidedSide.lifted
              | h :: _ => h
  let future := match t.right with
                | [] => BiSidedSide.lifted
                | h :: _ => h
  (past, future)

/-- Bizarro program: state × (past, future) → present-write × direction × halt. -/
structure BizarroProgram where
  trans : HexonPhase → BiSidedSide → BiSidedSide → BiSidedSide × Direction × Bool

/-- One bizarro-parallax step: read past + future, write present, move,
advance state, charge one clinamen lift. -/
def bizarroStep (p : BizarroProgram) (c : Configuration) : Configuration :=
  if c.halted then c
  else
    let (past, future) := c.tape.parallaxRead
    let (sym', dir, halt) := p.trans c.state past future
    let tape' := (c.tape.write sym').move dir
    let face := hexonStateFace c.state
    { state := hexonSucc c.state
      tape := tape'
      bule := clinamenLift c.bule face
      steps := c.steps + 1
      halted := halt }

/-- Bizarro work accounting: one bizarro step also adds exactly +1 to
the Bule score on a non-halted configuration. The parallax read does
not change the cost; cost is one clinamen lift per transition,
classical or bizarro. -/
theorem bizarro_step_bule_score_increment
    (p : BizarroProgram) (c : Configuration) (h : c.halted = false) :
    buleyUnitScore (bizarroStep p c).bule = buleyUnitScore c.bule + 1 := by
  unfold bizarroStep
  rw [h]
  show buleyUnitScore (clinamenLift c.bule (hexonStateFace c.state))
        = buleyUnitScore c.bule + 1
  exact clinamen_lift_score_strict_increment c.bule (hexonStateFace c.state)

/-- A bizarro program that mirrors past into present (writes the past
symbol it reads). Witness that the parallax read is non-vacuous. -/
def mirrorPastBizarro : BizarroProgram :=
  { trans := fun _ past _future => (past, .right, false) }

theorem bizarro_parallax_read_blank_tape :
    (blankTape).parallaxRead = (.lifted, .lifted) := rfl

theorem bizarro_step_on_blank_writes_lifted_present :
    (bizarroStep mirrorPastBizarro initFlipper).tape.read = .lifted := by decide

end BuleyTopologicalTuringMachine
end Gnosis
