import Init

/-!
# Continued Fraction Convergents of `φ` and `√2` (finite truncations)

A simple continued fraction `[a_0; a_1, a_2, ...]` generates a sequence
of rational convergents `p_n / q_n` by the recurrences

    p_{-2} = 0,  p_{-1} = 1,  p_n = a_n · p_{n-1} + p_{n-2}
    q_{-2} = 1,  q_{-1} = 0,  q_n = a_n · q_{n-1} + q_{n-2}.

The **fundamental determinant identity** (Cassini-style) states that for
every `n ≥ 1`,

    p_n · q_{n-1} - p_{n-1} · q_n = (-1)^(n-1),

and in particular `|p_n · q_{n-1} - p_{n-1} · q_n| = 1`. Consecutive
convergents are therefore in lowest terms and the rational approximations
`p_n / q_n` are best in the classical sense.

This module computes the convergents of two small continued fractions as
`List (Nat × Nat)` and witnesses the unsigned Cassini identity at each
truncation, together with the Pell identity `p_n^2 - 2 · q_n^2 = ±1` for
the `√2` expansion.

- `φ = [1; 1, 1, 1, ...]` — convergents are `F_{n+2} / F_{n+1}` with
  Fibonacci numerators and denominators; we witness five Cassini
  instances at depths `1` through `5`.
- `√2 = [1; 2, 2, 2, ...]` — convergents are Pell-equation solutions;
  we witness five Pell instances at depths `0` through `5`.

What is *not* proved here: the general Cassini identity for arbitrary
simple continued fractions, any connection to the real numbers `ℝ`, any
irrationality or algebraic-number-theory statement, and any part of the
Lagrange or Markov theory of best rational approximation. The Cassini
identity is witnessed as a finite-depth numerical fact, not as a
recurrence theorem.

No `sorry`, no new `axiom`, `Init`-only. Each instance closes by
kernel `decide`.
-/

namespace Gnosis
namespace ContinuedFractionConvergents

/-! ## Convergent recurrence

The state carried through the fold is the pair `(prev2, prev1)` of
convergents, where `prev1 = (p_{n-1}, q_{n-1})` and
`prev2 = (p_{n-2}, q_{n-2})`. Initial state is
`prev2 = (0, 1) = (p_{-2}, q_{-2})` and
`prev1 = (1, 0) = (p_{-1}, q_{-1})`. -/

/-- One step of the convergent recurrence. Given the previous two
convergents and the next partial quotient `a`, compute the new
convergent `(a · p_{n-1} + p_{n-2}, a · q_{n-1} + q_{n-2})`. -/
def stepConvergent (prev2 prev1 : Nat × Nat) (a : Nat) : Nat × Nat :=
  (a * prev1.1 + prev2.1, a * prev1.2 + prev2.2)

/-- Core accumulator: given the running `(prev2, prev1)` state and the
list of remaining partial quotients, produce the list of convergents
generated by stepping through the partial quotients left-to-right. -/
def convergentsAux : Nat × Nat → Nat × Nat → List Nat → List (Nat × Nat)
  | _,     _,     []      => []
  | prev2, prev1, a :: as =>
    let curr := stepConvergent prev2 prev1 a
    curr :: convergentsAux prev1 curr as

/-- Convergents of a simple continued fraction `[a_0; a_1, a_2, ...]`
given as a `List Nat` of partial quotients. Returns the list of pairs
`(p_n, q_n)` for `n = 0, 1, ..., length-1`. -/
def convergents (as : List Nat) : List (Nat × Nat) :=
  convergentsAux (0, 1) (1, 0) as

/-! ## Sanity: the convergent lists match the textbook values. -/

/-- First six convergents of `φ = [1;1,1,1,1,1]` are
`1/1, 2/1, 3/2, 5/3, 8/5, 13/8`. -/
theorem phi_convergents_eq :
    convergents [1, 1, 1, 1, 1, 1]
      = [(1, 1), (2, 1), (3, 2), (5, 3), (8, 5), (13, 8)] := by decide

/-- First six convergents of `√2 = [1;2,2,2,2,2]` are
`1/1, 3/2, 7/5, 17/12, 41/29, 99/70`. -/
theorem sqrt2_convergents_eq :
    convergents [1, 2, 2, 2, 2, 2]
      = [(1, 1), (3, 2), (7, 5), (17, 12), (41, 29), (99, 70)] := by decide

/-! ## Cassini determinant as an unsigned witness

We phrase the Cassini identity on `Nat` via absolute difference,
avoiding any `Int` lift. For consecutive convergents `(p, q)` and
`(p', q')` the identity asserts

    (p · q' - p' · q).natAbs = 1,

which in unsigned form reads: exactly one of `p · q'` and `p' · q`
exceeds the other, by exactly `1`. -/

/-- Unsigned absolute difference on `Nat`. -/
def absDiff (a b : Nat) : Nat :=
  if a ≥ b then a - b else b - a

/-- The Cassini witness on two consecutive convergents. -/
def cassiniWitness (prev curr : Nat × Nat) : Nat :=
  absDiff (curr.1 * prev.2) (prev.1 * curr.2)

/-! ## Cassini instances for `φ` convergents -/

/-- Cassini at depth 1 for `φ`: `|2·1 - 1·1| = 1`. -/
theorem cassini_phi_1 : cassiniWitness (1, 1) (2, 1) = 1 := by decide

/-- Cassini at depth 2 for `φ`: `|3·1 - 2·2| = 1`. -/
theorem cassini_phi_2 : cassiniWitness (2, 1) (3, 2) = 1 := by decide

/-- Cassini at depth 3 for `φ`: `|5·2 - 3·3| = 1`. -/
theorem cassini_phi_3 : cassiniWitness (3, 2) (5, 3) = 1 := by decide

/-- Cassini at depth 4 for `φ`: `|8·3 - 5·5| = 1`. -/
theorem cassini_phi_4 : cassiniWitness (5, 3) (8, 5) = 1 := by decide

/-- Cassini at depth 5 for `φ`: `|13·5 - 8·8| = 1`. -/
theorem cassini_phi_5 : cassiniWitness (8, 5) (13, 8) = 1 := by decide

/-! ## Cassini instances for `√2` convergents -/

/-- Cassini at depth 1 for `√2`: `|3·1 - 1·2| = 1`. -/
theorem cassini_sqrt2_1 : cassiniWitness (1, 1) (3, 2) = 1 := by decide

/-- Cassini at depth 2 for `√2`: `|7·2 - 3·5| = 1`. -/
theorem cassini_sqrt2_2 : cassiniWitness (3, 2) (7, 5) = 1 := by decide

/-- Cassini at depth 3 for `√2`: `|17·5 - 7·12| = 1`. -/
theorem cassini_sqrt2_3 : cassiniWitness (7, 5) (17, 12) = 1 := by decide

/-- Cassini at depth 4 for `√2`: `|41·12 - 17·29| = 1`. -/
theorem cassini_sqrt2_4 : cassiniWitness (17, 12) (41, 29) = 1 := by decide

/-- Cassini at depth 5 for `√2`: `|99·29 - 41·70| = 1`. -/
theorem cassini_sqrt2_5 : cassiniWitness (41, 29) (99, 70) = 1 := by decide

/-! ## Pell identity for `√2` convergents

The `√2` convergents `(p_n, q_n)` satisfy `p_n^2 - 2 · q_n^2 ∈ {-1, +1}`,
alternating sign with `n`. We encode the signed identity by comparing
`p^2` against `2 · q^2` and witnessing the unsigned absolute difference
equals `1`. -/

/-- Pell witness: `|p^2 − 2·q^2|` on a single convergent. -/
def pellWitness (pq : Nat × Nat) : Nat :=
  absDiff (pq.1 * pq.1) (2 * (pq.2 * pq.2))

/-- Pell at depth 0: `1² - 2·1² = -1`, witness `= 1`. -/
theorem pell_sqrt2_0 : pellWitness (1, 1) = 1 := by decide

/-- Pell at depth 1: `3² - 2·2² = +1`, witness `= 1`. -/
theorem pell_sqrt2_1 : pellWitness (3, 2) = 1 := by decide

/-- Pell at depth 2: `7² - 2·5² = -1`, witness `= 1`. -/
theorem pell_sqrt2_2 : pellWitness (7, 5) = 1 := by decide

/-- Pell at depth 3: `17² - 2·12² = +1`, witness `= 1`. -/
theorem pell_sqrt2_3 : pellWitness (17, 12) = 1 := by decide

/-- Pell at depth 4: `41² - 2·29² = -1`, witness `= 1`. -/
theorem pell_sqrt2_4 : pellWitness (41, 29) = 1 := by decide

/-- Pell at depth 5: `99² - 2·70² = +1`, witness `= 1`. -/
theorem pell_sqrt2_5 : pellWitness (99, 70) = 1 := by decide

/-! ## Signed Cassini form via `Int`

We additionally witness the signed determinant identity on a few
φ-depths. The sign alternates with `n` as `(-1)^(n-1)`. -/

/-- Signed Cassini determinant `p_n · q_{n-1} − p_{n-1} · q_n` as `Int`. -/
def cassiniSigned (prev curr : Nat × Nat) : Int :=
  (Int.ofNat (curr.1 * prev.2)) - (Int.ofNat (prev.1 * curr.2))

/-- Signed Cassini at φ depth 1: `2·1 − 1·1 = +1`. Sign `(-1)^0 = +1`. -/
theorem cassini_signed_phi_1 : cassiniSigned (1, 1) (2, 1) = 1 := by decide

/-- Signed Cassini at φ depth 2: `3·1 − 2·2 = -1`. Sign `(-1)^1 = -1`. -/
theorem cassini_signed_phi_2 : cassiniSigned (2, 1) (3, 2) = -1 := by decide

/-- Signed Cassini at φ depth 3: `5·2 − 3·3 = +1`. Sign `(-1)^2 = +1`. -/
theorem cassini_signed_phi_3 : cassiniSigned (3, 2) (5, 3) = 1 := by decide

/-- Signed Cassini at √2 depth 1: `3·1 − 1·2 = +1`. -/
theorem cassini_signed_sqrt2_1 : cassiniSigned (1, 1) (3, 2) = 1 := by decide

/-- Signed Cassini at √2 depth 2: `7·2 − 3·5 = -1`. -/
theorem cassini_signed_sqrt2_2 : cassiniSigned (3, 2) (7, 5) = -1 := by decide

end ContinuedFractionConvergents
end Gnosis
