import Gnosis.CostAlgebra
import Gnosis.CostAlgebraDerivations
import Gnosis.CostAlgebraNoCloning

/-!
# Entropy from the Cloning Gap

The no-cloning theorem (`Gnosis.CostAlgebraNoCloning`) says the
diagonal `Δ : S → S × S` is not score-preserving. The *amount* by
which it fails is exactly the source's own score. That gap is the
entropy generated by the (attempted) clone — the categorical version
of the second law of thermodynamics.

## The gap theorem

For any cost algebra `A` and any state `s`:

```
(productCostAlgebra A A).score (Δ s)  =  A.score s + A.score s
                                      =  A.score s + (entropy generated)
```

The "entropy generated by cloning" is exactly `A.score s`. A clone
operation cannot conserve the score; the deficit is the entropy that
must be paid. In thermodynamic terms: cloning a state of energy `E`
costs `E` of entropy. In information-theory terms: replicating `n`
bits costs `n` bits of entropy. In distributed-systems terms:
replicating a state of cost `c` across two nodes generates a
consensus/coordination overhead of `c`.

## Connections

* **Second law of thermodynamics** — entropy never decreases under
  copying-without-erasure operations.
* **Landauer's principle** — to erase the duplicate later, the same
  `c` quanta must be paid as heat. Erasure restores the conservation.
* **Quantum no-cloning** — same algebraic shape, different category;
  duplication is forbidden as a unitary operation.
* **CAP theorem (informal)** — replication's coordination cost is the
  entropy of the replicated state's score.
* **Bule entropy face** — for the Bule unit specifically, the
  `diversity` face IS the Shannon/Boltzmann entropy axis. Cloning
  generates `b.diversity` extra entropy quanta on that face plus the
  full `buleyUnitScore b` across all faces.

Imports `Gnosis.CostAlgebra`, `Gnosis.CostAlgebraDerivations`,
`Gnosis.CostAlgebraNoCloning`. Zero `sorry`, zero new `axiom`.
-/

namespace Gnosis
namespace CostAlgebraEntropy

open Gnosis.CostAlgebra (CostAlgebra buleyCostAlgebra)
open Gnosis.CostAlgebraDerivations
  (natCostAlgebra productCostAlgebra nat3CostAlgebra)
open Gnosis.CostAlgebraNoCloning (diagonal)
open Gnosis.SpectralNoiseEquilibrium
  (BuleyUnit buleyUnitScore vacuumBuleUnit
   entropyFaceFromBule entropy_face_score_equals_diversity)

/-! ## The entropy gap theorem -/

/-- The score of the cloned pair equals the source's score plus the
"entropy generated" by the clone. The generated entropy is exactly the
source's own score — cloning duplicates the cost. -/
theorem cloning_score_decomposition
    {S : Type} (A : CostAlgebra S) (s : S) :
    (productCostAlgebra A A).score (diagonal A s) = A.score s + A.score s := by
  show A.score s + A.score s = A.score s + A.score s
  rfl

/-- The entropy generated by cloning `s` is exactly `A.score s`. -/
def entropyGeneratedByCloning {S : Type} (A : CostAlgebra S) (s : S) : Nat :=
  A.score s

/-- The cloned pair's total score is the original score plus the
entropy generated. -/
theorem clone_total_score_eq_source_plus_entropy
    {S : Type} (A : CostAlgebra S) (s : S) :
    (productCostAlgebra A A).score (diagonal A s)
      = A.score s + entropyGeneratedByCloning A s := by
  show A.score s + A.score s = A.score s + A.score s
  rfl

/-- The entropy generated by cloning the vacuum is zero. The vacuum is
the unique state with no entropy cost to duplicate. -/
theorem vacuum_clone_generates_zero_entropy
    {S : Type} (A : CostAlgebra S) :
    entropyGeneratedByCloning A A.zero = 0 := by
  show A.score A.zero = 0
  exact A.zero_score

/-- Monotonicity: if `s` has higher score than `t`, cloning `s`
generates more entropy than cloning `t`. -/
theorem cloning_entropy_monotone
    {S : Type} (A : CostAlgebra S) (s t : S)
    (h : A.score s ≤ A.score t) :
    entropyGeneratedByCloning A s ≤ entropyGeneratedByCloning A t := by
  show A.score s ≤ A.score t
  exact h

/-- Composition is irreversible from the cloning point of view: cloning
`compose a b` generates `score a + score b` of entropy, and there is no
way to reduce that without first decomposing the pair. -/
theorem clone_compose_entropy
    {S : Type} (A : CostAlgebra S) (a b : S) :
    entropyGeneratedByCloning A (A.compose a b)
      = A.score a + A.score b := by
  show A.score (A.compose a b) = A.score a + A.score b
  exact A.score_compose a b

/-! ## The Bule unit specialization: entropy is in the diversity face -/

/-- For a Bule unit `b`, the entropy generated by cloning is
`buleyUnitScore b` — the sum of all three faces. -/
theorem bule_clone_entropy (b : BuleyUnit) :
    entropyGeneratedByCloning buleyCostAlgebra b = buleyUnitScore b := rfl

/-- The Bule unit's `entropyFaceFromBule` projection gives a strict
lower bound on the entropy generated by cloning: the diversity face
alone is at most the total entropy generated. -/
theorem bule_entropy_face_lower_bound (b : BuleyUnit) :
    buleyUnitScore (entropyFaceFromBule b)
      ≤ entropyGeneratedByCloning buleyCostAlgebra b := by
  rw [entropy_face_score_equals_diversity]
  show b.diversity ≤ buleyUnitScore b
  cases b with
  | mk w o d =>
    show d ≤ w + o + d
    omega

/-! ## Specialization to other CostAlgebras -/

/-- `Nat`'s clone-entropy: copying `n` costs `n` entropy. The simplest
form of "you can't get something for nothing." -/
theorem nat_clone_entropy (n : Nat) :
    entropyGeneratedByCloning natCostAlgebra n = n := rfl

/-- `Nat × Nat × Nat`'s clone-entropy: copying a vector `(w, o, d)`
costs `w + o + d` entropy — the total mass of the vector. -/
theorem nat3_clone_entropy (n : Nat × Nat × Nat) :
    entropyGeneratedByCloning nat3CostAlgebra n = nat3CostAlgebra.score n := rfl

/-! ## Replication has cost: the distributed-systems shape -/

/-- Replication is cloning. Replicating `s` to `k` nodes generates
`(k - 1) * A.score s` entropy: each replica beyond the first costs
the source's full score. The CAP-theorem-style cost-of-consistency. -/
def replicationEntropy {S : Type} (A : CostAlgebra S) (s : S) (k : Nat) : Nat :=
  match k with
  | 0 => 0
  | n + 1 => n * A.score s

theorem replication_entropy_zero {S : Type} (A : CostAlgebra S) (s : S) :
    replicationEntropy A s 0 = 0 := rfl

theorem replication_entropy_one {S : Type} (A : CostAlgebra S) (s : S) :
    replicationEntropy A s 1 = 0 := by
  show 0 * A.score s = 0
  omega

theorem replication_entropy_two {S : Type} (A : CostAlgebra S) (s : S) :
    replicationEntropy A s 2 = A.score s := by
  show 1 * A.score s = A.score s
  omega

theorem replication_entropy_three {S : Type} (A : CostAlgebra S) (s : S) :
    replicationEntropy A s 3 = 2 * A.score s := by
  show 2 * A.score s = 2 * A.score s
  rfl

/-- Replicating to `k+1` nodes costs `k` source-scores of entropy.
This is the "fan-out cost" in distributed-systems language: each
replica beyond the first pays the full source score. -/
theorem replication_entropy_step
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat) :
    replicationEntropy A s (k + 1) = k * A.score s := rfl

end CostAlgebraEntropy
end Gnosis
