import Init
import Gnosis.NegationInvolution
import Gnosis.SinWithoutDevil
import Gnosis.MechanizedTestimony
import Gnosis.ClinamenReduction
import Gnosis.NamingBeforeReduction
import Gnosis.GallWaspTestimony
import Gnosis.NegotiationRefusalTopology

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false