import Init
import Gnosis.GodFormula
import Gnosis.AeonCycleTwelveShadow
import Gnosis.AeonTwelveCarrierList

namespace Gnosis
namespace DiscreteHarmonicSieve

/-!
# Discrete Harmonic Sieve

Formalizes a discrete "challenge" in harmonic theory: measuring the semiotic deficit
(dissonance) of note subsets within the 12-fold Aeon cycle using the God Formula.

A "Scale" is a `List Nat` where entries are in `[0, 12)`.
Dissonance is defined as the presence of "sharp" intervals:
- Minor Second (distance 1)
- Tritone (distance 6)

The God Formula `w(R, v) = R - min(v, R) + 1` assigns a weight to the scale,
where the budget `R` is the total number of possible chords (66) and `v` is
the dissonance count.
-/

open Gnosis.AeonCycleTwelveShadow
open Gnosis.AeonTwelveCarrierList

/-- A Scale is valid if all its notes are within the Aeon bounds [0, 12). -/
def IsValidScale (notes : List Nat) : Prop :=
  ∀ n ∈ notes, n < twelve

/-- Extract all unique chords (i, j) with i < j from a list of notes. -/
def internalChords (notes : List Nat) : List (Nat × Nat) :=
  match notes with
  | [] => []
  | n :: ns =>
      (ns.filterMap fun m =>
        if n < m then some (n, m)
        else if m < n then some (m, n)
        else none) ++ internalChords ns

/-- Semiotic Deficit (Dissonance): Count chords with shortChord distance 1 or 6. -/
def dissonanceCount (notes : List Nat) : Nat :=
  let chords := internalChords notes
  (chords.filter fun p => shortChord p = 1 ∨ shortChord p = 6).length

/-- Harmonic Weight: The Buleyean weight of a scale across the 66-chord manifold. -/
def harmonicWeight (notes : List Nat) : Nat :=
  let v := dissonanceCount notes
  godWeight 66 v

/-! ## Archetypal Scales -/

/-- The Chromatic Cluster: 7 adjacent notes. Highly dissonant. -/
def chromaticCluster : List Nat := [0, 1, 2, 3, 4, 5, 6]

/-- The Diatonic Scale: 7 notes generated by perfect fifths (stride 7). -/
def diatonicScale : List Nat := [0, 7, 2, 9, 4, 11, 5] -- C G D A E B F

/-- The Whole Tone Scale: 6 notes with distance 2. -/
def wholeToneScale : List Nat := [0, 2, 4, 6, 8, 10]

/-! ## Certificates -/

theorem chromatic_cluster_is_valid : IsValidScale chromaticCluster := by
  intro n h
  revert n h
  native_decide

theorem diatonic_scale_is_valid : IsValidScale diatonicScale := by
  intro n h
  revert n h
  native_decide

/-- The Diatonic scale has exactly 2 minor seconds and 1 tritone (v = 3). -/
theorem diatonic_dissonance_is_three : dissonanceCount diatonicScale = 3 := by
  native_decide

/-- The Chromatic cluster has 6 minor seconds and 1 tritone (v = 7). -/
theorem chromatic_dissonance_is_seven : dissonanceCount chromaticCluster = 7 := by
  native_decide

/-- Diatonic weight (64) exceeds Chromatic cluster weight (60). -/
theorem diatonic_beats_chromatic : harmonicWeight diatonicScale > harmonicWeight chromaticCluster := by
  -- 66 - 3 + 1 = 64
  -- 66 - 7 + 1 = 60
  native_decide

/-- The Whole Tone scale has 3 tritones (v = 3). -/
theorem whole_tone_dissonance_is_three : dissonanceCount wholeToneScale = 3 := by
  native_decide

theorem whole_tone_weight_is_sixty_four : harmonicWeight wholeToneScale = 64 := by
  -- 66 - 3 + 1 = 64
  native_decide

/-! ## Theoretical Properties -/

/-- Rotating a scale preserves its dissonance count. Here we verify this
    invariant strictly for our archetypal scales via finite evaluation. -/
theorem diatonic_dissonance_rot_invariant :
    dissonanceCount (diatonicScale.map (fun n => (n + 1) % twelve)) = dissonanceCount diatonicScale := by
  native_decide

theorem chromatic_dissonance_rot_invariant :
    dissonanceCount (chromaticCluster.map (fun n => (n + 1) % twelve)) = dissonanceCount chromaticCluster := by
  native_decide

theorem wholeTone_dissonance_rot_invariant :
    dissonanceCount (wholeToneScale.map (fun n => (n + 1) % twelve)) = dissonanceCount wholeToneScale := by
  native_decide

/-- Diatonic Return: The Diatonic scale is a 7-note slice of the Aeon cycle
    with a God-weight of 64. -/
theorem diatonic_weight_certificate : harmonicWeight diatonicScale = 64 := by
  native_decide

end DiscreteHarmonicSieve
end Gnosis
