import Init
import Gnosis.NegationInvolution
import Gnosis.SinWithoutDevil
import Gnosis.NamingBeforeReduction
import Gnosis.GallWaspTestimony
import Gnosis.DevilDetailer
import Gnosis.ClinamenReduction

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false