import Init

/-!
# Fano plane incidence

Finite `Init`-only incidence scaffold for the seven-point Fano plane.

The central contract is the pair-completion theorem: every distinct pair of
points determines a unique third point on its Fano line. This is the incidence
piece needed before routing pair collisions into a Plucker-label mesh.
-/

namespace Gnosis
namespace FanoIncidence

/-- The seven points of the Fano plane. -/
inductive FanoPoint
  | p0 | p1 | p2 | p3 | p4 | p5 | p6
  deriving DecidableEq, Repr

open FanoPoint

/-- Numerical address for embedding Fano points into larger finite carriers. -/
def pointIndex : FanoPoint → Nat
  | p0 => 0
  | p1 => 1
  | p2 => 2
  | p3 => 3
  | p4 => 4
  | p5 => 5
  | p6 => 6

theorem pointIndex_lt_seven (p : FanoPoint) : pointIndex p < 7 := by
  cases p <;> decide

/-- Completing point for any ordered pair. Diagonal values are harmless;
the theorem below only uses distinct pairs.

The seven unoriented Fano lines encoded here are:
`012`, `034`, `065`, `135`, `146`, `236`, and `254`.
-/
def completePair : FanoPoint → FanoPoint → FanoPoint
  | p0, p1 => p2
  | p1, p0 => p2
  | p0, p2 => p1
  | p2, p0 => p1
  | p1, p2 => p0
  | p2, p1 => p0
  | p0, p3 => p4
  | p3, p0 => p4
  | p0, p4 => p3
  | p4, p0 => p3
  | p3, p4 => p0
  | p4, p3 => p0
  | p0, p6 => p5
  | p6, p0 => p5
  | p0, p5 => p6
  | p5, p0 => p6
  | p6, p5 => p0
  | p5, p6 => p0
  | p1, p3 => p5
  | p3, p1 => p5
  | p1, p5 => p3
  | p5, p1 => p3
  | p3, p5 => p1
  | p5, p3 => p1
  | p1, p4 => p6
  | p4, p1 => p6
  | p1, p6 => p4
  | p6, p1 => p4
  | p4, p6 => p1
  | p6, p4 => p1
  | p2, p3 => p6
  | p3, p2 => p6
  | p2, p6 => p3
  | p6, p2 => p3
  | p3, p6 => p2
  | p6, p3 => p2
  | p2, p5 => p4
  | p5, p2 => p4
  | p2, p4 => p5
  | p4, p2 => p5
  | p5, p4 => p2
  | p4, p5 => p2
  | a, _ => a

/-- Incidence relation generated by the completion table. For distinct
`a` and `b`, `fanoLine a b c` means that `c` is the completing point of
the line through `a` and `b`. -/
def fanoLine (a b c : FanoPoint) : Prop :=
  a ≠ b ∧ c = completePair a b

theorem completePair_ne_left (a b : FanoPoint) (hab : a ≠ b) :
    completePair a b ≠ a := by
  cases a <;> cases b <;> simp [completePair] at hab ⊢

theorem completePair_ne_right (a b : FanoPoint) (hab : a ≠ b) :
    completePair a b ≠ b := by
  cases a <;> cases b <;> simp [completePair] at hab ⊢

/-- Every distinct pair has a unique third point on its Fano line. -/
theorem distinct_pair_unique_completion (a b : FanoPoint) (hab : a ≠ b) :
    completePair a b ≠ a ∧
    completePair a b ≠ b ∧
    fanoLine a b (completePair a b) ∧
    ∀ c, c ≠ a → c ≠ b → fanoLine a b c → c = completePair a b :=
  ⟨completePair_ne_left a b hab,
    completePair_ne_right a b hab,
    ⟨hab, rfl⟩,
    fun _ _ _ hline => hline.2⟩

/-- Existential form of the same incidence contract. -/
theorem distinct_pair_has_unique_completion (a b : FanoPoint) (hab : a ≠ b) :
    ∃ c,
      c ≠ a ∧ c ≠ b ∧ fanoLine a b c ∧
        ∀ d, d ≠ a → d ≠ b → fanoLine a b d → d = c := by
  refine ⟨completePair a b, ?_⟩
  exact distinct_pair_unique_completion a b hab

end FanoIncidence
end Gnosis
