import Init
import Gnosis.BlindMethodBarrier
import Gnosis.AlgebrizationBarrier
import Gnosis.NaturalProofsBarrier
import Gnosis.BarrierUnification

/-
  FiveWalls.lean
  ==============

  Three walls usually mean FIVE: the ternary of named barriers, generated by the
  two interference modes — constructive and destructive — exactly the clinamen /
  trit signature (a ternary primitive manifests through a +1 / -1 interference
  pair; cf. the swerve and "the trill"). And the split is mathematically real,
  not just framework: the barriers fail by two distinct mechanisms.

    ── DESTRUCTIVE interference (the signal CANCELS) ─────────────────────────────
      The distinguishing signal vanishes: the method, reading only a view, cannot
      track the truth. `destructive_blindness`. Instances: RELATIVIZATION (view =
      oracle) and ALGEBRIZATION (view = oracle + extension).

    ── CONSTRUCTIVE interference (the signal REINFORCES) ─────────────────────────
      The signal over-commits: a test large enough to accept, yet useful enough to
      reject a whole covering family, collapses under a covering/indistinguishability
      hypothesis. `constructive_overreach`. Instance: NATURAL PROOFS (large +
      useful property = a distinguisher = a crypto break).

  THE FIVE: {relativization, algebrization} from the destructive mode, {natural
  proofs} from the constructive mode, and the two MODES themselves as the
  generators. Three named techniques + two interference modes = five walls.

  Init + the barrier modules. Zero `sorry`, zero new `axiom`.
-/

namespace FiveWalls

/-! ## The two interference modes (the generators) -/

/-- **DESTRUCTIVE interference — cancellation.** A method reading only a view `v`
    cannot match two opposite truths sharing that view: the distinguishing signal
    cancels to nothing. (= `BarrierUnification.view_blind_must_err`; the `-1` mode.) -/
theorem destructive_blindness {V : Type} (M : V → Bool) (v : V) {t₁ t₂ : Bool}
    (hdiff : t₁ ≠ t₂) : ¬ (M v = t₁ ∧ M v = t₂) :=
  BarrierUnification.view_blind_must_err M v hdiff

/-- **CONSTRUCTIVE interference — reinforcement.** A test `P` that accepts
    something (large) yet rejects an entire covering family (useful) collapses
    under a covering hypothesis (anything accepted-somewhere is accepted on the
    family): the signal reinforces past the cover and breaks. The `+1` mode,
    generalizing the natural-proofs argument to any domain. -/
theorem constructive_overreach {α : Type} (P : α → Bool) (cover : Nat → α)
    (hcover : (∃ a, P a = true) → ∃ s, P (cover s) = true)
    (hlarge : ∃ a, P a = true)
    (huseful : ∀ s, P (cover s) = false) : False := by
  obtain ⟨s, hs⟩ := hcover hlarge
  rw [huseful s] at hs
  exact Bool.noConfusion hs

/-! ## The five walls: three named techniques, two modes -/

/-- **THE FIVE WALLS.** The two destructive instances (relativization,
    algebrization) and the one constructive instance (natural proofs, conditional
    on the hardness hypothesis), bundled — the ternary of techniques carried by
    the two interference modes. -/
theorem five_walls
    (G : NaturalProofsBarrier.Generator)
    (hcrypto : NaturalProofsBarrier.CryptoIndistinguishable G) :
    -- DESTRUCTIVE mode, instance 1 — relativization (view = oracle)
    (∀ M : BlindMethodBarrier.BlindMethod,
        ∃ w₁ w₂ : BlindMethodBarrier.World,
          w₁.charge = w₂.charge
            ∧ ¬ (BlindMethodBarrier.SoundOn M w₁ ∧ BlindMethodBarrier.SoundOn M w₂))
    -- DESTRUCTIVE mode, instance 2 — algebrization (view = oracle + extension)
    ∧ (∀ M : AlgebrizationBarrier.AlgMethod,
        ∃ w₁ w₂ : AlgebrizationBarrier.World,
          w₁.view = w₂.view
            ∧ ¬ (AlgebrizationBarrier.SoundOn M w₁ ∧ AlgebrizationBarrier.SoundOn M w₂))
    -- CONSTRUCTIVE mode, instance — natural proofs (large + useful = a break)
    ∧ (¬ ∃ P : NaturalProofsBarrier.Property, NaturalProofsBarrier.Natural P G) :=
  ⟨BlindMethodBarrier.no_blind_method_is_universally_sound,
   AlgebrizationBarrier.no_alg_method_is_universally_sound,
   NaturalProofsBarrier.no_natural_property_under_crypto G hcrypto⟩

end FiveWalls
