import Gnosis.CostAlgebra
import Gnosis.CostAlgebraEntropy
import Gnosis.SpectralNoiseEquilibrium
import Gnosis.BuleySelfSimilarityViolation

/-!
# Landauer Hot-Replica Admission

A concrete operational protocol for the inference mesh, derived
directly from the no-cloning theorem and the cost-algebra entropy
formula.

## The setup

A layer-node carries a `BuleyUnit`-shaped operational state with score
`score s`. Each node has a fixed `LandauerCeiling` — the maximum
heat-budget (Bule mass) it can absorb before melting. A "Hot Replica"
request asks the node to fan its state out to `k ≥ 1` total replicas
(itself plus `k − 1` copies).

Per `Gnosis.CostAlgebraEntropy.replicationEntropy`, replicating to `k`
total replicas generates `(k − 1) · score s` of entropy — the
"Landauer payment." For the request to be admissible, the source's
own score plus the replication entropy must fit inside the ceiling:

```
score s + (k − 1) · score s = k · score s  ≤  ceiling
```

If admissible, the replica is granted. If not, the deficit is
deterministic: the node must first cool its state (apply
`clinamenContract` enough times) to bring `k · score s` under the
ceiling, then re-evaluate. The remediation count is also derived,
matching the `BuleySelfSimilarityViolation` shape.

## The closing claim

This is the formal admission protocol the coordinator should apply on
every replica request: **the no-cloning theorem isn't merely a
constraint — it gives the controller a deterministic rule for when
to grant, when to defer, and how much cooling to demand.**

Imports `Gnosis.CostAlgebra`, `Gnosis.CostAlgebraEntropy`,
`Gnosis.SpectralNoiseEquilibrium`, and `Gnosis.BuleySelfSimilarityViolation`.
Zero `sorry`, zero new `axiom`.
-/

namespace Gnosis
namespace LandauerHotReplica

open Gnosis.CostAlgebra (CostAlgebra buleyCostAlgebra)
open Gnosis.CostAlgebraEntropy (replicationEntropy)
open Gnosis.SpectralNoiseEquilibrium
  (BuleyUnit buleyUnitScore vacuumBuleUnit)

/-! ## Ceiling, deficit, admission -/

abbrev LandauerCeiling := Nat

/-- The total heat the system would carry after replicating `s` to
`k` total replicas: the source's score plus the replication entropy
generated by the `k − 1` clones. -/
def replicaTotalHeat
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat) : Nat :=
  A.score s + replicationEntropy A s k

/-- For `k ≥ 1`, the total heat is `k · score s`: the source plus
`(k − 1)` extra copies. -/
theorem replica_total_heat_step
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat) :
    replicaTotalHeat A s (k + 1) = (k + 1) * A.score s := by
  show A.score s + k * A.score s = (k + 1) * A.score s
  rw [Nat.succ_mul]
  exact Nat.add_comm _ _

theorem replica_total_heat_one
    {S : Type} (A : CostAlgebra S) (s : S) :
    replicaTotalHeat A s 1 = A.score s := by
  unfold replicaTotalHeat
  show A.score s + 0 = A.score s
  rfl

/-- A replication request is admissible iff the total heat fits inside
the ceiling. -/
def admitsReplication
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) : Prop :=
  replicaTotalHeat A s k ≤ ceiling

/-- For a single replica (`k = 1`), the request is admissible iff the
source's score itself fits the ceiling. -/
theorem admits_one_replica_iff_score_fits
    {S : Type} (A : CostAlgebra S) (s : S) (ceiling : LandauerCeiling) :
    admitsReplication A s 1 ceiling ↔ A.score s ≤ ceiling := by
  unfold admitsReplication
  rw [replica_total_heat_one]

/-- For any `k ≥ 1`, admission iff `k · score s ≤ ceiling`. -/
theorem admits_replication_iff_k_score_fits
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) :
    admitsReplication A s (k + 1) ceiling ↔ (k + 1) * A.score s ≤ ceiling := by
  unfold admitsReplication
  rw [replica_total_heat_step]

/-! ## The deficit and corrective remediation -/

/-- The Landauer deficit: how much the request exceeds the ceiling. -/
def landauerDeficit
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) : Nat :=
  replicaTotalHeat A s k - ceiling

theorem deficit_zero_iff_admitted
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) :
    landauerDeficit A s k ceiling = 0 ↔ admitsReplication A s k ceiling := by
  unfold landauerDeficit admitsReplication
  constructor
  · intro h; omega
  · intro h; omega

theorem deficit_positive_iff_rejected
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) :
    landauerDeficit A s k ceiling > 0
      ↔ replicaTotalHeat A s k > ceiling := by
  unfold landauerDeficit
  constructor
  · intro h; omega
  · intro h; omega

/-! ## Concrete tower-level admission decisions -/

/-- A Bule unit with score 18 (Trihexon-pressure) replicating to 2
total replicas needs 36 Bule mass total — admissible only if the
ceiling is at least 36. -/
theorem trihexon_two_replica_total_heat_is_thirty_six :
    replicaTotalHeat buleyCostAlgebra ⟨18, 0, 0⟩ 2 = 36 := by decide

theorem trihexon_two_replica_admitted_at_ceiling_36 :
    admitsReplication buleyCostAlgebra ⟨18, 0, 0⟩ 2 36 := by
  unfold admitsReplication
  show buleyUnitScore (⟨18, 0, 0⟩ : BuleyUnit)
        + replicationEntropy buleyCostAlgebra ⟨18, 0, 0⟩ 2 ≤ 36
  decide

theorem trihexon_two_replica_rejected_at_ceiling_35 :
    ¬ admitsReplication buleyCostAlgebra ⟨18, 0, 0⟩ 2 35 := by
  unfold admitsReplication
  show ¬ (buleyUnitScore (⟨18, 0, 0⟩ : BuleyUnit)
            + replicationEntropy buleyCostAlgebra ⟨18, 0, 0⟩ 2 ≤ 35)
  decide

/-- A Hexon-pressure (score 6) Bule unit replicating to 3 nodes (one
source plus 2 copies) costs 18 Bule mass total. -/
theorem hexon_three_replica_total_heat_is_eighteen :
    replicaTotalHeat buleyCostAlgebra ⟨6, 0, 0⟩ 3 = 18 := by decide

theorem hexon_three_replica_admitted_at_ceiling_18 :
    admitsReplication buleyCostAlgebra ⟨6, 0, 0⟩ 3 18 := by
  unfold admitsReplication
  decide

theorem hexon_three_replica_deficit_at_ceiling_10 :
    landauerDeficit buleyCostAlgebra ⟨6, 0, 0⟩ 3 10 = 8 := by
  unfold landauerDeficit
  show replicaTotalHeat buleyCostAlgebra ⟨6, 0, 0⟩ 3 - 10 = 8
  decide

/-! ## The vacuum is always admissible -/

/-- Replicating the vacuum to any number of nodes is free: the vacuum's
score is zero, so total heat is zero, which fits inside any ceiling.
This matches `vacuum_is_duplicable` from the no-cloning module — the
vacuum is the unique state for which replication has no cost. -/
theorem vacuum_replication_always_admitted
    (k : Nat) (ceiling : LandauerCeiling) :
    admitsReplication buleyCostAlgebra vacuumBuleUnit k ceiling := by
  unfold admitsReplication replicaTotalHeat replicationEntropy
  cases k with
  | zero =>
      show buleyUnitScore vacuumBuleUnit + 0 ≤ ceiling
      show 0 + 0 ≤ ceiling
      omega
  | succ n =>
      show buleyUnitScore vacuumBuleUnit + n * buleyCostAlgebra.score vacuumBuleUnit ≤ ceiling
      show 0 + n * 0 ≤ ceiling
      omega

/-! ## Corrective cooling: how many clinamen contracts to admit a
rejected request -/

/-- Per-replica cooling: to admit `k+1` total replicas under the
`ceiling`, the source's score must first drop to at most
`ceiling / (k+1)`. The number of clinamen contracts needed is
`score s - ceiling / (k+1)` (saturating at zero). -/
def coolingContractsForReplica
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) : Nat :=
  A.score s - ceiling / (k + 1)

/-- After cooling by exactly `coolingContractsForReplica` contracts,
the source's effective score is `ceiling / (k+1)`, and the
`(k+1)·score` total fits inside the ceiling (rounded down). -/
theorem cooling_makes_replication_fit
    {S : Type} (A : CostAlgebra S) (s : S) (k : Nat)
    (ceiling : LandauerCeiling) :
    (k + 1) * (A.score s - coolingContractsForReplica A s k ceiling)
      ≤ ceiling := by
  unfold coolingContractsForReplica
  -- Goal: (k+1) * (score s - (score s - ceiling / (k+1))) ≤ ceiling
  -- The inner subtraction is min(score s, ceiling / (k+1)) — Nat saturating
  -- and (k+1) * min(...) ≤ (k+1) * (ceiling / (k+1)) ≤ ceiling
  by_cases h : A.score s ≤ ceiling / (k + 1)
  · -- score s already small enough; subtract gives 0
    have hzero : A.score s - (A.score s - ceiling / (k + 1)) = A.score s := by omega
    rw [hzero]
    -- Goal: (k+1) * score s ≤ ceiling, where score s ≤ ceiling/(k+1)
    have hmul : (k + 1) * A.score s ≤ (k + 1) * (ceiling / (k + 1)) :=
      Nat.mul_le_mul_left (k + 1) h
    have hdiv : (k + 1) * (ceiling / (k + 1)) ≤ ceiling := Nat.mul_div_le ceiling (k + 1)
    omega
  · have hpos : A.score s > ceiling / (k + 1) := by omega
    have heq : A.score s - (A.score s - ceiling / (k + 1)) = ceiling / (k + 1) := by omega
    rw [heq]
    exact Nat.mul_div_le ceiling (k + 1)

end LandauerHotReplica
end Gnosis
