import Init
import Gnosis.NegationInvolution
import Gnosis.SinWithoutDevil
import Gnosis.ClinamenReduction
import Gnosis.MechanizedTestimony
import Gnosis.ForkRaceFoldTrinity

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false