import Init
import Gnosis.FoilZeroDragCompatibility

/-!
# Provable Randomness Boundary

This module dares to emit bytes, but keeps the claim honest.

No deterministic program can manufacture new entropy from an unobserved void.
What it can do is transform a seed by a proved finite permutation, so that a
full period visits every byte exactly once before repeating.

This follows the Rustic Church / Lacey-cipher stance:

* entropy harvesting is a projection, not a source theorem;
* discrete systems are allowed to find the edge boundary;
* a ciphertext/noise surface is useful when it remains valid structured data.
* FOIL may import ambient entropy as an observed runtime certificate; Lean then
  proves the bounded projection after that certificate exists.

The generator below is a tiny counter-mode byte generator:

* `weylByte seed k = seed + 73 * k (mod 256)`;
* `mixByte x = 157 * x + 101 (mod 256)`;
* `provableByte seed k = mixByte (weylByte seed k)`.

Because `73` and `157` are odd, the intended mathematical reason is that both
maps are permutations of `Z / 256 Z`. In this Init-only file we certify the
finite statement directly over all 256 bytes with `native_decide`.

This is a provable boundary sampler, not a cryptographic PRNG.
Zero `sorry`, zero new `axiom`, `Init` only.
-/

namespace Gnosis
namespace ProvableRandomness

/-- Byte modulus used by the finite certificate. -/
def byteModulus : Nat := 256

/-- Lacey works over a 54-dimensional helix. -/
def laceyDimensionCount : Nat := 54

/-- Knotchain DNA content hash dimension from `open-source/bitwise`. -/
def laceyDnaDimension : Nat := 39

/-- Seeded Weyl counter on bytes. The odd stride should visit all byte slots. -/
def weylByte (seed k : Nat) : Nat :=
  (seed + 73 * k) % byteModulus

/-- A small affine byte mixer. The odd multiplier is invertible modulo `256`. -/
def mixByte (x : Nat) : Nat :=
  (157 * x + 101) % byteModulus

/-- The emitted byte at index `k` for a given seed. -/
def provableByte (seed k : Nat) : Nat :=
  mixByte (weylByte seed k)

theorem weylByte_lt (seed k : Nat) : weylByte seed k < byteModulus := by
  unfold weylByte byteModulus
  exact Nat.mod_lt _ (by decide)

theorem mixByte_lt (x : Nat) : mixByte x < byteModulus := by
  unfold mixByte byteModulus
  exact Nat.mod_lt _ (by decide)

/-- Every emitted value is a byte. -/
theorem provableByte_lt (seed k : Nat) : provableByte seed k < byteModulus :=
  mixByte_lt (weylByte seed k)

/-- One full period from a seed. -/
def byteCycle (seed : Nat) : List Nat :=
  (List.range byteModulus).map (provableByte seed)

/--
Dimension-scoped boundary byte. This mirrors the Lacey-cipher shape:
each helix dimension gets an independent-looking stream derived from
the capability/seed plus the dimension index.
-/
def laceyBoundaryByte (seed dim k : Nat) : Nat :=
  provableByte (seed + dim * 251) k

/-- One full dimension-scoped byte boundary cycle. -/
def laceyBoundaryCycle (seed dim : Nat) : List Nat :=
  (List.range byteModulus).map (laceyBoundaryByte seed dim)

/-- A concrete stream we can inspect: seed `42`, one full byte period. -/
def seed42Cycle : List Nat := byteCycle 42

/-- First 32 emitted bytes for seed `42`. These are actual generated bytes. -/
def seed42First32 : List Nat :=
  (List.range 32).map (provableByte 42)

theorem seed42First32_value :
    seed42First32 =
      [ 39, 236, 177, 118, 59, 0, 197, 138
      , 79, 20, 217, 158, 99, 40, 237, 178
      , 119, 60, 1, 198, 139, 80, 21, 218
      , 159, 100, 41, 238, 179, 120, 61, 2
      ] := by native_decide

theorem seed42Cycle_length : seed42Cycle.length = byteModulus := by
  native_decide

/-- The 256-byte seed-42 cycle has no duplicate outputs. -/
theorem seed42Cycle_nodup : seed42Cycle.Nodup := by
  native_decide

/-- The 256-byte seed-42 cycle covers every byte value. -/
theorem seed42Cycle_covers_all_bytes :
    (List.range byteModulus).all (fun b => seed42Cycle.contains b) = true := by
  native_decide

/--
The certified boundary: for seed `42`, this generator produces 256 byte values,
each byte appears, and no byte appears twice before the cycle repeats.
-/
theorem seed42Cycle_is_full_byte_permutation :
    seed42Cycle.length = byteModulus ∧
      seed42Cycle.Nodup ∧
        (List.range byteModulus).all (fun b => seed42Cycle.contains b) = true :=
  ⟨seed42Cycle_length, seed42Cycle_nodup, seed42Cycle_covers_all_bytes⟩

/-! ## Lacey edge-boundary witness -/

def laceySeed42DnaCycle : List Nat :=
  laceyBoundaryCycle 42 laceyDnaDimension

theorem lacey_dimension_count_value : laceyDimensionCount = 54 := rfl

theorem lacey_dna_dimension_inside_helix :
    laceyDnaDimension < laceyDimensionCount := by decide

theorem laceySeed42DnaCycle_length :
    laceySeed42DnaCycle.length = byteModulus := by native_decide

/-- The seed-42 DNA-dimension Lacey boundary cycle has no duplicate bytes. -/
theorem laceySeed42DnaCycle_nodup : laceySeed42DnaCycle.Nodup := by
  native_decide

/-- The seed-42 DNA-dimension Lacey boundary cycle covers every byte value. -/
theorem laceySeed42DnaCycle_covers_all_bytes :
    (List.range byteModulus).all (fun b => laceySeed42DnaCycle.contains b) = true := by
  native_decide

/--
The finite Lacey-style edge boundary for the DNA dimension: the stream is
dimension-scoped, emits structured bytes, and covers the entire byte boundary
exactly once before repeating.
-/
theorem lacey_seed42_dna_boundary_is_full_byte_permutation :
    laceyDnaDimension < laceyDimensionCount ∧
      laceySeed42DnaCycle.length = byteModulus ∧
        laceySeed42DnaCycle.Nodup ∧
          (List.range byteModulus).all (fun b => laceySeed42DnaCycle.contains b) = true :=
  ⟨lacey_dna_dimension_inside_helix,
    laceySeed42DnaCycle_length,
    laceySeed42DnaCycle_nodup,
    laceySeed42DnaCycle_covers_all_bytes⟩

/-! ## FOIL ambient-entropy projection boundary -/

/--
Layer C supplies this certificate from FOIL/runtime observation: bytes were
actually observed, and the runtime computed the witness signal from them.
Lean treats those fields as the external boundary, not as a theorem that
the universe generated perfect randomness.
-/
structure FoilAmbientEntropyCertificate where
  observedBytes : Nat
  witnessSignal : Nat
  activationThreshold : Nat

/--
The honest ambient-randomness theorem: given a FOIL runtime certificate whose
witness clears the threshold, the internal projection is exactly the 10-bit
Aeon/Flow frame. Randomness enters at the certificate boundary; the Lean claim
is the deterministic projection from that boundary.
-/
theorem foil_ambient_entropy_certificate_projects_to_ten_bit_frame
    (certificate : FoilAmbientEntropyCertificate)
    (hSignal : certificate.activationThreshold ≤ certificate.witnessSignal) :
    Gnosis.FoilZeroDragCompatibility.activeChannels
        { potentialChannels :=
            Gnosis.FoilZeroDragCompatibility.rawObservationPotentialChannels
              certificate.observedBytes,
          witnessSignal := certificate.witnessSignal,
          activationThreshold := certificate.activationThreshold } =
      10 := by
  rw [Gnosis.FoilZeroDragCompatibility.raw_observation_active_channels_when_signal_clears
    certificate.observedBytes certificate.witnessSignal certificate.activationThreshold hSignal]
  rfl

/--
The same FOIL certificate also reaches the existing zero-drag projection theorem.
This is the stronger bridge: ambient entropy is admitted by FOIL, then the
already-proved compatibility layer discharges the residual.
-/
theorem foil_ambient_entropy_certificate_zero_drag
    (certificate : FoilAmbientEntropyCertificate)
    (hSignal : certificate.activationThreshold ≤ certificate.witnessSignal) :
    Gnosis.FoilZeroDragCompatibility.foilDrag
      Gnosis.FoilZeroDragCompatibility.foilProjectedFrameWidth
      (Gnosis.FoilZeroDragCompatibility.activeChannels
        { potentialChannels :=
            Gnosis.FoilZeroDragCompatibility.rawObservationPotentialChannels
              certificate.observedBytes,
          witnessSignal := certificate.witnessSignal,
          activationThreshold := certificate.activationThreshold }) = 0 :=
  Gnosis.FoilZeroDragCompatibility.raw_observation_signal_clear_implies_projection_zero_drag
    certificate.observedBytes certificate.witnessSignal certificate.activationThreshold hSignal

end ProvableRandomness
end Gnosis
