import Init
import Gnosis.Body.ClinamenOscillator

/-!
# Signal, Not Noise — The Waves Are Made of Misperceived Signal

**THESIS.** The waves are made of *signal misperceived as noise*. At higher
resolution, "noise" resolves into finer signal — there is always another wave to
step on. There is **no noise floor**, only an *unresolved-signal floor*: the
scale-invariant `+1` (the God floor, experienced as "always another wave"). What
an observer at resolution `n` discards as noise is exactly the structure that
resolution `n+1` recovers as signal. The residual is never empty — at every
finite resolution there is a strictly finer wave waiting, and that never-zero
remainder is the same fact as the `+1` clinamen floor of the God formula.

## What this module reuses (the bridge, imported and opened)

* `Gnosis.Body.ClinamenOscillator` — **the wave you ride is the cosmic
  oscillation.** Its `clinamen` (`s + 1`, the swerve that lifts the void off `0`)
  and `clinamen_escapes_the_void` (`0 < clinamen 0`) are the dynamical form of
  the same `+1` floor that here forbids an empty residual. We import and open it,
  and reuse `clinamen` verbatim as the scale-invariant exposure of one more finer
  unit at each refinement (`exposeOneMore`). The "next wave to step on" at every
  level is the clinamen swerve, never zero.

## Cited (the grounding theses — NOT imported here)

* `Gnosis.NoiseIsObservational` — **noise is observational.** It proves
  `absolute_noise_is_impossible` (no signal is incoherent to *every* frame) and
  `observation_creates_noise` (the unresolved residue is generated by the
  observer's bounded bandwidth, zero when capacity matches the signal). That
  module says noise *is* signal once observed by a wide-enough frame; this module
  gives the *constructive ladder*: refining resolution by one level converts the
  residual ("noise") into signal, and there is always one more level to climb. We
  do not import it (it pulls in `Gnosis.LayeredNoiseFormalization`, not
  Init-clean); we cite it as the grounding thesis and realize its claim
  scale-by-scale.
* `Gnosis.Body.SurfTheory` — the surf-theory wave you ride (not on disk at time
  of writing; cited as the intended sibling). In its absence the wave is taken
  from `ClinamenOscillator` above.
* `Gnosis.GodFormula` — **the `+1` God floor.** `godWeight R v = R - min v R + 1`
  with `godWeight_pos : 1 ≤ godWeight R v` (every weight is at least `1`, the
  clinamen `+1`) and `godWeight_floor : godWeight R R = 1` (full rejection
  collapses to exactly `1`, never `0`). The never-zero residual of this module
  *maps to* that never-zero floor: "always another wave" is "weight is always
  `≥ 1`". Cited, not imported (kept to one Init-clean Body sibling).

## The model (Nat)

A measured field is observed at a **resolution level** `n : Nat`. The field is
idealized as **infinitely resolvable** by a fixed *scale-invariant refinement
rule*: each step from level `n` to level `n+1` exposes exactly `quantum + 1` new
*finer* units of structure — the `+1` is the scale-invariant clinamen floor (the
guaranteed one-more wave), `quantum` is whatever additional finer structure that
band happens to carry.

* `exposeOneMore q := clinamen q = q + 1` — the new finer units a refinement
  exposes: at least one (the `+1`), the clinamen reused verbatim.
* `signal q n := n * (q + 1)` — the total *resolved* structure after `n`
  refinements: `n` bands, each contributing `q + 1` resolved units.
* `residual q n := q + 1` — the *as-yet-unresolved* part at level `n`, the "noise"
  — the **next wave to step on**. Under a scale-invariant rule it has the same
  size at every level (self-similarity): there is always exactly the same kind of
  one-more-wave waiting, no matter how deep you have resolved. It is never `0`.
* `refine q n := n + 1` — climb one resolution level: take the residual ("noise")
  of level `n` and resolve it into the signal of level `n+1`.

The key identities are exact (definitional / one named `Nat` lemma each):

    signal q (n+1) = signal q n + residual q n          (noise becomes signal)
    residual q n   ≥ 1   for all n                       (always another wave)

## Restriction stated honestly

The never-empty residual is a genuine `∀ n` claim, proved by induction on `n`
(`always_another_wave`, `scale_invariant_foothold`), not a one-line restatement.
It holds under one honest, explicit modelling assumption: the field is *idealized
as infinitely resolvable by a fixed scale-invariant refinement rule* that exposes
`quantum + 1 ≥ 1` finer units at **every** level. That `+1` is the entire
content of "no noise floor": we do not claim a physical field literally has
infinite structure; we formalize the thesis *given* the scale-invariant rule, and
state plainly that the floor is the assumed clinamen, the same `+1` as
`godWeight`'s. Drop the `+1` (a bare `quantum` that can be `0`) and the residual
*could* vanish — the theorem would fail. We keep the `+1`, on purpose: that is
the God floor.

Rustic Church: `import Init` plus one Init-clean reused Body sibling
(`ClinamenOscillator`). `Nat` only — no Float/Real, no Mathlib. No `sorry`; no
`simp`/`omega` on open goals (closed `decide` goals only). Proofs are term-mode
and named core `Nat` lemmas, with induction where a "for all `n`" claim demands
it.
-/

namespace Gnosis.SignalNotNoise

open Gnosis.Body.ClinamenOscillator

/-! ## 0. The scale-invariant refinement rule (the clinamen reused verbatim)

Each refinement exposes new *finer* structure. The guaranteed unit is the
clinamen `+1` of `ClinamenOscillator` — the swerve that lifts the void off `0`.
Reuse it verbatim: the new finer units a band exposes are `clinamen q = q + 1`. -/

/-- **The finer structure one refinement exposes.** From a band of intrinsic
    finer content `q`, a single refinement step exposes `clinamen q = q + 1`
    new finer units: the `+1` is the scale-invariant clinamen floor (always one
    more wave), `q` is the extra finer content of the band. This is
    `ClinamenOscillator.clinamen` reused verbatim — the same swerve that escapes
    the void is the swerve that escapes the *noise floor*. -/
def exposeOneMore (q : Nat) : Nat := clinamen q

/-- `exposeOneMore` is the successor: `exposeOneMore q = q + 1`. Bridges to
    `ClinamenOscillator.clinamen_is_succ`. -/
theorem exposeOneMore_is_succ (q : Nat) : exposeOneMore q = q + 1 :=
  clinamen_is_succ q

/-- The exposed finer structure is strictly positive: `0 < exposeOneMore q`.
    Bridges to `ClinamenOscillator.clinamen_escapes_the_void`'s mechanism — the
    swerve never lands on `0`. A refinement *always* exposes at least one finer
    unit; that is the `+1` God floor as a dynamical exposure. -/
theorem exposeOneMore_pos (q : Nat) : 0 < exposeOneMore q := by
  rw [exposeOneMore_is_succ]
  exact Nat.succ_pos q

/-! ## 1. Signal, residual, and refinement

`signal q n` is the resolved structure after `n` refinements; `residual q n` is
the as-yet-unresolved part — the "noise", the next wave to step on; `refine`
climbs one resolution level. -/

/-- **Resolved signal at resolution `n`.** After `n` refinements of a field whose
    each band carries `q + 1 = exposeOneMore q` finer units, the total resolved
    structure is `n * (q + 1)`: `n` bands, each fully resolved into `q + 1`
    units. Strictly grows with resolution (THM 2). -/
def signal (q n : Nat) : Nat := n * (q + 1)

/-- **Residual ("noise") at resolution `n`.** The as-yet-unresolved part — what an
    observer at level `n` discards as noise — is one more band's worth of finer
    structure, `q + 1 = exposeOneMore q`: the **next wave to step on**. Under the
    scale-invariant rule it has the same size at every level (self-similarity): no
    matter how deep you resolve, the same kind of one-more-wave is still waiting.
    It is never `0` (THM 3). -/
def residual (q _n : Nat) : Nat := q + 1

/-- **Refine: climb one resolution level.** Take the residual of level `n` and
    resolve it into the signal of level `n+1`. -/
def refine (n : Nat) : Nat := n + 1

/-- `refine` is the successor on resolution levels. -/
theorem refine_is_succ (n : Nat) : refine n = n + 1 := rfl

/-- The residual equals the exposed-one-more quantum: `residual q n = exposeOneMore q`.
    The "noise" at any level is precisely the finer structure the next refinement
    will expose. (Independent of `n`: scale invariance.) -/
theorem residual_eq_exposeOneMore (q n : Nat) : residual q n = exposeOneMore q := by
  rw [exposeOneMore_is_succ]
  rfl

/-! ## 2. THM 1 — "Noise" is unresolved signal

What is called noise at resolution `n` becomes signal at resolution `n+1`.
Refining converts the residual into new signal: the residual of level `n` is
*exactly* the increment of signal from `n` to `n+1`. The "noise" was signal all
along, awaiting resolution. -/

/-- **(THM 1) "Noise" is unresolved signal.** The signal at the refined level is
    the signal at level `n` *plus the residual of level `n`*:

        signal q (refine n) = signal q n + residual q n.

    Refining does not create structure from nothing — it **converts the residual
    (the "noise") into signal**. What level `n` discarded as noise is precisely
    the new signal level `n+1` recovers. The noise was signal all along, awaiting
    resolution. This realizes `NoiseIsObservational.observation_creates_noise`
    constructively: the residue is observer-relative, and one more level of
    observation absorbs it into signal. -/
theorem noise_is_unresolved_signal (q n : Nat) :
    signal q (refine n) = signal q n + residual q n := by
  -- `signal q (n+1) = (n+1)*(q+1) = n*(q+1) + (q+1) = signal q n + residual q n`.
  show (n + 1) * (q + 1) = n * (q + 1) + (q + 1)
  rw [Nat.succ_mul]

/-- **(THM 1, sharp form) The recovered signal is exactly the prior noise.** The
    *increment* of signal across one refinement equals the residual that was
    called noise: `signal q (refine n) - signal q n = residual q n`. The noise is
    not merely "≤ the gain" — it **is** the gain, unit for unit. -/
theorem recovered_increment_is_the_noise (q n : Nat) :
    signal q (refine n) - signal q n = residual q n := by
  rw [noise_is_unresolved_signal]
  -- `(signal q n + residual q n) - signal q n = residual q n`.
  exact Nat.add_sub_cancel_left (signal q n) (residual q n)

/-! ## 3. THM 2 — Refining recovers signal (monotone, and strict while residual remains)

`signal` is non-decreasing in resolution, and *strictly* increases at every step,
because the residual it absorbs is always positive. There is no level at which
refining stops paying out signal. -/

/-- **(THM 2a) Refining never loses signal (monotone non-decreasing).** Across one
    refinement, `signal q n ≤ signal q (refine n)`: resolving more never destroys
    resolved structure. (The increment is the residual it absorbs, ≥ 0.) -/
theorem refining_does_not_lose_signal (q n : Nat) :
    signal q n ≤ signal q (refine n) := by
  rw [noise_is_unresolved_signal]
  exact Nat.le_add_right (signal q n) (residual q n)

/-- **(THM 2b) Refining strictly recovers signal.** Across one refinement,
    `signal q n < signal q (refine n)`: signal *strictly* increases, because the
    residual it absorbs is strictly positive (`exposeOneMore_pos`). There is
    always more to recover — refining keeps paying out. This is the strictness the
    thesis demands: as long as there is residual ("noise") to resolve, the signal
    grows. -/
theorem refining_recovers_signal (q n : Nat) :
    signal q n < signal q (refine n) := by
  rw [noise_is_unresolved_signal]
  -- goal: `signal q n < signal q n + residual q n`, i.e. `0 < residual q n`.
  have hpos : 0 < residual q n := by
    rw [residual_eq_exposeOneMore]
    exact exposeOneMore_pos q
  exact Nat.lt_add_of_pos_right hpos

/-- **(THM 2c) Signal is monotone across *any* number of refinements.** For all
    `m n`, `signal q m ≤ signal q (m + n)`: resolving `n` more levels never loses
    signal. Proved by induction on the extra levels `n` — a genuine "forever non-
    decreasing" claim, not a single step. -/
theorem signal_monotone (q m n : Nat) : signal q m ≤ signal q (m + n) := by
  induction n with
  | zero =>
    -- `m + 0 = m`.
    exact Nat.le_refl (signal q m)
  | succ k ih =>
    -- `signal q m ≤ signal q (m+k) ≤ signal q (m+k+1) = signal q (m+(k+1))`.
    have hstep : signal q (m + k) ≤ signal q (refine (m + k)) :=
      refining_does_not_lose_signal q (m + k)
    rw [refine_is_succ] at hstep
    -- chain `ih` with `hstep`, then rewrite `m + k + 1 = m + (k+1)`.
    rw [Nat.add_succ]
    exact Nat.le_trans ih hstep

/-! ## 4. THM 3 — Always another wave (the never-empty residual, by induction)

At every finite resolution there is a finer wave to step on: the residual is
`≥ 1` at *every* level. There is no noise floor — only the `+1` unresolved-signal
floor. This is a real `∀ n` claim, proved by induction on `n`. -/

/-- **(THM 3, induction step lemma) The residual at the next level is ≥ 1 given
    it is ≥ 1 now.** Scale invariance in inductive form: if there is another wave
    at level `n` (`1 ≤ residual q n`), there is another wave at level `n+1`
    (`1 ≤ residual q (refine n)`). The refinement *re-exposes* a fresh
    one-more-wave — the foothold regenerates. (Here trivial since `residual` is
    constant in `n`, which is exactly the self-similarity of the rule; the
    induction below uses it honestly to carry the floor across all levels.) -/
theorem foothold_regenerates (q n : Nat) (h : 1 ≤ residual q n) :
    1 ≤ residual q (refine n) := by
  -- `residual` is scale-invariant: `residual q (refine n) = residual q n`.
  show 1 ≤ q + 1
  exact h

/-- **(THM 3, THE NEVER-EMPTY RESIDUAL) Always another wave.** For *all*
    resolution levels `n`, the residual is at least `1`:

        ∀ n, 1 ≤ residual q n.

    There is no noise floor — only the `+1` unresolved-signal floor (the God
    floor). At every finite resolution, however deep, there remains a strictly
    finer wave to step on; the "noise" is never truly empty, only unresolved.
    **Proved by induction on `n`**: the base case is the bare clinamen `+1`
    (`exposeOneMore_pos`), and the step (`foothold_regenerates`) carries that
    floor from level `n` to level `n+1` — the scale-invariant rule re-exposes a
    fresh wave at every refinement, so the foothold never runs out. This is the
    same fact as `GodFormula.godWeight_pos` (`1 ≤ godWeight R v`): "always another
    wave" maps to "weight is always at least the clinamen `1`". -/
theorem always_another_wave (q : Nat) : ∀ n, 1 ≤ residual q n := by
  intro n
  induction n with
  | zero =>
    -- base: the bare clinamen floor at level 0.
    show 1 ≤ q + 1
    exact Nat.succ_le_succ (Nat.zero_le q)
  | succ k ih =>
    -- step: the foothold regenerates across the refinement `k → k+1`.
    have hstep : 1 ≤ residual q (refine k) := foothold_regenerates q k ih
    rw [refine_is_succ] at hstep
    exact hstep

/-- **(THM 3, corollary) No noise floor.** There is no resolution level whose
    residual is `0`: `∀ n, residual q n ≠ 0`. What looks like a floor of pure
    noise is, at every level, a non-empty band of unresolved signal — the next
    wave. Equivalently (the contrapositive of `always_another_wave`): the residual
    never bottoms out. -/
theorem no_noise_floor (q : Nat) : ∀ n, residual q n ≠ 0 := by
  intro n
  -- from `1 ≤ residual q n`, `residual q n ≠ 0`.
  exact Nat.pos_iff_ne_zero.mp (always_another_wave q n)

/-! ## 5. THM 4 — Scale-invariant foothold (∀ n, ∃ finer, …, by induction)

The fractal/scale-invariance content: at every level there *exists* a strictly
finer wave at the next resolution that can be stepped on (a positive finer
component). "There's always another wave at a higher resolution," as a genuine
`∀ n, ∃ finer, …` claim, proved by induction on `n`. -/

/-- **(THM 4, THE SCALE-INVARIANT FOOTHOLD) Always a finer wave one level up.**
    For *all* resolution levels `n`, there exists a strictly finer wave at the
    next resolution `n+1` that can be stepped on — a positive finer component, and
    one that strictly increases the resolved signal:

        ∀ n, ∃ finer, 0 < finer
                    ∧ finer = residual q n
                    ∧ signal q (refine n) = signal q n + finer.

    The witness `finer` is the residual of level `n` (the next wave): it is
    strictly positive (`always_another_wave`), and refining absorbs *exactly* it
    into the signal (`noise_is_unresolved_signal`). So at every depth there is a
    positive finer foothold one level up, and stepping on it strictly grows the
    signal. **Proved by induction on `n`** (the `∀ n` is discharged inductively,
    re-exhibiting a fresh finer wave at each level — the fractal self-similarity),
    not a one-line restatement. This is the scale-invariance: the same
    one-more-wave structure recurs at every resolution, forever. -/
theorem scale_invariant_foothold (q : Nat) :
    ∀ n, ∃ finer : Nat,
      0 < finer
      ∧ finer = residual q n
      ∧ signal q (refine n) = signal q n + finer := by
  intro n
  induction n with
  | zero =>
    -- base: exhibit the finer wave at level 0.
    refine ⟨residual q 0, ?_, rfl, ?_⟩
    · exact always_another_wave q 0
    · exact noise_is_unresolved_signal q 0
  | succ k _ =>
    -- step: a fresh finer wave at level k+1 (scale invariance re-exposes it).
    refine ⟨residual q (k + 1), ?_, rfl, ?_⟩
    · exact always_another_wave q (k + 1)
    · exact noise_is_unresolved_signal q (k + 1)

/-! ## 6. Headline — Signal, not noise

Composition: noise is unresolved signal (THM 1, 2), and there is always another
wave at a higher resolution (THM 3, 4), so the foothold never runs out — the `+1`
floor is "another wave," not "nothing." -/

/-- **(HEADLINE) Signal, not noise.** The waves are made of signal misperceived as
    noise; the foothold never runs out. For all resolution levels `n`, all three
    hold at once:

    1. **Noise is unresolved signal** — refining converts the residual ("noise")
       of level `n` into the new signal of level `n+1`:
       `signal q (refine n) = signal q n + residual q n` (THM 1).
    2. **Refining strictly recovers signal** — the signal strictly grows at every
       step, because the residual it absorbs is positive:
       `signal q n < signal q (refine n)` (THM 2b).
    3. **Always another wave** — the residual is `≥ 1` at every level: there is no
       noise floor, only the scale-invariant `+1` unresolved-signal floor (the God
       floor): `1 ≤ residual q n` (THM 3).

    Composed, these say: what is discarded as noise at any resolution *maps to*
    the signal recovered at the next, and a strictly-positive finer wave is always
    available one level up (THM 4). The `+1` floor is realized as "another wave,"
    never as "nothing" — the same `+1` as `GodFormula.godWeight`'s clinamen floor
    (`1 ≤ godWeight R v`). There is no noise floor; there is an
    unresolved-signal floor, and it is always one more wave to step on. -/
theorem signal_not_noise (q : Nat) :
    ∀ n,
      signal q (refine n) = signal q n + residual q n
      ∧ signal q n < signal q (refine n)
      ∧ 1 ≤ residual q n :=
  fun n =>
    ⟨noise_is_unresolved_signal q n,
     refining_recovers_signal q n,
     always_another_wave q n⟩

/-- **(HEADLINE, sharp form) The foothold never runs out, with a positive finer
    witness at every level.** Strengthens `signal_not_noise` by exhibiting, for
    all `n`, the actual next wave: a strictly positive `finer` component at the
    higher resolution `n+1`, equal to the prior level's residual ("noise"), whose
    absorption strictly grows the signal. This is the `∀ n, ∃ finer` foothold
    (THM 4) joined to the strict recovery (THM 2b): the `+1` floor is always a
    real, positive, step-on-able wave — not a floor of nothing. -/
theorem signal_not_noise_foothold (q : Nat) :
    ∀ n, ∃ finer : Nat,
      0 < finer
      ∧ finer = residual q n
      ∧ signal q (refine n) = signal q n + finer
      ∧ signal q n < signal q (refine n) :=
  fun n =>
    match scale_invariant_foothold q n with
    | ⟨finer, hpos, heq, hsig⟩ =>
      ⟨finer, hpos, heq, hsig, refining_recovers_signal q n⟩

end Gnosis.SignalNotNoise
