/-
  SpinorCover2O.lean
  ==================

  The SU(2) → SO(3) double cover COMPUTED on the binary OCTAHEDRAL group 2O — the 48 unit
  octahedral quaternions — by EXACT ℤ[√2] conjugation arithmetic. This completes the
  sampled conjugation-cover ladder:

    Q8  (8,  trivial coords)   — SpinorCoverSampled §1
    2T  (24, ℤ scaled ×2)      — SpinorCoverSampled §2  (per-pair `decide`)
    2I  (120, ℤ[φ] scaled ×2)  — SpinorCover600Cell      (universal polynomial hom)
    2O  (48, ℤ[√2] scaled ×2)  — THIS MODULE             (universal polynomial hom)

  With all four landed, every nontrivial binary polyhedral spin cover is an exact COMPUTED
  conjugation cover with kernel {±1}.

  THE ENGINE IS REUSED VERBATIM. We import `Gnosis.SpinorCover600Cell` and reuse the
  reflective polynomial normalizer `GR.CRing` / `reify` / `denote_eq_of_reify_eq` and the
  Int-reflection helper `IntInst.Ki` exactly as the 2I module built them. The cover map
  `R(q) = q·v·q⁻¹` (matrix form, scaled by |q|²) satisfies `R(p·q) = R(p)·R(q)` as a
  POLYNOMIAL IDENTITY in the components of `p` and `q` — true for ALL ℤ[√2]-quaternions,
  proved ONCE symbolically (NOT by enumerating the 48² = 2304 ordered pairs). Only the
  coefficient ring changes from ℤ[φ] to ℤ[√2]; the nine entry polynomial normal forms are
  identical `PExpr` shapes, re-checked by kernel `decide` over the new coefficient ring.

  2O reduces to a SMALL number of finite checks:

    (a) UNIVERSAL HOMOMORPHISM (`hom_bridge2`): `R(p·q) = R(p)·R(q)` for every pair of
        ℤ[√2]-quaternions — nine polynomial-identity `decide`s in 8 ℤ[√2]-variables, NOT
        2304 sampled pairs.
    (b) CLOSURE TO 48 (`octa_card`, `octa_gen_closed`): the 48 octahedral units are
        generated by orbit-BFS from a 2T generator (the half-integer `(1+i+j+k)/2`) plus
        one `(e₀+e₁)/√2` unit; we verify the explicit 48-element list and that it is closed
        under multiplication by each GENERATOR. With the universal homomorphism, generator
        closure pins the group.
    (c) KERNEL = {±1} (`octa_kernel_is_pm_one`): exactly the two central units `±1` map to
        the identity rotation. Image = 24 distinct rotation matrices
        (`octa_image_card_is_24`) = the octahedral rotation group O ≅ S₄; cover index
        48 / 24 = 2.

  EXACT ℤ[√2] ARITHMETIC. An octahedral unit lives in ½·ℤ[√2]⁴: the 24 of 2T (8 Lipschitz
  `±eᵢ`, 16 `(±1±i±j±k)/2`) plus 24 of the form `(±eᵢ±eⱼ)/√2`. We store every quaternion
  SCALED BY 2 so the `/2` is integer; `(±eᵢ±eⱼ)/√2` scales to coordinates `±√2 = ⟨0,±1⟩ ∈
  ℤ[√2]`. All arithmetic is exact integer-pair arithmetic in ℤ[√2] (`√2·√2 = 2`), no reals.

  RELATIONSHIP TO THE ORDER-LEVEL SHADOW (precise, not identity). The 48 = 2·24 here is the
  COMPUTED conjugation lift of the order arithmetic in `Gnosis.OrientationE8Bridge`
  (`binary_is_2to1_spin_cover` for the octahedral case, `subgroupOrder .BinaryOcta = 48`):
  there `|2O| = 2·|O|` is tabulated; here the index 2 is COMPUTED from `R` (kernel {±1},
  image 24).

  HARD CONSTRAINTS (met). Init-only (`import Init` + cited Gnosis bridges, transitively via
  the 2I module). KERNEL `decide`/`rfl`/structural + the symbolic homomorphism identity
  ONLY — NO `native_decide`, no `sorry`, no `admit`, no new `axiom`, no `Classical.choice`,
  no `omega`. `set_option maxRecDepth` raised (the normalizer recurses deep). Gate ONLY on
  `lake build Gnosis.SpinorCover2O`. Does NOT edit other modules and does NOT register
  itself in `Gnosis.lean`. `#print axioms` for the headline theorems is at the bottom.
-/

import Init
import Gnosis.SpinorCover600Cell

-- The reflective polynomial normalizer recurses through degree-4 polynomials in 8
-- variables over ℤ[√2]; raise the reduction depth (same DEPTH knob the 2I module used).
set_option maxRecDepth 8000

set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false

-- ════════ ℤ[√2] as a commutative ring, ring axioms via Int reflection ════════
namespace ZSqrt2
open GR IntInst

structure Zs2 where
  a : Int
  b : Int
deriving DecidableEq, Repr
def zadd (p q : Zs2) : Zs2 := ⟨p.a+q.a, p.b+q.b⟩
def zneg (p : Zs2) : Zs2 := ⟨-p.a, -p.b⟩
-- (a+b√2)(c+d√2) = (ac + 2bd) + (ad+bc)√2
def zmul (p q : Zs2) : Zs2 := ⟨p.a*q.a + 2*(p.b*q.b), p.a*q.b + p.b*q.a⟩
def zzero : Zs2 := ⟨0,0⟩
def zone : Zs2 := ⟨1,0⟩
theorem zext {p q : Zs2} (ha : p.a = q.a) (hb : p.b = q.b) : p = q := by
  cases p; cases q; simp_all

-- symbolic Zs2 pair over the Int engine PExpr (reused VERBATIM from the ZPhi pattern;
-- only `szmul` changes — the ℤ[√2] product law replaces the ℤ[φ] product law)
abbrev IE := @PExpr Int
structure SZ where
  a : IE
  b : IE
def szD (env : Nat → Int) (s : SZ) : Zs2 := ⟨denote Ki env s.a, denote Ki env s.b⟩
def szadd (p q : SZ) : SZ := ⟨.add p.a q.a, .add p.b q.b⟩
-- (a+b√2)(c+d√2) = (ac + 2bd) + (ad+bc)√2
def szmul (p q : SZ) : SZ :=
  ⟨.add (.mul p.a q.a) (.mul (.cst (2:Int)) (.mul p.b q.b)), .add (.mul p.a q.b) (.mul p.b q.a)⟩
theorem szadd_D (env) (p q : SZ) : szD env (szadd p q) = zadd (szD env p) (szD env q) := by
  simp only [szD, szadd, zadd, denote, Ki]
theorem szmul_D (env) (p q : SZ) : szD env (szmul p q) = zmul (szD env p) (szD env q) := by
  simp only [szD, szmul, zmul, denote, Ki]
theorem szEq (s t : SZ) (ha : reify Ki s.a = reify Ki t.a) (hb : reify Ki s.b = reify Ki t.b) (env) :
    szD env s = szD env t := by
  apply zext
  · exact denote_eq_of_reify_eq Ki s.a t.a ha env
  · exact denote_eq_of_reify_eq Ki s.b t.b hb env
def sp : SZ := ⟨.var 0, .var 1⟩
def sq : SZ := ⟨.var 2, .var 3⟩
def sr : SZ := ⟨.var 4, .var 5⟩
def envPQR (p q r : Zs2) : Nat → Int := fun i => [p.a,p.b,q.a,q.b,r.a,r.b].getD i 0
theorem sp_D (p q r) : szD (envPQR p q r) sp = p := by simp [szD, sp, denote, envPQR, List.getD]
theorem sq_D (p q r) : szD (envPQR p q r) sq = q := by simp [szD, sq, denote, envPQR, List.getD]
theorem sr_D (p q r) : szD (envPQR p q r) sr = r := by simp [szD, sr, denote, envPQR, List.getD]

theorem zmul_assoc (p q r : Zs2) : zmul (zmul p q) r = zmul p (zmul q r) := by
  have h := szEq (szmul (szmul sp sq) sr) (szmul sp (szmul sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szmul_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_comm (p q : Zs2) : zmul p q = zmul q p := by
  have h := szEq (szmul sp sq) (szmul sq sp) (by decide) (by decide) (envPQR p q p)
  rw [szmul_D, szmul_D, sp_D, sq_D] at h; exact h
theorem zadd_comm (p q : Zs2) : zadd p q = zadd q p := by
  have h := szEq (szadd sp sq) (szadd sq sp) (by decide) (by decide) (envPQR p q p)
  rw [szadd_D, szadd_D, sp_D, sq_D] at h; exact h
theorem zadd_assoc (p q r : Zs2) : zadd (zadd p q) r = zadd p (zadd q r) := by
  have h := szEq (szadd (szadd sp sq) sr) (szadd sp (szadd sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szadd_D, szadd_D, szadd_D, szadd_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_add (p q r : Zs2) : zmul p (zadd q r) = zadd (zmul p q) (zmul p r) := by
  have h := szEq (szmul sp (szadd sq sr)) (szadd (szmul sp sq) (szmul sp sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szadd_D, szadd_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zadd_mul (p q r : Zs2) : zmul (zadd p q) r = zadd (zmul p r) (zmul q r) := by
  have h := szEq (szmul (szadd sp sq) sr) (szadd (szmul sp sr) (szmul sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szadd_D, szadd_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_left_comm (p q r : Zs2) : zmul p (zmul q r) = zmul q (zmul p r) := by
  rw [← zmul_assoc, zmul_comm p q, zmul_assoc]
theorem zadd_left_comm (p q r : Zs2) : zadd p (zadd q r) = zadd q (zadd p r) := by
  rw [← zadd_assoc, zadd_comm p q, zadd_assoc]
theorem zzero_add (p : Zs2) : zadd zzero p = p := by apply zext <;> simp [zadd, zzero, Int.zero_add]
theorem zadd_zero (p : Zs2) : zadd p zzero = p := by apply zext <;> simp [zadd, zzero, Int.add_zero]
theorem zzero_mul (p : Zs2) : zmul zzero p = zzero := by
  apply zext <;> simp [zmul, zzero, Int.zero_mul, Int.add_zero, Int.zero_add, Int.mul_zero]
theorem zmul_zero (p : Zs2) : zmul p zzero = zzero := by
  apply zext <;> simp [zmul, zzero, Int.mul_zero, Int.add_zero, Int.zero_add]
theorem zone_mul (p : Zs2) : zmul zone p = p := by
  apply zext <;> simp [zmul, zone, Int.one_mul, Int.zero_mul, Int.add_zero, Int.zero_add, Int.mul_zero]
theorem zmul_one (p : Zs2) : zmul p zone = p := by
  apply zext <;> simp [zmul, zone, Int.mul_one, Int.mul_zero, Int.add_zero, Int.zero_add]
theorem zneg_mul (p q : Zs2) : zmul (zneg p) q = zneg (zmul p q) := by
  apply zext <;> simp [zmul, zneg, Int.neg_mul, Int.neg_add, Int.mul_neg, Int.neg_add]
theorem zneg_add (p q : Zs2) : zneg (zadd p q) = zadd (zneg p) (zneg q) := by
  apply zext <;> simp [zadd, zneg, Int.neg_add]

def Kz2 : CRing Zs2 :=
  { add := zadd, mul := zmul, neg := zneg, zero := zzero, one := zone
  , add_comm := zadd_comm, add_assoc := zadd_assoc, add_left_comm := zadd_left_comm
  , zero_add := zzero_add, add_zero := zadd_zero
  , mul_comm := zmul_comm, mul_assoc := zmul_assoc, mul_left_comm := zmul_left_comm
  , add_mul := zadd_mul, mul_add := zmul_add
  , zero_mul := zzero_mul, mul_zero := zmul_zero, one_mul := zone_mul, mul_one := zmul_one
  , neg_mul := zneg_mul, neg_add := zneg_add }

theorem zsqrt2_sq : zmul ⟨0,1⟩ ⟨0,1⟩ = ⟨2,0⟩ := by decide

end ZSqrt2

-- ════════ The universal conjugation homomorphism over ℤ[√2] ════════
-- The nine entry-identity PExpr SHAPES are IDENTICAL to the 2I module's (only the
-- coefficient ring / `c2` constant changes). We re-state them over `Kz2` and re-check the
-- normal forms by kernel `decide`.
namespace Cover2
open GR ZSqrt2

abbrev PE := @PExpr Zs2
def vw : PE := .var 0
def vx : PE := .var 1
def vy : PE := .var 2
def vz : PE := .var 3
def vW : PE := .var 4
def vX : PE := .var 5
def vY : PE := .var 6
def vZ : PE := .var 7
def c2 : PE := .cst ⟨2,0⟩

def pqw : PE := .sub (.sub (.sub (.mul vw vW) (.mul vx vX)) (.mul vy vY)) (.mul vz vZ)
def pqx : PE := .add (.add (.mul vw vX) (.mul vx vW)) (.sub (.mul vy vZ) (.mul vz vY))
def pqy : PE := .add (.sub (.mul vw vY) (.mul vx vZ)) (.add (.mul vy vW) (.mul vz vX))
def pqz : PE := .add (.sub (.add (.mul vw vZ) (.mul vx vY)) (.mul vy vX)) (.mul vz vW)

def R00 (a b cc d : PE) : PE := .sub (.sub (.add (.mul a a) (.mul b b)) (.mul cc cc)) (.mul d d)
def R01 (a b cc d : PE) : PE := .mul c2 (.sub (.mul b cc) (.mul a d))
def R02 (a b cc d : PE) : PE := .mul c2 (.add (.mul b d) (.mul a cc))
def R10 (a b cc d : PE) : PE := .mul c2 (.add (.mul b cc) (.mul a d))
def R11 (a b cc d : PE) : PE := .sub (.add (.sub (.mul a a) (.mul b b)) (.mul cc cc)) (.mul d d)
def R12 (a b cc d : PE) : PE := .mul c2 (.sub (.mul cc d) (.mul a b))
def R20 (a b cc d : PE) : PE := .mul c2 (.sub (.mul b d) (.mul a cc))
def R21 (a b cc d : PE) : PE := .mul c2 (.add (.mul cc d) (.mul a b))
def R22 (a b cc d : PE) : PE := .sub (.sub (.add (.mul a a) (.mul d d)) (.mul b b)) (.mul cc cc)

def prodEntry (Ri0 Ri1 Ri2 : PE → PE → PE → PE → PE)
              (R0j R1j R2j : PE → PE → PE → PE → PE) : PE :=
  .add (.add (.mul (Ri0 vw vx vy vz) (R0j vW vX vY vZ))
             (.mul (Ri1 vw vx vy vz) (R1j vW vX vY vZ)))
       (.mul (Ri2 vw vx vy vz) (R2j vW vX vY vZ))

theorem e00 : reify Kz2 (R00 pqw pqx pqy pqz) = reify Kz2 (prodEntry R00 R01 R02 R00 R10 R20) := by decide
theorem e01 : reify Kz2 (R01 pqw pqx pqy pqz) = reify Kz2 (prodEntry R00 R01 R02 R01 R11 R21) := by decide
theorem e02 : reify Kz2 (R02 pqw pqx pqy pqz) = reify Kz2 (prodEntry R00 R01 R02 R02 R12 R22) := by decide
theorem e10 : reify Kz2 (R10 pqw pqx pqy pqz) = reify Kz2 (prodEntry R10 R11 R12 R00 R10 R20) := by decide
theorem e11 : reify Kz2 (R11 pqw pqx pqy pqz) = reify Kz2 (prodEntry R10 R11 R12 R01 R11 R21) := by decide
theorem e12 : reify Kz2 (R12 pqw pqx pqy pqz) = reify Kz2 (prodEntry R10 R11 R12 R02 R12 R22) := by decide
theorem e20 : reify Kz2 (R20 pqw pqx pqy pqz) = reify Kz2 (prodEntry R20 R21 R22 R00 R10 R20) := by decide
theorem e21 : reify Kz2 (R21 pqw pqx pqy pqz) = reify Kz2 (prodEntry R20 R21 R22 R01 R11 R21) := by decide
theorem e22 : reify Kz2 (R22 pqw pqx pqy pqz) = reify Kz2 (prodEntry R20 R21 R22 R02 R12 R22) := by decide

end Cover2

-- ════════ Concrete ℤ[√2]-quaternions, conjugation matrix, universal hom ════════
namespace Cover2
open GR ZSqrt2

structure QZ where
  w : Zs2
  x : Zs2
  y : Zs2
  z : Zs2
deriving DecidableEq, Repr

def zsubZ (a b : Zs2) : Zs2 := zadd a (zneg b)
def z2 (p : Zs2) : Zs2 := zmul ⟨2,0⟩ p

def qmulZ (p q : QZ) : QZ :=
  { w := zsubZ (zsubZ (zsubZ (zmul p.w q.w) (zmul p.x q.x)) (zmul p.y q.y)) (zmul p.z q.z)
  , x := zadd (zadd (zmul p.w q.x) (zmul p.x q.w)) (zsubZ (zmul p.y q.z) (zmul p.z q.y))
  , y := zadd (zsubZ (zmul p.w q.y) (zmul p.x q.z)) (zadd (zmul p.y q.w) (zmul p.z q.x))
  , z := zadd (zsubZ (zadd (zmul p.w q.z) (zmul p.x q.y)) (zmul p.y q.x)) (zmul p.z q.w) }

structure M3 where
  a00 : Zs2
  a01 : Zs2
  a02 : Zs2
  a10 : Zs2
  a11 : Zs2
  a12 : Zs2
  a20 : Zs2
  a21 : Zs2
  a22 : Zs2
deriving DecidableEq, Repr

def RmatZ (q : QZ) : M3 :=
  let a := q.w; let b := q.x; let cc := q.y; let d := q.z
  { a00 := zsubZ (zsubZ (zadd (zmul a a) (zmul b b)) (zmul cc cc)) (zmul d d)
  , a01 := z2 (zsubZ (zmul b cc) (zmul a d))
  , a02 := z2 (zadd (zmul b d) (zmul a cc))
  , a10 := z2 (zadd (zmul b cc) (zmul a d))
  , a11 := zsubZ (zadd (zsubZ (zmul a a) (zmul b b)) (zmul cc cc)) (zmul d d)
  , a12 := z2 (zsubZ (zmul cc d) (zmul a b))
  , a20 := z2 (zsubZ (zmul b d) (zmul a cc))
  , a21 := z2 (zadd (zmul cc d) (zmul a b))
  , a22 := zsubZ (zsubZ (zadd (zmul a a) (zmul d d)) (zmul b b)) (zmul cc cc) }

def mmulZ (P Q : M3) : M3 :=
  { a00 := zadd (zadd (zmul P.a00 Q.a00) (zmul P.a01 Q.a10)) (zmul P.a02 Q.a20)
  , a01 := zadd (zadd (zmul P.a00 Q.a01) (zmul P.a01 Q.a11)) (zmul P.a02 Q.a21)
  , a02 := zadd (zadd (zmul P.a00 Q.a02) (zmul P.a01 Q.a12)) (zmul P.a02 Q.a22)
  , a10 := zadd (zadd (zmul P.a10 Q.a00) (zmul P.a11 Q.a10)) (zmul P.a12 Q.a20)
  , a11 := zadd (zadd (zmul P.a10 Q.a01) (zmul P.a11 Q.a11)) (zmul P.a12 Q.a21)
  , a12 := zadd (zadd (zmul P.a10 Q.a02) (zmul P.a11 Q.a12)) (zmul P.a12 Q.a22)
  , a20 := zadd (zadd (zmul P.a20 Q.a00) (zmul P.a21 Q.a10)) (zmul P.a22 Q.a20)
  , a21 := zadd (zadd (zmul P.a20 Q.a01) (zmul P.a21 Q.a11)) (zmul P.a22 Q.a21)
  , a22 := zadd (zadd (zmul P.a20 Q.a02) (zmul P.a21 Q.a12)) (zmul P.a22 Q.a22) }

def qenv (p q : QZ) : Nat → Zs2 :=
  fun i => [p.w,p.x,p.y,p.z,q.w,q.x,q.y,q.z].getD i zzero

/-- **UNIVERSAL HOMOMORPHISM over ℤ[√2].** `RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q)`
    for EVERY pair of ℤ[√2]-quaternions — the nine entry identities reused verbatim (same
    `PExpr` shapes as 2I, re-normalized over `Kz2`). NOT 2304 sampled pairs. -/
theorem hom_bridge2 (p q : QZ) :
    RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q) := by
  have E00 := denote_eq_of_reify_eq Kz2 _ _ e00 (qenv p q)
  have E01 := denote_eq_of_reify_eq Kz2 _ _ e01 (qenv p q)
  have E02 := denote_eq_of_reify_eq Kz2 _ _ e02 (qenv p q)
  have E10 := denote_eq_of_reify_eq Kz2 _ _ e10 (qenv p q)
  have E11 := denote_eq_of_reify_eq Kz2 _ _ e11 (qenv p q)
  have E12 := denote_eq_of_reify_eq Kz2 _ _ e12 (qenv p q)
  have E20 := denote_eq_of_reify_eq Kz2 _ _ e20 (qenv p q)
  have E21 := denote_eq_of_reify_eq Kz2 _ _ e21 (qenv p q)
  have E22 := denote_eq_of_reify_eq Kz2 _ _ e22 (qenv p q)
  cases p; cases q
  simp only [RmatZ, mmulZ, qmulZ, zsubZ, z2, qenv, List.getD,
             denote, Kz2, R00, R01, R02, R10, R11, R12, R20, R21, R22,
             prodEntry, pqw, pqx, pqy, pqz, vw, vx, vy, vz, vW, vX, vY, vZ, c2] at *
  refine M3.mk.injEq .. ▸ ?_
  refine ⟨E00, E01, E02, E10, E11, E12, E20, E21, E22⟩

end Cover2

-- ============ The 48 octahedral units (2O), scaled ×2, in ℤ[√2] ============
namespace Cover2
open GR ZSqrt2

def zhalf (p : Zs2) : Zs2 := ⟨p.a/2, p.b/2⟩
def qmulS (p q : QZ) : QZ :=
  let r := qmulZ p q
  ⟨zhalf r.w, zhalf r.x, zhalf r.y, zhalf r.z⟩
def qnegZ (q : QZ) : QZ := ⟨zneg q.w, zneg q.x, zneg q.y, zneg q.z⟩

-- Coordinate shorthands (over ℤ[√2], scaled ×2):
--   integer n   = ⟨n,0⟩      (rational part)
--   ±√2         = ⟨0,±1⟩     (the (±eᵢ±eⱼ)/√2 units, scaled ×2)
-- The 8 Lipschitz units: one slot ⟨±2,0⟩, rest ⟨0,0⟩.
-- The 16 half-integer (±1±i±j±k)/2 ×2: all slots ⟨±1,0⟩.
-- The 24 face units (±eᵢ±eⱼ)/√2 ×2: two slots ⟨0,±1⟩ (=±√2), two slots ⟨0,0⟩.
def octa : List QZ :=
  [ -- 8 Lipschitz (= ±eᵢ, scaled ×2)
    ⟨⟨2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨2,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨2,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨-2,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨2,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨-2,0⟩⟩,
    -- 16 half-integer (±1±i±j±k)/2, scaled ×2 (all coords ⟨±1,0⟩)
    ⟨⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
    ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
    -- 24 face units (±eᵢ±eⱼ)/√2, scaled ×2 = (±√2)eᵢ + (±√2)eⱼ, the two slots ⟨0,±1⟩
    -- pair (w,x)
    ⟨⟨0,1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
    -- pair (w,y)
    ⟨⟨0,1⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,1⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
    -- pair (w,z)
    ⟨⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
    ⟨⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
    ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
    -- pair (x,y)
    ⟨⟨0,0⟩, ⟨0,1⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,1⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
    ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
    -- pair (x,z)
    ⟨⟨0,0⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
    -- pair (y,z)
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨0,1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨0,-1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨0,1⟩⟩,
    ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨0,-1⟩⟩
  ]

-- Generators: a 2T half-integer unit (1+i+j+k)/2 (×2 = ⟨1,1,1,1⟩) and one face unit
-- (e₀+e₁)/√2 (×2 = ⟨√2,√2,0,0⟩ = ⟨⟨0,1⟩,⟨0,1⟩,0,0⟩).
def gT : QZ := ⟨⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩
def gF : QZ := ⟨⟨0,1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩⟩
def gens2 : List QZ := [gT, gF]
def qOne  : QZ := ⟨⟨2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩
def qNeg1 : QZ := ⟨⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩

theorem octa_card : octa.length = 48 := by decide

/-- 2O is closed under (scaled) multiplication by each GENERATOR. With the universal
    homomorphism, generator closure pins the group (240 → here 96 checks, not 2304). -/
theorem octa_gen_closed :
    (octa.all (fun a => gens2.all (fun g => octa.contains (qmulS a g)))) = true := by decide

end Cover2

-- ════════ Kernel = {±1}, image = octahedral O ≅ S₄ (24), cover index 2 ════════
namespace Cover2
open GR ZSqrt2

def RIdent : M3 := RmatZ qOne

def octaKernel : List QZ := octa.filter (fun q => decide (RmatZ q = RIdent))

def nubM3 (l : List M3) : List M3 :=
  l.foldl (fun acc m => if acc.contains m then acc else acc ++ [m]) []
def octaImage : List M3 := nubM3 (octa.map RmatZ)

theorem octa_kernel_is_pm_one :
    octaKernel = [qOne, qNeg1] ∧ octaKernel.length = 2 := by
  refine ⟨by decide, by decide⟩

theorem octa_neg_invariant :
    (octa.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true := by decide

theorem octa_image_card_is_24 :
    octaImage.length = 24 ∧ octa.length / octaImage.length = 2 := by
  refine ⟨by decide, by decide⟩

end Cover2

-- ════════════════════════════════════════════════════════════
-- §  Master certificate — the 2O cover, computed
-- ════════════════════════════════════════════════════════════

namespace Cover2
open GR ZSqrt2

/-- **SPINOR-COVER-2O (master).** The SU(2) → SO(3) double cover realized by EXACT ℤ[√2]
    conjugation rotation `RmatZ` on the binary octahedral group 2O (the 48 octahedral
    units):

      (a) UNIVERSAL HOMOMORPHISM: `RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q)` for
          EVERY pair of ℤ[√2]-quaternions (`hom_bridge2`) — polynomial identity, NOT the
          2304 sampled pairs of 2O.
      (b) CLOSURE: the explicit 48-element octahedral list has length 48 (`octa_card`) and
          is closed under multiplication by the two generators (`octa_gen_closed`).
      (c) `RmatZ q = RmatZ (−q)` for every octahedral unit (`octa_neg_invariant`), so −1
          lies in the kernel and the cover is (at least) 2:1.
      (d) KERNEL = {±1}: exactly the two central units map to the identity rotation
          (`octa_kernel_is_pm_one`).
      (e) IMAGE = 24 = |O| = |S₄| (the octahedral rotation group), cover index 48 / 24 = 2
          (`octa_image_card_is_24`).

    This is the COMPUTED conjugation lift of the order-level shadow in `OrientationE8Bridge`
    (`binary_is_2to1_spin_cover` for the octahedral case); it is the finite restriction of
    the continuous cover, not the continuous cover. -/
theorem spinor_cover_2O_master :
    (∀ p q : QZ, RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q))
    ∧ octa.length = 48
    ∧ (octa.all (fun a => gens2.all (fun g => octa.contains (qmulS a g)))) = true
    ∧ (octa.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true
    ∧ (octaKernel = [qOne, qNeg1] ∧ octaKernel.length = 2)
    ∧ (octaImage.length = 24 ∧ octa.length / octaImage.length = 2) := by
  refine ⟨hom_bridge2, octa_card, octa_gen_closed, octa_neg_invariant,
          octa_kernel_is_pm_one, octa_image_card_is_24⟩

/-- **The computed 2O cover index equals the order-level shadow.** The index 2 computed
    here from the conjugation rotation (`|2O| / |image| = 48 / 24 = 2`) equals the tabulated
    `Gnosis.OrientationE8Bridge.spinCoverIndex`, and the carrier/image counts match the
    order-arithmetic `subgroupOrder .BinaryOcta / rotationOrder .Octa = 48 / 24`. The
    conjugation computation reproduces — and lifts — `binary_is_2to1_spin_cover` for the
    octahedral case. -/
theorem octa_cover_index_ties_to_shadow :
    octa.length / octaImage.length = Gnosis.OrientationE8Bridge.spinCoverIndex
    ∧ octa.length = ADEMcKayCorrespondence.subgroupOrder .BinaryOcta 0
    ∧ octaImage.length = Gnosis.OrientationE8Bridge.rotationOrder .Octa
    ∧ octa.length / octaImage.length
        = ADEMcKayCorrespondence.subgroupOrder .BinaryOcta 0
            / Gnosis.OrientationE8Bridge.rotationOrder .Octa := by
  refine ⟨by decide, by decide, by decide, by decide⟩

end Cover2

/-! ## Axiom footprint (verified)

`#print axioms` on the headline theorems. The purely finite closed-`decide` theorems depend
on NO axioms; the universal-homomorphism and master theorems depend on at most
`propext` + `Quot.sound` (the standard Init kernel axioms) — propext-at-most, NO
`Classical.choice`:

    Cover2.spinor_cover_2O_master         -- [propext, Quot.sound]
    Cover2.hom_bridge2                     -- [propext, Quot.sound]
    Cover2.octa_card                       -- no axioms
    Cover2.octa_gen_closed                 -- no axioms
    Cover2.octa_kernel_is_pm_one           -- no axioms
    Cover2.octa_neg_invariant              -- no axioms
    Cover2.octa_image_card_is_24           -- no axioms
    Cover2.octa_cover_index_ties_to_shadow -- no axioms
    ZSqrt2.zsqrt2_sq                        -- no axioms

No `native_decide`, no `sorry`, no `admit`, no new `axiom`, no `Classical.choice`, no
`omega`.
-/

#print axioms Cover2.spinor_cover_2O_master
#print axioms Cover2.hom_bridge2
#print axioms Cover2.octa_card
#print axioms Cover2.octa_gen_closed
#print axioms Cover2.octa_kernel_is_pm_one
#print axioms Cover2.octa_neg_invariant
#print axioms Cover2.octa_image_card_is_24
#print axioms Cover2.octa_cover_index_ties_to_shadow
#print axioms ZSqrt2.zsqrt2_sq

/-! ## Next exploration

The sampled SU(2) → SO(3) conjugation-cover ladder is now COMPLETE: Q8 + 2T
(`SpinorCoverSampled`) + 2I (`SpinorCover600Cell`) + 2O (this module) are all exact computed
conjugation covers with kernel {±1}. Open follow-ons:

  * Continuum lift (the genuine deferral): with Mathlib, build the Lie cover SU(2) → SO(3),
    prove surjective with kernel {±I}, and prove each `RmatZ` is its finite restriction to
    the ring-of-integers points. The hard part remains the real-manifold surjectivity.
  * Unify the four finite modules behind ONE ring-generic `hom_bridge` parameterized over
    `GR.CRing R` (the nine entry identities are literally the same `PExpr` shapes; only the
    coefficient ring's `decide` over `reify K` differs). Then Q8/2T/2I/2O are instances of a
    single universal theorem, and a new finite SU(2) subgroup needs only its closure list +
    kernel scan + ring instance.
  * The binary dihedral families 2D_n (the remaining McKay ADE branch, `Ẽ`-type Dₙ) over the
    appropriate cyclotomic ring — the only McKay-ADE binary covers not yet computed here.
-/
