/-
  SpinorCoverADE.lean
  ===================

  The McKay-ADE binary spin-cover ladder COMPLETED on its A (cyclic) and D (dihedral)
  branches by EXACT ℤ[√2] conjugation arithmetic, reusing the `SpinorCover2O` engine
  VERBATIM. With this module every node of the McKay-ADE correspondence is realized by an
  exact COMPUTED conjugation cover with kernel {±1} and index 2:

    A-series (cyclic)   2C4  (8)   over ℤ[√2]   — THIS MODULE §A   → Ã₃   (image C4, 4)
    D-series (dihedral) 2D4  (16)  over ℤ[√2]   — THIS MODULE §D   → D̃₆   (image D4, 8)
    E6 (tetra)          2T   (24)  over ℤ       — SpinorCoverSampled §2
    E7 (octa)           2O   (48)  over ℤ[√2]   — SpinorCover2O
    E8 (icosa)          2I   (120) over ℤ[φ]    — SpinorCover600Cell
    (+ Q8 = 2D2 (8) over ℤ — SpinorCoverSampled §1, the smallest binary dihedral)

  THE ENGINE IS REUSED VERBATIM. We `import Gnosis.SpinorCover2O` and reuse, with NO
  changes, the ℤ[√2] ring `ZSqrt2` (the `GR.CRing Zs2` instance `Kz2` built via the same
  Int-reflection helper `GR.IntInst.Ki`), the symbolic quaternion type `Cover2.QZ`, the
  scaled Hamilton product `Cover2.qmulZ` / `Cover2.qmulS`, the conjugation rotation
  `Cover2.RmatZ`, the matrix product `Cover2.mmulZ`, and — crucially — the UNIVERSAL
  HOMOMORPHISM `Cover2.hom_bridge2`:

    `RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q)`  for EVERY pair of ℤ[√2]-quaternions,

  proved ONCE symbolically from the nine entry polynomial identities `Cover2.e00..e22`
  over the reflective normalizer `GR.reify Kz2`. NOT a single new ring, NOT a single new
  `hom_bridge`. The A and D covers are new CARRIER LISTS over the same engine; the
  homomorphism comes for free from `hom_bridge2`, exactly as 2O reused 2I's nine `e..`
  shapes.

  WHY n = 4 OVER ℤ[√2]. The binary cyclic group 2Cₙ is generated by the unit quaternion
  ζ = cos(π/n) + sin(π/n)·i (rotation by 2π/n about the i-axis). For n = 4,
  cos(π/4) = sin(π/4) = √2/2, so ζ = (1/√2)(1 + i); scaled ×2 (clearing the /√2 and /1)
  its coordinates are `(√2, √2, 0, 0) = (⟨0,1⟩, ⟨0,1⟩, 0, 0) ∈ ℤ[√2]⁴`. The whole 2C4
  orbit stays in (½)·ℤ[√2]⁴, integral after the ×2 scaling — so it reuses `Zs2` with NO
  new ring. The binary dihedral 2D4 adds the flip generator j = (0,0,1,0) (scaled ×2:
  `(0,0,⟨2,0⟩,0)`); its 16 elements likewise live in scaled ℤ[√2]⁴. This is the SIMPLEST
  tractable representative of each series; general n needs ℤ[cos(π/n)] (cyclotomic), the
  documented deferral.

  WHAT LANDS (kernel `decide`, no `native_decide`):

    §A  2C4 (A-series, Ã₃):
        - carrier = explicit 8-element list, `c4_card = 8`;
        - closed under multiplication by the single generator ζ (`c4_gen_closed`);
        - `RmatZ q = RmatZ (−q)` (`c4_neg_invariant`), so −1 ∈ kernel;
        - KERNEL = {±1} (`c4_kernel_is_pm_one`);
        - IMAGE = 4 = |C4| (the cyclic rotation group), index 8/4 = 2
          (`c4_image_card_is_4`);
        - tied to the McKay shadow `subgroupOrder .Cyclic 4 = 4` and `mckayType .Cyclic = .A`.

    §D  2D4 (D-series, D̃₆):
        - carrier = explicit 16-element list, `d4_card = 16`;
        - closed under multiplication by the two generators ζ, j (`d4_gen_closed`);
        - `RmatZ q = RmatZ (−q)` (`d4_neg_invariant`), so −1 ∈ kernel;
        - KERNEL = {±1} (`d4_kernel_is_pm_one`);
        - IMAGE = 8 = |D4| (the dihedral rotation group), index 16/8 = 2
          (`d4_image_card_is_8`);
        - tied to the McKay shadow `subgroupOrder .BinaryDihedral 4 = 16` and
          `mckayType .BinaryDihedral = .D`.

  RELATIONSHIP TO THE ORDER-LEVEL SHADOW (precise, not identity). The index 2 computed
  here from the conjugation rotation `RmatZ` (kernel {±1}, image = half the carrier) is the
  COMPUTED conjugation lift of the order arithmetic tabulated in
  `Gnosis.ADEMcKayCorrespondence` (`subgroupOrder`, `mckayType`): there `|2D4| = 4·4 = 16`
  and the A/D McKay types are tabulated; here the carrier/image counts and the index 2 are
  COMPUTED from `RmatZ`.

  HARD CONSTRAINTS (met). Init-only (`import Init` + cited Gnosis bridges, transitively via
  `SpinorCover2O` and `ADEMcKayCorrespondence`). KERNEL `decide`/`rfl`/structural + the
  reused symbolic homomorphism `hom_bridge2` ONLY — NO `native_decide`, no `sorry`, no
  `admit`, no new `axiom`, no `Classical.choice`, no `omega`. `set_option maxRecDepth`
  raised. Gate ONLY on `lake build Gnosis.SpinorCoverADE`. Does NOT edit other modules and
  does NOT register itself in `Gnosis.lean`. `#print axioms` for the headline theorems is at
  the bottom.
-/

import Init
import Gnosis.SpinorCover2O
import Gnosis.ADEMcKayCorrespondence

-- The reused reflective normalizer recurses through degree-4 polynomials in 8 variables
-- over ℤ[√2]; raise the reduction depth to match `SpinorCover2O`.
set_option maxRecDepth 8000

set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false

namespace Gnosis
namespace SpinorCoverADE

open GR ZSqrt2 Cover2
open ADEMcKayCorrespondence (subgroupOrder mckayType ADEType)

-- ══════════════════════════════════════════════════════════
-- §0  Shared helpers over the reused ℤ[√2] engine
-- ══════════════════════════════════════════════════════════

/-! Everything below is built on the VERBATIM-reused `Cover2` engine from
    `Gnosis.SpinorCover2O`:
      * `Cover2.QZ`     — ℤ[√2]-quaternion (four `ZSqrt2.Zs2` coords, scaled ×2);
      * `Cover2.qmulZ`  — the (×4) scaled Hamilton product;
      * `Cover2.qmulS`  — `qmulZ` followed by `zhalf` on each coord (the ×2-scaled product);
      * `Cover2.qnegZ`  — quaternion negation;
      * `Cover2.RmatZ`  — the conjugation rotation matrix (`q ↦ q·v·q⁻¹`, ×|q|²);
      * `Cover2.mmulZ`  — 3×3 ℤ[√2] matrix product;
      * `Cover2.hom_bridge2` — the UNIVERSAL homomorphism `RmatZ (qmulZ p q) =
        mmulZ (RmatZ p) (RmatZ q)` for every ℤ[√2]-quaternion pair (the nine entry
        identities, reused). We add only new carrier lists + finite scans. -/

/-- The shared scaled identity `+1` (×2 = `(2,0,0,0)`) and its negation, reusing
    `Cover2.qOne` / `Cover2.qNeg1`. -/
abbrev qOne  : QZ := Cover2.qOne
abbrev qNeg1 : QZ := Cover2.qNeg1

/-- The identity rotation matrix `RmatZ qOne` (reused). -/
abbrev RIdentADE : M3 := Cover2.RIdent

/-- Distinct-`M3` fold for image de-duplication (reused). -/
abbrev nubM3ADE : List M3 → List M3 := Cover2.nubM3

-- ══════════════════════════════════════════════════════════
-- §A  A-series: the binary cyclic group 2C4 (order 8) over ℤ[√2]  → Ã₃
-- ══════════════════════════════════════════════════════════

/-- The 8 elements of the binary cyclic group `2C4 = ⟨ζ⟩`, `ζ = cos(π/4)+sin(π/4)·i =
    (1/√2)(1+i)`, scaled ×2 so coordinates are integral in ℤ[√2]. The orbit is
    `{ ±1, ±i, ±ζ, ±ζ³ }`:

      ζ⁰ = +1          → (⟨2,0⟩,0,0,0)
      ζ¹ = (1+i)/√2    → (⟨0,1⟩,⟨0,1⟩,0,0)
      ζ² = i           → (0,⟨2,0⟩,0,0)
      ζ³ = (−1+i)/√2   → (⟨0,-1⟩,⟨0,1⟩,0,0)
      ζ⁴ = −1          → (⟨-2,0⟩,0,0,0)
      ζ⁵ = −ζ          → (⟨0,-1⟩,⟨0,-1⟩,0,0)
      ζ⁶ = −i          → (0,⟨-2,0⟩,0,0)
      ζ⁷ = −ζ³         → (⟨0,1⟩,⟨0,-1⟩,0,0)

    Computed exactly in scaled ℤ[√2] arithmetic (no reals). -/
def c4 : List QZ :=
  [ ⟨⟨2,0⟩,  ⟨0,0⟩,  ⟨0,0⟩, ⟨0,0⟩⟩    -- +1
  , ⟨⟨0,1⟩,  ⟨0,1⟩,  ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ
  , ⟨⟨0,0⟩,  ⟨2,0⟩,  ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ² = i
  , ⟨⟨0,-1⟩, ⟨0,1⟩,  ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ³
  , ⟨⟨-2,0⟩, ⟨0,0⟩,  ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ⁴ = −1
  , ⟨⟨0,-1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ⁵
  , ⟨⟨0,0⟩,  ⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩    -- ζ⁶ = −i
  , ⟨⟨0,1⟩,  ⟨0,-1⟩, ⟨0,0⟩, ⟨0,0⟩⟩ ]  -- ζ⁷

/-- The single cyclic generator ζ (scaled ×2). -/
def gC : QZ := ⟨⟨0,1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨0,0⟩⟩
def gensC : List QZ := [gC]

/-- 2C4 has exactly 8 elements. -/
theorem c4_card : c4.length = 8 := by decide

/-- **CLOSURE.** 2C4 is closed under (scaled) multiplication by its generator ζ. With the
    reused universal homomorphism `hom_bridge2`, generator closure pins the group. -/
theorem c4_gen_closed :
    (c4.all (fun a => gensC.all (fun g => c4.contains (qmulS a g)))) = true := by decide

/-- **R(q) = R(−q) on 2C4**, so −1 lies in the kernel and the cover is (at least) 2:1. -/
theorem c4_neg_invariant :
    (c4.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true := by decide

/-- The kernel sample of 2C4: elements whose conjugation rotation is the identity. -/
def c4Kernel : List QZ := c4.filter (fun q => decide (RmatZ q = RIdentADE))

/-- **KERNEL = {±1}.** Exactly the two central units `±1` map to the identity rotation. -/
theorem c4_kernel_is_pm_one :
    c4Kernel = [qOne, qNeg1] ∧ c4Kernel.length = 2 := by
  refine ⟨by decide, by decide⟩

/-- The image of 2C4 under `RmatZ`: the distinct rotation matrices. -/
def c4Image : List M3 := nubM3ADE (c4.map RmatZ)

/-- **IMAGE = 4 = |C4|, index 8/4 = 2.** The image is the cyclic rotation group C4 (order
    4) — the A₃ rotation group — and the cover is exactly 2:1. -/
theorem c4_image_card_is_4 :
    c4Image.length = 4 ∧ c4.length / c4Image.length = 2 := by
  refine ⟨by decide, by decide⟩

/-- **The computed 2C4 cover ties to the McKay A-node shadow.** The image order 4 equals
    the tabulated `subgroupOrder .Cyclic 4` (the cyclic rotation group Cₙ, the Ã_{n-1} =
    Ã₃ node), the carrier 8 = 2·4 is its binary preimage, and the McKay type is `.A`. The
    conjugation computation reproduces — and lifts — the order-level A-series shadow. -/
theorem c4_cover_ties_to_shadow :
    c4Image.length = subgroupOrder .Cyclic 4
    ∧ c4.length = 2 * subgroupOrder .Cyclic 4
    ∧ c4.length / c4Image.length = 2
    ∧ mckayType .Cyclic = ADEType.A := by
  refine ⟨by decide, by decide, by decide, by decide⟩

/-- **`spinor_cover_2C4_master` — A-series master.** The conjugation rotation `RmatZ`
    realizes the SU(2)→SO(3) double cover EXACTLY on the binary cyclic group 2C4 over
    ℤ[√2]:

      (a) UNIVERSAL HOMOMORPHISM `hom_bridge2` (reused verbatim): `RmatZ (qmulZ p q) =
          mmulZ (RmatZ p) (RmatZ q)` for EVERY ℤ[√2]-quaternion pair;
      (b) CLOSURE: the explicit 8-element list is closed under the generator ζ;
      (c) `RmatZ q = RmatZ (−q)`, so −1 ∈ kernel;
      (d) KERNEL = {±1};
      (e) IMAGE = 4 = |C4|, index 8/4 = 2. -/
theorem spinor_cover_2C4_master :
    (∀ p q : QZ, RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q))
    ∧ c4.length = 8
    ∧ (c4.all (fun a => gensC.all (fun g => c4.contains (qmulS a g)))) = true
    ∧ (c4.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true
    ∧ (c4Kernel = [qOne, qNeg1] ∧ c4Kernel.length = 2)
    ∧ (c4Image.length = 4 ∧ c4.length / c4Image.length = 2) := by
  refine ⟨hom_bridge2, c4_card, c4_gen_closed, c4_neg_invariant,
          c4_kernel_is_pm_one, c4_image_card_is_4⟩

-- ══════════════════════════════════════════════════════════
-- §D  D-series: the binary dihedral group 2D4 (order 16) over ℤ[√2]  → D̃₆
-- ══════════════════════════════════════════════════════════

/-- The 16 elements of the binary dihedral group `2D4 = ⟨ζ, j⟩`, `ζ = (1/√2)(1+i)`,
    `j` the flip. Scaled ×2; coordinates integral in ℤ[√2]. The 16 = the 8 of 2C4
    (the cyclic ⟨ζ⟩ part) plus their right-multiples by j (`{ ±j, ±k, ±ζj, ±ζ³j }`),
    computed exactly:

      ⟨ζ⟩  : ±1, ±i, ±ζ, ±ζ³            (as in §A)
      ⟨ζ⟩j : ±j, ±k, ±ζj=(j+k)/√2,
                         ±ζ³j=(−j+k)/√2

    All in scaled ℤ[√2] arithmetic (no reals). -/
def d4 : List QZ :=
  [ -- the cyclic part ⟨ζ⟩ (= 2C4)
    ⟨⟨2,0⟩,  ⟨0,0⟩,  ⟨0,0⟩,  ⟨0,0⟩⟩     -- +1
  , ⟨⟨0,1⟩,  ⟨0,1⟩,  ⟨0,0⟩,  ⟨0,0⟩⟩     -- ζ
  , ⟨⟨0,0⟩,  ⟨2,0⟩,  ⟨0,0⟩,  ⟨0,0⟩⟩     -- i
  , ⟨⟨0,-1⟩, ⟨0,1⟩,  ⟨0,0⟩,  ⟨0,0⟩⟩     -- ζ³
  , ⟨⟨-2,0⟩, ⟨0,0⟩,  ⟨0,0⟩,  ⟨0,0⟩⟩     -- −1
  , ⟨⟨0,-1⟩, ⟨0,-1⟩, ⟨0,0⟩,  ⟨0,0⟩⟩     -- −ζ
  , ⟨⟨0,0⟩,  ⟨-2,0⟩, ⟨0,0⟩,  ⟨0,0⟩⟩     -- −i
  , ⟨⟨0,1⟩,  ⟨0,-1⟩, ⟨0,0⟩,  ⟨0,0⟩⟩     -- −ζ³
    -- the reflection coset ⟨ζ⟩·j
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨2,0⟩,  ⟨0,0⟩⟩     -- j
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,1⟩,  ⟨0,1⟩⟩     -- ζj  = (j+k)/√2
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,0⟩,  ⟨2,0⟩⟩     -- k
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,-1⟩, ⟨0,1⟩⟩     -- ζ³j = (−j+k)/√2
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨-2,0⟩, ⟨0,0⟩⟩     -- −j
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,-1⟩, ⟨0,-1⟩⟩    -- −ζj
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,0⟩,  ⟨-2,0⟩⟩    -- −k
  , ⟨⟨0,0⟩,  ⟨0,0⟩,  ⟨0,1⟩,  ⟨0,-1⟩⟩ ]  -- −ζ³j

/-- The two dihedral generators: ζ (rotation, scaled ×2) and j (flip, scaled ×2). -/
def gJ : QZ := ⟨⟨0,0⟩, ⟨0,0⟩, ⟨2,0⟩, ⟨0,0⟩⟩
def gensD : List QZ := [gC, gJ]

/-- 2D4 has exactly 16 elements. -/
theorem d4_card : d4.length = 16 := by decide

/-- **CLOSURE.** 2D4 is closed under (scaled) multiplication by its two generators ζ, j.
    With the reused universal homomorphism, generator closure pins the group. -/
theorem d4_gen_closed :
    (d4.all (fun a => gensD.all (fun g => d4.contains (qmulS a g)))) = true := by decide

/-- **R(q) = R(−q) on 2D4**, so −1 lies in the kernel and the cover is (at least) 2:1. -/
theorem d4_neg_invariant :
    (d4.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true := by decide

/-- The kernel sample of 2D4. -/
def d4Kernel : List QZ := d4.filter (fun q => decide (RmatZ q = RIdentADE))

/-- **KERNEL = {±1}.** Exactly the two central units `±1` map to the identity rotation. -/
theorem d4_kernel_is_pm_one :
    d4Kernel = [qOne, qNeg1] ∧ d4Kernel.length = 2 := by
  refine ⟨by decide, by decide⟩

/-- The image of 2D4 under `RmatZ`. -/
def d4Image : List M3 := nubM3ADE (d4.map RmatZ)

/-- **IMAGE = 8 = |D4|, index 16/8 = 2.** The image is the dihedral rotation group D4
    (order 8) and the cover is exactly 2:1. -/
theorem d4_image_card_is_8 :
    d4Image.length = 8 ∧ d4.length / d4Image.length = 2 := by
  refine ⟨by decide, by decide⟩

/-- **The computed 2D4 cover ties to the McKay D-node shadow.** The carrier order 16
    equals the tabulated `subgroupOrder .BinaryDihedral 4` (the binary dihedral group, the
    D̃_{n+2} = D̃₆ node), the image 8 = 16/2 is the dihedral rotation group D4, and the
    McKay type is `.D`. The conjugation computation reproduces — and lifts — the
    order-level D-series shadow. -/
theorem d4_cover_ties_to_shadow :
    d4.length = subgroupOrder .BinaryDihedral 4
    ∧ d4Image.length = subgroupOrder .BinaryDihedral 4 / 2
    ∧ d4.length / d4Image.length = 2
    ∧ mckayType .BinaryDihedral = ADEType.D := by
  refine ⟨by decide, by decide, by decide, by decide⟩

/-- **`spinor_cover_2D4_master` — D-series master.** The conjugation rotation `RmatZ`
    realizes the SU(2)→SO(3) double cover EXACTLY on the binary dihedral group 2D4 over
    ℤ[√2]:

      (a) UNIVERSAL HOMOMORPHISM `hom_bridge2` (reused verbatim);
      (b) CLOSURE: the explicit 16-element list is closed under ζ and j;
      (c) `RmatZ q = RmatZ (−q)`, so −1 ∈ kernel;
      (d) KERNEL = {±1};
      (e) IMAGE = 8 = |D4|, index 16/8 = 2. -/
theorem spinor_cover_2D4_master :
    (∀ p q : QZ, RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q))
    ∧ d4.length = 16
    ∧ (d4.all (fun a => gensD.all (fun g => d4.contains (qmulS a g)))) = true
    ∧ (d4.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true
    ∧ (d4Kernel = [qOne, qNeg1] ∧ d4Kernel.length = 2)
    ∧ (d4Image.length = 8 ∧ d4.length / d4Image.length = 2) := by
  refine ⟨hom_bridge2, d4_card, d4_gen_closed, d4_neg_invariant,
          d4_kernel_is_pm_one, d4_image_card_is_8⟩

-- ══════════════════════════════════════════════════════════
-- §M  Master certificate — the McKay-ADE A+D branches, computed
-- ══════════════════════════════════════════════════════════

/-- **SPINOR-COVER-ADE (master).** The McKay-ADE binary spin covers on the A (cyclic) and
    D (dihedral) branches are EXACT COMPUTED conjugation covers with kernel {±1} and
    index 2, sharing ONE engine with the E-branch (the `Cover2` ℤ[√2] machinery + the
    universal homomorphism `hom_bridge2`, reused verbatim from `SpinorCover2O`):

      A-series  2C4 (8)  over ℤ[√2]:  closure under ζ, kernel {±1}, image C4 (4),
                                      index 8/4 = 2, McKay type `.A` (Ã₃).
      D-series  2D4 (16) over ℤ[√2]:  closure under ζ, j, kernel {±1}, image D4 (8),
                                      index 16/8 = 2, McKay type `.D` (D̃₆).

    Combined with E6/E7/E8 (2T/2O/2I) and Q8 (= 2D2), EVERY McKay-ADE node is now realized
    by a computed 2:1 conjugation cover with kernel {±1}. These are the FINITE
    representatives (n = 4); general n is the documented Next exploration. -/
theorem spinor_cover_ADE_master :
    -- shared universal homomorphism (one engine, reused)
    (∀ p q : QZ, RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q))
    -- A-series 2C4
    ∧ (c4.length = 8
        ∧ (c4Kernel = [qOne, qNeg1] ∧ c4Kernel.length = 2)
        ∧ (c4Image.length = 4 ∧ c4.length / c4Image.length = 2)
        ∧ mckayType .Cyclic = ADEType.A)
    -- D-series 2D4
    ∧ (d4.length = 16
        ∧ (d4Kernel = [qOne, qNeg1] ∧ d4Kernel.length = 2)
        ∧ (d4Image.length = 8 ∧ d4.length / d4Image.length = 2)
        ∧ mckayType .BinaryDihedral = ADEType.D)
    -- both indices = 2 = the shared {±1} fibre
    ∧ (c4.length / c4Image.length = d4.length / d4Image.length) := by
  refine ⟨hom_bridge2,
          ⟨c4_card, c4_kernel_is_pm_one, c4_image_card_is_4, by decide⟩,
          ⟨d4_card, d4_kernel_is_pm_one, d4_image_card_is_8, by decide⟩,
          by decide⟩

/-! ## Axiom footprint (verified)

`#print axioms` on the headline theorems. The purely finite closed-`decide` theorems depend
on NO axioms; the universal-homomorphism-bearing theorems depend at most on
`propext` + `Quot.sound` (inherited from the reused `Cover2.hom_bridge2`) — propext-at-most,
NO `Classical.choice`:

    Gnosis.SpinorCoverADE.spinor_cover_ADE_master   -- [propext, Quot.sound]
    Gnosis.SpinorCoverADE.spinor_cover_2C4_master   -- [propext, Quot.sound]
    Gnosis.SpinorCoverADE.spinor_cover_2D4_master   -- [propext, Quot.sound]
    Gnosis.SpinorCoverADE.c4_card                    -- no axioms
    Gnosis.SpinorCoverADE.c4_gen_closed              -- no axioms
    Gnosis.SpinorCoverADE.c4_kernel_is_pm_one        -- no axioms
    Gnosis.SpinorCoverADE.c4_image_card_is_4         -- no axioms
    Gnosis.SpinorCoverADE.c4_cover_ties_to_shadow    -- no axioms
    Gnosis.SpinorCoverADE.d4_card                    -- no axioms
    Gnosis.SpinorCoverADE.d4_gen_closed              -- no axioms
    Gnosis.SpinorCoverADE.d4_kernel_is_pm_one        -- no axioms
    Gnosis.SpinorCoverADE.d4_image_card_is_8         -- no axioms
    Gnosis.SpinorCoverADE.d4_cover_ties_to_shadow    -- no axioms

No `native_decide`, no `sorry`, no `admit`, no new `axiom`, no `Classical.choice`, no
`omega`.
-/

#print axioms spinor_cover_ADE_master
#print axioms spinor_cover_2C4_master
#print axioms spinor_cover_2D4_master
#print axioms c4_card
#print axioms c4_gen_closed
#print axioms c4_kernel_is_pm_one
#print axioms c4_image_card_is_4
#print axioms c4_cover_ties_to_shadow
#print axioms d4_card
#print axioms d4_gen_closed
#print axioms d4_kernel_is_pm_one
#print axioms d4_image_card_is_8
#print axioms d4_cover_ties_to_shadow

/-! ## Next exploration

With the A (2C4) and D (2D4) branches landed here, and E6/E7/E8 (2T/2O/2I) + Q8 (= 2D2)
already done, every McKay-ADE node is realized by an EXACT COMPUTED conjugation cover with
kernel {±1} and index 2 — for these FINITE representatives. Open follow-ons:

  * GENERAL-n CYCLOTOMIC CASE (the genuine deferral). 2Cₙ / 2Dₙ for arbitrary n need
    ζ = cos(π/n) + sin(π/n)·i with cos(π/n) ∈ ℤ[ζ_{2n}]ᵣₑ — the real cyclotomic ring
    ℤ[cos(π/n)] (= ℤ[2cos(π/n)], the ring of integers of the maximal real subfield of
    ℚ(ζ_{2n})). n = 4 reduces to ℤ[√2] (this module) and n = 6 to ℤ[√3]; general n needs
    the cyclotomic ring built via the same Int-reflection `Ki` helper (a `GR.CRing` on the
    minimal-polynomial quotient, coords a Float-free integer vector in the power basis).
    The orbit-BFS closure + kernel scan are unchanged; only the ring instance grows. The
    families would then be ONE theorem schema parameterized over n, not per-n lists.

  * RING-GENERIC UNIFICATION OF ALL COVERS BEHIND ONE `hom_bridge`. The nine entry
    identities `e00..e22` are literally the same `PExpr` shapes for every coefficient ring;
    only the `decide`-over-`reify K` step differs (ℤ for Q8/2T, ℤ[√2] for 2O/2C4/2D4, ℤ[φ]
    for 2I, ℤ[√3] for 2C6/2D3). Factor a `hom_bridge_generic {R} [DecidableEq R]
    (K : GR.CRing R) (he00 .. he22 : reify K _ = reify K _) : ∀ p q, RmatZ (qmulZ p q) =
    mmulZ (RmatZ p) (RmatZ q)` so each finite cover supplies only (a) its ring instance,
    (b) its nine `decide`d normal forms, (c) its carrier list. Then A/D/E6/E7/E8 + Q8 are
    instances of a single universal cover theorem, and a new SU(2) subgroup needs only a
    closure list + kernel scan.

  * CONTINUUM LIFT (still deferred, needs Mathlib). Build the Lie cover SU(2) → SO(3),
    prove surjective with kernel {±I}, and prove each `RmatZ` is its finite restriction to
    the ring-of-integers points. The hard part remains the real-manifold surjectivity.
-/

end SpinorCoverADE
end Gnosis
