/-
  SpinorCover600Cell.lean
  =======================

  The SU(2) → SO(3) double cover COMPUTED on the binary icosahedral group 2I — the 120
  unit icosian quaternions, the 600-cell vertices — by EXACT ℤ[φ] conjugation arithmetic.

  This is the TIER-3 lift left as the `Next exploration` of `Gnosis.SpinorCoverSampled`
  (which lands Q8 / 2T by per-pair `decide`). There the 2I cover was DEFERRED: the per-pair
  homomorphism `decide` over 120² = 14400 ordered pairs in golden-ratio quadratic-integer
  arithmetic blows the kernel heartbeat budget. This module lands 2I WITHOUT that blowup.

  THE CRACK — the homomorphism is UNIVERSAL, not sampled. The conjugation-to-rotation map
  `R(q) = q·v·q⁻¹` (in matrix form, scaled by |q|²) satisfies `R(p·q) = R(p)·R(q)` as a
  POLYNOMIAL IDENTITY in the components of `p` and `q`, true for ALL ℤ[φ]-quaternions, not
  just for elements of a finite subgroup. We prove this ONCE, symbolically, by a verified
  reflective polynomial normalizer (§1–§3), NOT by enumerating pairs. The 2I cover then
  reduces to a SMALL number of finite checks:

    (a) UNIVERSAL HOMOMORPHISM (`hom_bridge`): `R(p·q) = R(p)·R(q)` for every pair of
        ℤ[φ]-quaternions, proved as nine polynomial-identity `decide`s in 8 ℤ[φ]-variables
        (the quaternion components) — NOT 14400 sampled pairs. Each identity is normalized
        by the reflective engine and checked by kernel `decide`.
    (b) CLOSURE TO 120 (`icosa_card`, `icosa_gen_closed`): the 120 icosians are generated by
        orbit-BFS from two generators (the unit `i` and the golden icosian
        `(φ + φ⁻¹·i + j)/2`); we verify the explicit 120-element list and that it is closed
        under multiplication by each GENERATOR (240 checks), NOT all 14400 products. With the
        universal homomorphism, generator-closure pins the group.
    (c) KERNEL = {±1} (`icosa_kernel_is_pm_one`): exactly the two central units `±1` map to
        the identity rotation — a 120-element scan. Image = 60 distinct rotation matrices
        (`icosa_image_card_is_sixty`) = the icosahedral rotation group I ≅ A₅; cover index
        120 / 60 = 2.

  EXACT ℤ[φ] ARITHMETIC. An icosian unit lives in ½·ℤ[φ]⁴ (8 Lipschitz `±eᵢ`, 16
  `(±1±i±j±k)/2`, 96 even permutations of `(±φ ± i ± φ⁻¹·j)/2`). We store every quaternion
  SCALED BY 2 so the `/2` is integer; `1/φ = φ − 1` keeps `φ⁻¹` inside ℤ[φ]. All arithmetic
  is exact integer-pair arithmetic in ℤ[φ] (`φ² = φ + 1`), no reals.

  RELATIONSHIP TO E8 (precise, not identity). The 120 = 2·60 here is the COMPUTED
  conjugation lift of the order-level arithmetic in `Gnosis.OrientationE8Bridge`
  (`binary_is_2to1_spin_cover`, `icosa_spin_cover_lands_on_E8`): there `|2I| = 2·|I|` is
  tabulated; here the index 2 is COMPUTED from `R` (kernel {±1}, image 60). The 600-cell
  vertex set realized here MAPS TO the lattice `open-source/gnosis/distributed-inference/
  src/e8_quantizer.rs` cites as optimal SO(3) sampling for orientation→spin→2I→E8.

  HARD CONSTRAINTS (met). Init-only (`import Init` + cited Gnosis bridges). KERNEL
  `decide`/`rfl`/structural + the symbolic homomorphism identity ONLY — NO `native_decide`,
  no `sorry`, no `admit`, no new `axiom`, no `Classical.choice`, no `omega`. `set_option
  maxRecDepth` raised (the polynomial normalizer recurses deep). Gate ONLY on
  `lake build Gnosis.SpinorCover600Cell`. Does NOT edit `SpinorCoverSampled` and does NOT
  register itself in `Gnosis.lean` (the orchestrator does that). `#print axioms` for the
  headline theorems is at the bottom.

  WHAT THIS IS / IS NOT. This is the FINITE RESTRICTION of the continuous Lie cover
  `SU(2) → SO(3)` to the 2I subgroup, realized by ACTUAL conjugation. It does NOT establish
  surjectivity onto the full continuous SO(3) (that needs Mathlib; see
  `SpinorCoverSampled`'s §5 trail).
-/

import Init
import Gnosis.OrientationE8Bridge
import Gnosis.OrientationSpinorBridge

-- The reflective polynomial normalizer recurses through degree-4 ℤ[φ]-polynomials in 8
-- variables; raise the reduction depth. This is a DEPTH knob, not a tactic exception —
-- still pure kernel `decide`, no `native_decide`.
set_option maxRecDepth 8000

-- Cosmetic linters only (the generic engine carries `[DecidableEq R]` for the normalizer's
-- coefficient-zero test; a few sub-lemmas don't use it, and two `simp` calls list a
-- redundant `Int.zero_add`). These do not affect the kernel proofs.
set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false

namespace GR

structure CRing (R : Type) where
  add : R → R → R
  mul : R → R → R
  neg : R → R
  zero : R
  one : R
  add_comm : ∀ a b, add a b = add b a
  add_assoc : ∀ a b c, add (add a b) c = add a (add b c)
  add_left_comm : ∀ a b c, add a (add b c) = add b (add a c)
  zero_add : ∀ a, add zero a = a
  add_zero : ∀ a, add a zero = a
  mul_comm : ∀ a b, mul a b = mul b a
  mul_assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)
  mul_left_comm : ∀ a b c, mul a (mul b c) = mul b (mul a c)
  add_mul : ∀ a b c, mul (add a b) c = add (mul a c) (mul b c)
  mul_add : ∀ a b c, mul a (add b c) = add (mul a b) (mul a c)
  zero_mul : ∀ a, mul zero a = zero
  mul_zero : ∀ a, mul a zero = zero
  one_mul : ∀ a, mul one a = a
  mul_one : ∀ a, mul a one = a
  neg_mul : ∀ a b, mul (neg a) b = neg (mul a b)
  neg_add : ∀ a b, neg (add a b) = add (neg a) (neg b)

def Rpow {R : Type} (K : CRing R) (x : R) : Nat → R
  | 0 => K.one
  | n+1 => K.mul x (Rpow K x n)
theorem Rpow_add {R : Type} (K : CRing R) (x : R) (m n : Nat) :
    Rpow K x (m+n) = K.mul (Rpow K x m) (Rpow K x n) := by
  induction m with
  | zero => simp only [Rpow, Nat.zero_add]; rw [K.one_mul]
  | succ k ih => simp only [Rpow, Nat.succ_add]; rw [ih, K.mul_assoc]

variable {R : Type} [DecidableEq R] (K : CRing R)

abbrev Mono := List Nat
abbrev Term (R : Type) := Mono × R
abbrev Poly (R : Type) := List (Term R)

def monoLt : Mono → Mono → Bool
  | [], [] => false
  | [], _  => true
  | _, []  => false
  | a::as, b::bs => if a < b then true else if b < a then false else monoLt as bs

def insertTerm (t : Term R) (p : Poly R) : Poly R :=
  match p with
  | [] => if decide (t.2 = K.zero) then [] else [t]
  | h :: rest =>
    if h.1 == t.1 then
      let c := K.add h.2 t.2
      if decide (c = K.zero) then rest else (h.1, c) :: rest
    else if monoLt t.1 h.1 then
      (if decide (t.2 = K.zero) then h :: rest else t :: h :: rest)
    else h :: insertTerm t rest

def padd (a b : Poly R) : Poly R := a.foldr (insertTerm K) b
def pneg (a : Poly R) : Poly R := a.map (fun t => (t.1, K.neg t.2))
def psub (a b : Poly R) : Poly R := padd K a (pneg K b)

def monoMul : Mono → Mono → Mono
  | [], m2 => m2
  | m1, [] => m1
  | a::as, b::bs => (a+b) :: monoMul as bs

def ptmul (t : Term R) (p : Poly R) : Poly R :=
  p.foldr (fun s acc => insertTerm K (monoMul t.1 s.1, K.mul t.2 s.2) acc) []

def pmul (a b : Poly R) : Poly R := a.foldr (fun t acc => padd K (ptmul K t b) acc) []

def vmono (i : Nat) : Mono := List.replicate i 0 ++ [1]
def pvar (i : Nat) : Poly R := [(vmono i, K.one)]
def pconst (c : R) : Poly R := if decide (c = K.zero) then [] else [([], c)]

def evalMonoAux (env : Nat → R) : Nat → Mono → R
  | _, [] => K.one
  | i, e :: es => K.mul (Rpow K (env i) e) (evalMonoAux env (i+1) es)
def emono (env : Nat → R) (m : Mono) : R := evalMonoAux K env 0 m
def eterm (env : Nat → R) (t : Term R) : R := K.mul t.2 (emono K env t.1)
def eval (env : Nat → R) (p : Poly R) : R := p.foldr (fun t acc => K.add (eterm K env t) acc) K.zero

theorem eval_insertTerm (env : Nat → R) (t : Term R) (p : Poly R) :
    eval K env (insertTerm K t p) = K.add (eterm K env t) (eval K env p) := by
  induction p with
  | nil =>
    simp only [insertTerm]
    by_cases h : decide (t.2 = K.zero)
    · simp only [h, if_true]
      have ht : t.2 = K.zero := of_decide_eq_true h
      simp only [eval, eterm, ht, List.foldr]
      rw [K.zero_mul, K.add_zero]
    · have hf : decide (t.2 = K.zero) = false := by
        cases hh : decide (t.2 = K.zero) with
        | false => rfl
        | true => exact absurd hh h
      rw [hf]
      simp only [Bool.false_eq_true, if_false, eval, List.foldr, K.add_zero]
  | cons hd tl ih =>
    simp only [insertTerm]
    by_cases heq : hd.1 == t.1
    · simp only [heq, if_true]
      have hm : hd.1 = t.1 := (beq_iff_eq).1 heq
      by_cases hc : decide (K.add hd.2 t.2 = K.zero)
      · simp only [hc, if_true]
        have hsum : K.add hd.2 t.2 = K.zero := of_decide_eq_true hc
        simp only [eval, List.foldr]
        have hz : K.add (eterm K env hd) (eterm K env t) = K.zero := by
          simp only [eterm, hm]
          rw [← K.add_mul, hsum, K.zero_mul]
        rw [← K.add_assoc, K.add_comm (eterm K env t) (eterm K env hd), hz, K.zero_add]
      · have hcf : decide (K.add hd.2 t.2 = K.zero) = false := by
          cases h : decide (K.add hd.2 t.2 = K.zero) with
          | false => rfl
          | true => exact absurd h hc
        rw [hcf]
        simp only [Bool.false_eq_true, if_false, eval, List.foldr, eterm, hm]
        rw [K.add_mul, K.add_assoc]
        exact K.add_left_comm _ _ _
    · have heqf : (hd.1 == t.1) = false := by
        cases h : (hd.1 == t.1) with
        | false => rfl
        | true => exact absurd h heq
      simp only [heqf, Bool.false_eq_true, if_false]
      by_cases hlt : monoLt t.1 hd.1
      · simp only [hlt, if_true]
        by_cases h0 : decide (t.2 = K.zero)
        · have ht0 : t.2 = K.zero := of_decide_eq_true h0
          rw [h0]
          simp only [if_true, eval, List.foldr, eterm, ht0]
          rw [K.zero_mul, K.zero_add]
        · have h0f : decide (t.2 = K.zero) = false := by
            cases h : decide (t.2 = K.zero) with
            | false => rfl
            | true => exact absurd h h0
          simp only [h0f, Bool.false_eq_true, if_false, eval, List.foldr]
      · have hltf : monoLt t.1 hd.1 = false := by
          cases h : monoLt t.1 hd.1 with
          | false => rfl
          | true => exact absurd h hlt
        simp only [hltf, Bool.false_eq_true, if_false]
        show K.add (eterm K env hd) (eval K env (insertTerm K t tl))
           = K.add (eterm K env t) (K.add (eterm K env hd) (eval K env tl))
        rw [ih]
        exact K.add_left_comm _ _ _

theorem eval_padd (env : Nat → R) (a b : Poly R) :
    eval K env (padd K a b) = K.add (eval K env a) (eval K env b) := by
  unfold padd
  induction a with
  | nil => simp only [List.foldr, eval]; rw [K.zero_add]
  | cons hd tl ih =>
    simp only [List.foldr]
    rw [eval_insertTerm, ih]
    simp only [eval, List.foldr]
    rw [← K.add_assoc]

theorem neg_zero : K.neg K.zero = K.zero := by
  have h := K.neg_mul K.zero K.zero
  rw [K.mul_zero, K.zero_mul] at h
  exact h.symm

theorem eval_pneg (env : Nat → R) (a : Poly R) :
    eval K env (pneg K a) = K.neg (eval K env a) := by
  induction a with
  | nil => simp only [pneg, List.map, eval, List.foldr]; exact (neg_zero K).symm
  | cons hd tl ih =>
    simp only [pneg, List.map, eval, List.foldr] at *
    rw [ih]
    simp only [eterm]
    rw [K.neg_mul, K.neg_add]

theorem evalMonoAux_monoMul (env : Nat → R) :
    ∀ (i : Nat) (m1 m2 : Mono),
      evalMonoAux K env i (monoMul m1 m2) = K.mul (evalMonoAux K env i m1) (evalMonoAux K env i m2) := by
  intro i m1
  induction m1 generalizing i with
  | nil => intro m2; simp only [monoMul, evalMonoAux]; rw [K.one_mul]
  | cons a as ih =>
    intro m2
    cases m2 with
    | nil => simp only [monoMul, evalMonoAux]; rw [K.mul_one]
    | cons b bs =>
      simp only [monoMul, evalMonoAux]
      rw [ih (i+1) bs, Rpow_add]
      rw [K.mul_assoc, K.mul_left_comm (Rpow K (env i) b), ← K.mul_assoc, ← K.mul_assoc]

theorem emono_monoMul (env : Nat → R) (m1 m2 : Mono) :
    emono K env (monoMul m1 m2) = K.mul (emono K env m1) (emono K env m2) := by
  simp only [emono]; exact evalMonoAux_monoMul K env 0 m1 m2

theorem eval_ptmul (env : Nat → R) (t : Term R) (p : Poly R) :
    eval K env (ptmul K t p) = K.mul (eterm K env t) (eval K env p) := by
  induction p with
  | nil => simp only [ptmul, eval, eterm, List.foldr]; rw [K.mul_zero]
  | cons hd tl ih =>
    simp only [ptmul, List.foldr] at *
    rw [eval_insertTerm, ih]
    simp only [eterm, emono_monoMul, eval, List.foldr]
    rw [K.mul_add]
    have e1 : K.mul (K.mul t.2 hd.2) (K.mul (emono K env t.1) (emono K env hd.1))
            = K.mul (K.mul t.2 (emono K env t.1)) (K.mul hd.2 (emono K env hd.1)) := by
      rw [K.mul_assoc, K.mul_assoc, K.mul_left_comm hd.2 (emono K env t.1)]
    rw [e1]

theorem eval_pmul (env : Nat → R) (a b : Poly R) :
    eval K env (pmul K a b) = K.mul (eval K env a) (eval K env b) := by
  induction a with
  | nil => simp only [pmul, eval, List.foldr]; rw [K.zero_mul]
  | cons hd tl ih =>
    simp only [pmul, List.foldr] at *
    rw [eval_padd, ih, eval_ptmul]
    simp only [eval, List.foldr, eterm]
    rw [K.add_mul]

theorem eval_psub (env : Nat → R) (a b : Poly R) :
    eval K env (psub K a b) = K.add (eval K env a) (K.neg (eval K env b)) := by
  simp only [psub]; rw [eval_padd, eval_pneg]

theorem evalMonoAux_vmono (env : Nat → R) (i base : Nat) :
    evalMonoAux K env base (List.replicate i 0 ++ [1]) = env (base + i) := by
  induction i generalizing base with
  | zero =>
    simp only [List.replicate, List.nil_append, evalMonoAux, Rpow, Nat.add_zero]
    rw [K.mul_one, K.mul_one]
  | succ k ih =>
    simp only [List.replicate, List.cons_append, evalMonoAux, Rpow]
    rw [K.one_mul, ih (base+1)]
    have : base + 1 + k = base + (k+1) := by rw [Nat.add_assoc, Nat.add_comm 1 k]
    rw [this]

theorem eval_pvar (env : Nat → R) (i : Nat) : eval K env (pvar K i) = env i := by
  simp only [pvar, eval, eterm, emono, vmono, List.foldr]
  rw [evalMonoAux_vmono K env i 0]
  rw [Nat.zero_add, K.one_mul, K.add_zero]

theorem eval_pconst (env : Nat → R) (c : R) : eval K env (pconst K c) = c := by
  simp only [pconst]
  by_cases h : decide (c = K.zero)
  · have hc : c = K.zero := of_decide_eq_true h
    rw [h]
    simp only [if_true, eval, List.foldr, hc]
  · have hf : decide (c = K.zero) = false := by
      cases hh : decide (c = K.zero) with
      | false => rfl
      | true => exact absurd hh h
    rw [hf]
    simp only [Bool.false_eq_true, if_false, eval, eterm, emono, evalMonoAux, List.foldr]
    rw [K.mul_one, K.add_zero]

inductive PExpr where
  | var : Nat → PExpr
  | cst : R → PExpr
  | add : PExpr → PExpr → PExpr
  | sub : PExpr → PExpr → PExpr
  | mul : PExpr → PExpr → PExpr

def denote (env : Nat → R) : @PExpr R → R
  | .var i => env i
  | .cst c => c
  | .add a b => K.add (denote env a) (denote env b)
  | .sub a b => K.add (denote env a) (K.neg (denote env b))
  | .mul a b => K.mul (denote env a) (denote env b)

def reify : @PExpr R → Poly R
  | .var i => pvar K i
  | .cst c => pconst K c
  | .add a b => padd K (reify a) (reify b)
  | .sub a b => psub K (reify a) (reify b)
  | .mul a b => pmul K (reify a) (reify b)

theorem eval_reify (env : Nat → R) (e : @PExpr R) :
    eval K env (reify K e) = denote K env e := by
  induction e with
  | var i => simp only [reify, denote]; exact eval_pvar K env i
  | cst c => simp only [reify, denote]; exact eval_pconst K env c
  | add a b iha ihb => simp only [reify, denote]; rw [eval_padd, iha, ihb]
  | sub a b iha ihb => simp only [reify, denote]; rw [eval_psub, iha, ihb]
  | mul a b iha ihb => simp only [reify, denote]; rw [eval_pmul, iha, ihb]

theorem denote_eq_of_reify_eq (e1 e2 : @PExpr R) (h : reify K e1 = reify K e2) :
    ∀ env, denote K env e1 = denote K env e2 := by
  intro env
  rw [← eval_reify K env e1, ← eval_reify K env e2, h]

end GR
-- (appended to genengine) CRing Int instance + verify Int ring lemmas exist
namespace IntInst
open GR
def Ki : CRing Int :=
  { add := (· + ·), mul := (· * ·), neg := (- ·), zero := 0, one := 1
  , add_comm := Int.add_comm, add_assoc := Int.add_assoc, add_left_comm := Int.add_left_comm
  , zero_add := Int.zero_add, add_zero := Int.add_zero
  , mul_comm := Int.mul_comm, mul_assoc := Int.mul_assoc, mul_left_comm := Int.mul_left_comm
  , add_mul := Int.add_mul, mul_add := Int.mul_add
  , zero_mul := Int.zero_mul, mul_zero := Int.mul_zero, one_mul := Int.one_mul, mul_one := Int.mul_one
  , neg_mul := Int.neg_mul, neg_add := fun a b => by rw [Int.neg_add] }
end IntInst

-- ════════ ℤ[φ] as a commutative ring, ring axioms via Int reflection ════════
namespace ZPhi
open GR IntInst

structure Zphi where
  a : Int
  b : Int
deriving DecidableEq, Repr
def zadd (p q : Zphi) : Zphi := ⟨p.a+q.a, p.b+q.b⟩
def zneg (p : Zphi) : Zphi := ⟨-p.a, -p.b⟩
def zmul (p q : Zphi) : Zphi := ⟨p.a*q.a + p.b*q.b, p.a*q.b + p.b*q.a + p.b*q.b⟩
def zzero : Zphi := ⟨0,0⟩
def zone : Zphi := ⟨1,0⟩
theorem zext {p q : Zphi} (ha : p.a = q.a) (hb : p.b = q.b) : p = q := by
  cases p; cases q; simp_all

-- symbolic Zphi pair over the Int engine PExpr
abbrev IE := @PExpr Int
structure SZ where
  a : IE
  b : IE
def szD (env : Nat → Int) (s : SZ) : Zphi := ⟨denote Ki env s.a, denote Ki env s.b⟩
def szadd (p q : SZ) : SZ := ⟨.add p.a q.a, .add p.b q.b⟩
def szmul (p q : SZ) : SZ :=
  ⟨.add (.mul p.a q.a) (.mul p.b q.b), .add (.add (.mul p.a q.b) (.mul p.b q.a)) (.mul p.b q.b)⟩
theorem szadd_D (env) (p q : SZ) : szD env (szadd p q) = zadd (szD env p) (szD env q) := by
  simp only [szD, szadd, zadd, denote, Ki]
theorem szmul_D (env) (p q : SZ) : szD env (szmul p q) = zmul (szD env p) (szD env q) := by
  simp only [szD, szmul, zmul, denote, Ki]
theorem szEq (s t : SZ) (ha : reify Ki s.a = reify Ki t.a) (hb : reify Ki s.b = reify Ki t.b) (env) :
    szD env s = szD env t := by
  apply zext
  · exact denote_eq_of_reify_eq Ki s.a t.a ha env
  · exact denote_eq_of_reify_eq Ki s.b t.b hb env
def sp : SZ := ⟨.var 0, .var 1⟩
def sq : SZ := ⟨.var 2, .var 3⟩
def sr : SZ := ⟨.var 4, .var 5⟩
def envPQR (p q r : Zphi) : Nat → Int := fun i => [p.a,p.b,q.a,q.b,r.a,r.b].getD i 0
theorem sp_D (p q r) : szD (envPQR p q r) sp = p := by simp [szD, sp, denote, envPQR, List.getD]
theorem sq_D (p q r) : szD (envPQR p q r) sq = q := by simp [szD, sq, denote, envPQR, List.getD]
theorem sr_D (p q r) : szD (envPQR p q r) sr = r := by simp [szD, sr, denote, envPQR, List.getD]

theorem zmul_assoc (p q r : Zphi) : zmul (zmul p q) r = zmul p (zmul q r) := by
  have h := szEq (szmul (szmul sp sq) sr) (szmul sp (szmul sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szmul_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_comm (p q : Zphi) : zmul p q = zmul q p := by
  have h := szEq (szmul sp sq) (szmul sq sp) (by decide) (by decide) (envPQR p q p)
  rw [szmul_D, szmul_D, sp_D, sq_D] at h; exact h
theorem zadd_comm (p q : Zphi) : zadd p q = zadd q p := by
  have h := szEq (szadd sp sq) (szadd sq sp) (by decide) (by decide) (envPQR p q p)
  rw [szadd_D, szadd_D, sp_D, sq_D] at h; exact h
theorem zadd_assoc (p q r : Zphi) : zadd (zadd p q) r = zadd p (zadd q r) := by
  have h := szEq (szadd (szadd sp sq) sr) (szadd sp (szadd sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szadd_D, szadd_D, szadd_D, szadd_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_add (p q r : Zphi) : zmul p (zadd q r) = zadd (zmul p q) (zmul p r) := by
  have h := szEq (szmul sp (szadd sq sr)) (szadd (szmul sp sq) (szmul sp sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szadd_D, szadd_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zadd_mul (p q r : Zphi) : zmul (zadd p q) r = zadd (zmul p r) (zmul q r) := by
  have h := szEq (szmul (szadd sp sq) sr) (szadd (szmul sp sr) (szmul sq sr)) (by decide) (by decide) (envPQR p q r)
  rw [szmul_D, szadd_D, szadd_D, szmul_D, szmul_D, sp_D, sq_D, sr_D] at h; exact h
theorem zmul_left_comm (p q r : Zphi) : zmul p (zmul q r) = zmul q (zmul p r) := by
  rw [← zmul_assoc, zmul_comm p q, zmul_assoc]
theorem zadd_left_comm (p q r : Zphi) : zadd p (zadd q r) = zadd q (zadd p r) := by
  rw [← zadd_assoc, zadd_comm p q, zadd_assoc]
theorem zzero_add (p : Zphi) : zadd zzero p = p := by apply zext <;> simp [zadd, zzero, Int.zero_add]
theorem zadd_zero (p : Zphi) : zadd p zzero = p := by apply zext <;> simp [zadd, zzero, Int.add_zero]
theorem zzero_mul (p : Zphi) : zmul zzero p = zzero := by
  apply zext <;> simp [zmul, zzero, Int.zero_mul, Int.add_zero, Int.zero_add]
theorem zmul_zero (p : Zphi) : zmul p zzero = zzero := by
  apply zext <;> simp [zmul, zzero, Int.mul_zero, Int.add_zero]
theorem zone_mul (p : Zphi) : zmul zone p = p := by
  apply zext <;> simp [zmul, zone, Int.one_mul, Int.zero_mul, Int.add_zero, Int.zero_add]
theorem zmul_one (p : Zphi) : zmul p zone = p := by
  apply zext <;> simp [zmul, zone, Int.mul_one, Int.mul_zero, Int.add_zero]
theorem zneg_mul (p q : Zphi) : zmul (zneg p) q = zneg (zmul p q) := by
  apply zext <;> simp [zmul, zneg, Int.neg_mul, Int.neg_add]
theorem zneg_add (p q : Zphi) : zneg (zadd p q) = zadd (zneg p) (zneg q) := by
  apply zext <;> simp [zadd, zneg, Int.neg_add]

def Kz : CRing Zphi :=
  { add := zadd, mul := zmul, neg := zneg, zero := zzero, one := zone
  , add_comm := zadd_comm, add_assoc := zadd_assoc, add_left_comm := zadd_left_comm
  , zero_add := zzero_add, add_zero := zadd_zero
  , mul_comm := zmul_comm, mul_assoc := zmul_assoc, mul_left_comm := zmul_left_comm
  , add_mul := zadd_mul, mul_add := zmul_add
  , zero_mul := zzero_mul, mul_zero := zmul_zero, one_mul := zone_mul, mul_one := zmul_one
  , neg_mul := zneg_mul, neg_add := zneg_add }

theorem zphi_sq : zmul ⟨0,1⟩ ⟨0,1⟩ = ⟨1,1⟩ := by decide

end ZPhi

-- ════════ The universal conjugation homomorphism over ℤ[φ] ════════
namespace Cover
open GR ZPhi

abbrev PE := @PExpr Zphi
def vw : PE := .var 0
def vx : PE := .var 1
def vy : PE := .var 2
def vz : PE := .var 3
def vW : PE := .var 4
def vX : PE := .var 5
def vY : PE := .var 6
def vZ : PE := .var 7
def c2 : PE := .cst ⟨2,0⟩

def pqw : PE := .sub (.sub (.sub (.mul vw vW) (.mul vx vX)) (.mul vy vY)) (.mul vz vZ)
def pqx : PE := .add (.add (.mul vw vX) (.mul vx vW)) (.sub (.mul vy vZ) (.mul vz vY))
def pqy : PE := .add (.sub (.mul vw vY) (.mul vx vZ)) (.add (.mul vy vW) (.mul vz vX))
def pqz : PE := .add (.sub (.add (.mul vw vZ) (.mul vx vY)) (.mul vy vX)) (.mul vz vW)

def R00 (a b cc d : PE) : PE := .sub (.sub (.add (.mul a a) (.mul b b)) (.mul cc cc)) (.mul d d)
def R01 (a b cc d : PE) : PE := .mul c2 (.sub (.mul b cc) (.mul a d))
def R02 (a b cc d : PE) : PE := .mul c2 (.add (.mul b d) (.mul a cc))
def R10 (a b cc d : PE) : PE := .mul c2 (.add (.mul b cc) (.mul a d))
def R11 (a b cc d : PE) : PE := .sub (.add (.sub (.mul a a) (.mul b b)) (.mul cc cc)) (.mul d d)
def R12 (a b cc d : PE) : PE := .mul c2 (.sub (.mul cc d) (.mul a b))
def R20 (a b cc d : PE) : PE := .mul c2 (.sub (.mul b d) (.mul a cc))
def R21 (a b cc d : PE) : PE := .mul c2 (.add (.mul cc d) (.mul a b))
def R22 (a b cc d : PE) : PE := .sub (.sub (.add (.mul a a) (.mul d d)) (.mul b b)) (.mul cc cc)

-- product-matrix entry (i,j) = sum_k R_ik(p) * R_kj(q)
def prodEntry (Ri0 Ri1 Ri2 : PE → PE → PE → PE → PE)
              (R0j R1j R2j : PE → PE → PE → PE → PE) : PE :=
  .add (.add (.mul (Ri0 vw vx vy vz) (R0j vW vX vY vZ))
             (.mul (Ri1 vw vx vy vz) (R1j vW vX vY vZ)))
       (.mul (Ri2 vw vx vy vz) (R2j vW vX vY vZ))

-- 9 entry identities: R_ij(p*q) = sum_k R_ik(p) R_kj(q)
theorem e00 : reify Kz (R00 pqw pqx pqy pqz) = reify Kz (prodEntry R00 R01 R02 R00 R10 R20) := by decide
theorem e01 : reify Kz (R01 pqw pqx pqy pqz) = reify Kz (prodEntry R00 R01 R02 R01 R11 R21) := by decide
theorem e02 : reify Kz (R02 pqw pqx pqy pqz) = reify Kz (prodEntry R00 R01 R02 R02 R12 R22) := by decide
theorem e10 : reify Kz (R10 pqw pqx pqy pqz) = reify Kz (prodEntry R10 R11 R12 R00 R10 R20) := by decide
theorem e11 : reify Kz (R11 pqw pqx pqy pqz) = reify Kz (prodEntry R10 R11 R12 R01 R11 R21) := by decide
theorem e12 : reify Kz (R12 pqw pqx pqy pqz) = reify Kz (prodEntry R10 R11 R12 R02 R12 R22) := by decide
theorem e20 : reify Kz (R20 pqw pqx pqy pqz) = reify Kz (prodEntry R20 R21 R22 R00 R10 R20) := by decide
theorem e21 : reify Kz (R21 pqw pqx pqy pqz) = reify Kz (prodEntry R20 R21 R22 R01 R11 R21) := by decide
theorem e22 : reify Kz (R22 pqw pqx pqy pqz) = reify Kz (prodEntry R20 R21 R22 R02 R12 R22) := by decide

end Cover

-- ════════ Concrete ℤ[φ]-quaternions, conjugation matrix, universal hom ════════
namespace Cover
open GR ZPhi

structure QZ where
  w : Zphi
  x : Zphi
  y : Zphi
  z : Zphi
deriving DecidableEq, Repr

def qmulZ (p q : QZ) : QZ :=
  { w := zsub (zsub (zsub (zmul p.w q.w) (zmul p.x q.x)) (zmul p.y q.y)) (zmul p.z q.z)
  , x := zadd (zadd (zmul p.w q.x) (zmul p.x q.w)) (zsub (zmul p.y q.z) (zmul p.z q.y))
  , y := zadd (zsub (zmul p.w q.y) (zmul p.x q.z)) (zadd (zmul p.y q.w) (zmul p.z q.x))
  , z := zadd (zsub (zadd (zmul p.w q.z) (zmul p.x q.y)) (zmul p.y q.x)) (zmul p.z q.w) }
  where
    zsub a b := zadd a (zneg b)

structure M3 where
  a00 : Zphi
  a01 : Zphi
  a02 : Zphi
  a10 : Zphi
  a11 : Zphi
  a12 : Zphi
  a20 : Zphi
  a21 : Zphi
  a22 : Zphi
deriving DecidableEq, Repr

def zsubZ (a b : Zphi) : Zphi := zadd a (zneg b)
def z2 (p : Zphi) : Zphi := zmul ⟨2,0⟩ p

def RmatZ (q : QZ) : M3 :=
  let a := q.w; let b := q.x; let cc := q.y; let d := q.z
  { a00 := zsubZ (zsubZ (zadd (zmul a a) (zmul b b)) (zmul cc cc)) (zmul d d)
  , a01 := z2 (zsubZ (zmul b cc) (zmul a d))
  , a02 := z2 (zadd (zmul b d) (zmul a cc))
  , a10 := z2 (zadd (zmul b cc) (zmul a d))
  , a11 := zsubZ (zadd (zsubZ (zmul a a) (zmul b b)) (zmul cc cc)) (zmul d d)
  , a12 := z2 (zsubZ (zmul cc d) (zmul a b))
  , a20 := z2 (zsubZ (zmul b d) (zmul a cc))
  , a21 := z2 (zadd (zmul cc d) (zmul a b))
  , a22 := zsubZ (zsubZ (zadd (zmul a a) (zmul d d)) (zmul b b)) (zmul cc cc) }

def mmulZ (P Q : M3) : M3 :=
  { a00 := zadd (zadd (zmul P.a00 Q.a00) (zmul P.a01 Q.a10)) (zmul P.a02 Q.a20)
  , a01 := zadd (zadd (zmul P.a00 Q.a01) (zmul P.a01 Q.a11)) (zmul P.a02 Q.a21)
  , a02 := zadd (zadd (zmul P.a00 Q.a02) (zmul P.a01 Q.a12)) (zmul P.a02 Q.a22)
  , a10 := zadd (zadd (zmul P.a10 Q.a00) (zmul P.a11 Q.a10)) (zmul P.a12 Q.a20)
  , a11 := zadd (zadd (zmul P.a10 Q.a01) (zmul P.a11 Q.a11)) (zmul P.a12 Q.a21)
  , a12 := zadd (zadd (zmul P.a10 Q.a02) (zmul P.a11 Q.a12)) (zmul P.a12 Q.a22)
  , a20 := zadd (zadd (zmul P.a20 Q.a00) (zmul P.a21 Q.a10)) (zmul P.a22 Q.a20)
  , a21 := zadd (zadd (zmul P.a20 Q.a01) (zmul P.a21 Q.a11)) (zmul P.a22 Q.a21)
  , a22 := zadd (zadd (zmul P.a20 Q.a02) (zmul P.a21 Q.a12)) (zmul P.a22 Q.a22) }

-- environment from a concrete pair of quaternions
def qenv (p q : QZ) : Nat → Zphi :=
  fun i => [p.w,p.x,p.y,p.z,q.w,q.x,q.y,q.z].getD i zzero

-- bridge: denote of the symbolic entry expressions = concrete entries
-- (proved by simp unfolding denote on the literal env list)
theorem hom_bridge (p q : QZ) :
    RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q) := by
  have E00 := denote_eq_of_reify_eq Kz _ _ e00 (qenv p q)
  have E01 := denote_eq_of_reify_eq Kz _ _ e01 (qenv p q)
  have E02 := denote_eq_of_reify_eq Kz _ _ e02 (qenv p q)
  have E10 := denote_eq_of_reify_eq Kz _ _ e10 (qenv p q)
  have E11 := denote_eq_of_reify_eq Kz _ _ e11 (qenv p q)
  have E12 := denote_eq_of_reify_eq Kz _ _ e12 (qenv p q)
  have E20 := denote_eq_of_reify_eq Kz _ _ e20 (qenv p q)
  have E21 := denote_eq_of_reify_eq Kz _ _ e21 (qenv p q)
  have E22 := denote_eq_of_reify_eq Kz _ _ e22 (qenv p q)
  cases p; cases q
  simp only [RmatZ, mmulZ, qmulZ, qmulZ.zsub, zsubZ, z2, qenv, List.getD,
             denote, Kz, R00, R01, R02, R10, R11, R12, R20, R21, R22,
             prodEntry, pqw, pqx, pqy, pqz, vw, vx, vy, vz, vW, vX, vY, vZ, c2] at *
  refine M3.mk.injEq .. ▸ ?_
  refine ⟨E00, E01, E02, E10, E11, E12, E20, E21, E22⟩

end Cover

-- ============ The 120 icosian units (600-cell vertices), scaled x2, in Z[phi] ============
namespace Cover
open GR ZPhi

def zhalf (p : Zphi) : Zphi := ⟨p.a/2, p.b/2⟩
def qmulRaw (p q : QZ) : QZ :=
  { w := zsubZ (zsubZ (zsubZ (zmul p.w q.w) (zmul p.x q.x)) (zmul p.y q.y)) (zmul p.z q.z)
  , x := zadd (zadd (zmul p.w q.x) (zmul p.x q.w)) (zsubZ (zmul p.y q.z) (zmul p.z q.y))
  , y := zadd (zsubZ (zmul p.w q.y) (zmul p.x q.z)) (zadd (zmul p.y q.w) (zmul p.z q.x))
  , z := zadd (zsubZ (zadd (zmul p.w q.z) (zmul p.x q.y)) (zmul p.y q.x)) (zmul p.z q.w) }
def qmulS (p q : QZ) : QZ :=
  let r := qmulRaw p q
  ⟨zhalf r.w, zhalf r.x, zhalf r.y, zhalf r.z⟩
def qnegZ (q : QZ) : QZ := ⟨zneg q.w, zneg q.x, zneg q.y, zneg q.z⟩

def icosa : List QZ :=
  [
⟨⟨2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,0⟩, ⟨2,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,1⟩, ⟨-1,1⟩, ⟨1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨1,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
   ⟨⟨0,0⟩, ⟨-2,0⟩, ⟨0,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨1,-1⟩, ⟨-1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨1,-1⟩, ⟨1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,1⟩, ⟨1,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,-1⟩, ⟨1,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨-1,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨-1,0⟩, ⟨0,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨1,-1⟩, ⟨-1,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,-1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
   ⟨⟨0,-1⟩, ⟨-1,0⟩, ⟨0,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,-1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨0,-1⟩, ⟨-1,1⟩, ⟨1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,1⟩, ⟨-1,1⟩, ⟨-1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨1,-1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,0⟩, ⟨0,-1⟩, ⟨-1,1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨1,-1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
   ⟨⟨-1,1⟩, ⟨-1,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨0,-1⟩, ⟨1,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨-1,0⟩, ⟨0,1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,-1⟩, ⟨1,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,0⟩, ⟨-1,0⟩, ⟨0,1⟩⟩,
   ⟨⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨1,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,0⟩, ⟨-1,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,-1⟩, ⟨0,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,1⟩, ⟨1,0⟩, ⟨0,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨-1,1⟩, ⟨1,0⟩, ⟨0,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,1⟩, ⟨0,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨0,1⟩, ⟨1,0⟩, ⟨0,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,1⟩, ⟨0,0⟩, ⟨0,1⟩⟩,
   ⟨⟨0,1⟩, ⟨1,-1⟩, ⟨-1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,1⟩, ⟨-1,0⟩, ⟨0,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨1,-1⟩, ⟨0,-1⟩, ⟨-1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨1,-1⟩, ⟨0,1⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,1⟩, ⟨1,-1⟩, ⟨1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,1⟩, ⟨-1,0⟩, ⟨0,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨-1,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,-1⟩, ⟨-1,1⟩, ⟨0,0⟩⟩,
   ⟨⟨0,0⟩, ⟨1,-1⟩, ⟨0,1⟩, ⟨1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,0⟩, ⟨1,-1⟩, ⟨0,1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨-1,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,1⟩, ⟨0,-1⟩, ⟨1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨1,-1⟩, ⟨0,-1⟩, ⟨1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,1⟩, ⟨0,-1⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,0⟩, ⟨1,-1⟩, ⟨0,-1⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,1⟩, ⟨-1,1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨0,1⟩, ⟨-1,1⟩, ⟨0,0⟩⟩,
   ⟨⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,0⟩, ⟨1,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,0⟩, ⟨1,0⟩, ⟨0,1⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,1⟩, ⟨0,0⟩, ⟨1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨0,1⟩, ⟨1,-1⟩, ⟨0,0⟩⟩,
   ⟨⟨0,1⟩, ⟨0,0⟩, ⟨-1,1⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,0⟩, ⟨-1,0⟩, ⟨0,1⟩⟩,
   ⟨⟨1,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,1⟩, ⟨0,0⟩, ⟨1,-1⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,1⟩, ⟨0,0⟩, ⟨-1,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,0⟩, ⟨1,0⟩, ⟨0,-1⟩⟩,
   ⟨⟨1,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,1⟩, ⟨0,0⟩, ⟨1,-1⟩, ⟨1,0⟩⟩,
   ⟨⟨1,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,1⟩, ⟨0,0⟩, ⟨-1,1⟩, ⟨1,0⟩⟩,
   ⟨⟨1,-1⟩, ⟨0,0⟩, ⟨1,0⟩, ⟨0,1⟩⟩,
   ⟨⟨1,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,-1⟩, ⟨1,0⟩, ⟨0,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,1⟩, ⟨0,1⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨1,0⟩, ⟨1,0⟩, ⟨1,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨-1,1⟩, ⟨-1,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨1,0⟩, ⟨0,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,1⟩, ⟨1,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,0⟩, ⟨1,0⟩, ⟨-1,1⟩, ⟨0,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,1⟩, ⟨1,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,1⟩, ⟨0,1⟩, ⟨-1,0⟩⟩,
   ⟨⟨0,0⟩, ⟨1,0⟩, ⟨-1,1⟩, ⟨0,1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,1⟩, ⟨-1,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨1,0⟩, ⟨1,-1⟩, ⟨0,1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,1⟩, ⟨-1,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,0⟩, ⟨1,0⟩, ⟨1,-1⟩, ⟨0,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,0⟩, ⟨2,0⟩, ⟨0,0⟩⟩,
   ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨1,-1⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨-1,1⟩, ⟨1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨-1,1⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,0⟩, ⟨0,-1⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,-1⟩, ⟨0,0⟩, ⟨1,-1⟩, ⟨-1,0⟩⟩,
   ⟨⟨-1,0⟩, ⟨0,0⟩, ⟨0,1⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨2,0⟩⟩,
   ⟨⟨0,0⟩, ⟨0,0⟩, ⟨0,0⟩, ⟨-2,0⟩⟩,
   ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨1,0⟩, ⟨-1,1⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,0⟩, ⟨-1,1⟩, ⟨0,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,-1⟩, ⟨1,0⟩, ⟨1,-1⟩⟩,
   ⟨⟨0,0⟩, ⟨-1,0⟩, ⟨-1,1⟩, ⟨0,1⟩⟩,
   ⟨⟨0,0⟩, ⟨0,0⟩, ⟨-2,0⟩, ⟨0,0⟩⟩
  ]

def gi : QZ := ⟨⟨0,0⟩,⟨2,0⟩,⟨0,0⟩,⟨0,0⟩⟩
def gg : QZ := ⟨⟨0,1⟩,⟨-1,1⟩,⟨1,0⟩,⟨0,0⟩⟩
def gens2 : List QZ := [gi, gg]
def qOne  : QZ := ⟨⟨2,0⟩,⟨0,0⟩,⟨0,0⟩,⟨0,0⟩⟩
def qNeg1 : QZ := ⟨⟨-2,0⟩,⟨0,0⟩,⟨0,0⟩,⟨0,0⟩⟩

theorem icosa_card : icosa.length = 120 := by decide
theorem icosa_gen_closed :
    (icosa.all (fun a => gens2.all (fun g => icosa.contains (qmulS a g)))) = true := by decide

end Cover

-- ════════ Kernel = {±1}, image = icosahedral rotation group (60), cover index 2 ════════
namespace Cover
open GR ZPhi

-- the scaled identity rotation R(+1) (= 4·I₃ on the ×2-scaled +1)
def RIdent : M3 := RmatZ qOne

-- kernel: icosians whose conjugation rotation equals R(+1)
def icosaKernel : List QZ := icosa.filter (fun q => decide (RmatZ q = RIdent))

-- distinct-rotation de-duplication
def nubM3 (l : List M3) : List M3 :=
  l.foldl (fun acc m => if acc.contains m then acc else acc ++ [m]) []
def icosaImage : List M3 := nubM3 (icosa.map RmatZ)

theorem icosa_kernel_is_pm_one :
    icosaKernel = [qOne, qNeg1] ∧ icosaKernel.length = 2 := by
  refine ⟨by decide, by decide⟩

theorem icosa_neg_invariant :
    (icosa.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true := by decide

theorem icosa_image_card_is_sixty :
    icosaImage.length = 60 ∧ icosa.length / icosaImage.length = 2 := by
  refine ⟨by decide, by decide⟩

end Cover

-- ════════════════════════════════════════════════════════════
-- §9  Master certificate — the 2I cover, computed
-- ════════════════════════════════════════════════════════════

namespace Cover
open GR ZPhi

/-- **SPINOR-COVER-600-CELL (master).** The SU(2) → SO(3) double cover realized by the
    EXACT ℤ[φ] conjugation rotation `RmatZ` on the binary icosahedral group 2I (the 120
    icosian units = the 600-cell vertices):

      (a) UNIVERSAL HOMOMORPHISM: `RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q)` for
          EVERY pair of ℤ[φ]-quaternions (`hom_bridge`) — proved as a polynomial identity,
          NOT by enumerating the 14400 pairs of 2I.
      (b) CLOSURE: the explicit 120-element icosian list has length 120 (`icosa_card`) and
          is closed under multiplication by the two generators (`icosa_gen_closed`).
      (c) `RmatZ q = RmatZ (−q)` for every icosian (`icosa_neg_invariant`), so −1 lies in
          the kernel and the cover is (at least) 2:1.
      (d) KERNEL = {±1}: exactly the two central units map to the identity rotation
          (`icosa_kernel_is_pm_one`).
      (e) IMAGE = 60 = |A₅| (the icosahedral rotation group), cover index 120 / 60 = 2
          (`icosa_image_card_is_sixty`).

    This is the COMPUTED conjugation lift of the order-level shadow in
    `OrientationE8Bridge`; it is the finite restriction of the continuous cover, not the
    continuous cover. -/
theorem spinor_cover_600cell_master :
    (∀ p q : QZ, RmatZ (qmulZ p q) = mmulZ (RmatZ p) (RmatZ q))
    ∧ icosa.length = 120
    ∧ (icosa.all (fun a => gens2.all (fun g => icosa.contains (qmulS a g)))) = true
    ∧ (icosa.all (fun q => decide (RmatZ q = RmatZ (qnegZ q)))) = true
    ∧ (icosaKernel = [qOne, qNeg1] ∧ icosaKernel.length = 2)
    ∧ (icosaImage.length = 60 ∧ icosa.length / icosaImage.length = 2) := by
  refine ⟨hom_bridge, icosa_card, icosa_gen_closed, icosa_neg_invariant,
          icosa_kernel_is_pm_one, icosa_image_card_is_sixty⟩

/-- **The computed 2I cover index equals the order-level shadow.** The index 2 computed
    here from the conjugation rotation (`|2I| / |image| = 120 / 60 = 2`) equals the
    tabulated `Gnosis.OrientationE8Bridge.spinCoverIndex`, and the carrier/image counts match the
    order-arithmetic `subgroupOrder .BinaryIcosa / rotationOrder .Icosa = 120 / 60`. The
    conjugation computation reproduces — and lifts — `binary_is_2to1_spin_cover` and
    `icosa_spin_cover_lands_on_E8` for the icosahedral case. -/
theorem icosa_cover_index_ties_to_shadow :
    icosa.length / icosaImage.length = Gnosis.OrientationE8Bridge.spinCoverIndex
    ∧ icosa.length = ADEMcKayCorrespondence.subgroupOrder .BinaryIcosa 0
    ∧ icosaImage.length = Gnosis.OrientationE8Bridge.rotationOrder .Icosa
    ∧ icosa.length / icosaImage.length
        = ADEMcKayCorrespondence.subgroupOrder .BinaryIcosa 0
            / Gnosis.OrientationE8Bridge.rotationOrder .Icosa := by
  refine ⟨by decide, by decide, by decide, by decide⟩

end Cover

/-! ## Axiom footprint (verified)

`#print axioms` on the headline theorems, verified with the v4.28.0 kernel. The purely
finite, closed-`decide` theorems depend on NO axioms; the universal-homomorphism and master
theorems depend on at most `propext` + `Quot.sound` (the standard Init kernel axioms that
accompany `List`/quotient and structure-equality reasoning) — propext-at-most, NO
`Classical.choice`:

    Cover.spinor_cover_600cell_master       -- [propext, Quot.sound]
    Cover.hom_bridge                        -- [propext, Quot.sound]
    Cover.icosa_card                        -- no axioms
    Cover.icosa_gen_closed                  -- no axioms
    Cover.icosa_kernel_is_pm_one            -- no axioms
    Cover.icosa_neg_invariant               -- no axioms
    Cover.icosa_image_card_is_sixty         -- no axioms
    Cover.icosa_cover_index_ties_to_shadow  -- no axioms
    GR.denote_eq_of_reify_eq                -- [propext, Quot.sound] (reflective bridge)
    ZPhi.zphi_sq                            -- no axioms

No `native_decide`, no `sorry`, no `admit`, no new `axiom`, no `Classical.choice`, no
`omega`.

  -- Next exploration:
  --   * 2O (48) over ℤ[√2] is now mechanical with this engine: instantiate a second
  --     `GR.CRing ℤ[√2]` (the ring axioms discharge via the same Int-reflection helper as
  --     `ZPhi`), reuse the universal `hom_bridge` proof verbatim (the nine entry identities
  --     are the SAME `PExpr`s — only the coefficient ring changes), and orbit-close the 48
  --     octonion units `(±eᵢ±eⱼ)/√2 ∪ 2T` from a 2T generator plus one (e₀+e₁)/√2 unit.
  --     Expected: image = octahedral rotation group O ≅ S₄ (order 24), kernel {±1},
  --     48 / 24 = 2.
  --   * The universal `hom_bridge` here already covers 2O / 2T / Q8 (it is ring-generic):
  --     only the closure list and kernel scan are group-specific.
  --   * The continuum lift (the genuine deferral): with Mathlib, build the Lie cover
  --     SU(2) → SO(3), prove surjective with kernel {±I}, and prove `RmatZ` is its finite
  --     restriction to the ℤ[φ]-points. The hard part is the real-manifold surjectivity.
-/
