import Gnosis.LocalGravityLaw
import Gnosis.ResidualNuclearForce
import Gnosis.MeasuredFlavorClosure
import Gnosis.PerturbativeScatteringClosure
import Gnosis.DarkSectorForceLawClosure
import Gnosis.PrecisionFlavorClosure
import Gnosis.DarkSectorClosure
import Gnosis.RunningCouplingClosure
import Gnosis.ElectroweakScatteringClosure
import Gnosis.ScatteringAmplitudeClosure
import Gnosis.AnomalyCancellationClosure
import Gnosis.ProtonRestMassCandidate

namespace Gnosis

noncomputable section