import Gnosis.DarkSectorClosure
import Gnosis.KinematicScatteringClosure
import Gnosis.PerturbativeBetaClosure
import Gnosis.PrecisionFlavorClosure
import Gnosis.ResidualStrongForceClosure
import Gnosis.GaugeMassShellClosure

namespace Gnosis

noncomputable section