import Gnosis.VibesHotellingVoting
import Gnosis.Bridges.BuleyMeshAttentionBridge
import Gnosis.BuleIsValue
import Gnosis.AmericanFrontier
import Gnosis.NashSkyrmsBuleyGodLadder

/-
  VibesCoaseBargaining.lean
  =========================

  Coase algebra for the vibe/Hotelling layer.

  The Hotelling layer says where emitters stand. The Coase layer says
  when they can bargain over the externalities caused by those
  positions. In this file:

  * a mood position creates a quiet-right externality measured by
    distance from the neutral coordinate `2`;
  * a Coase bargain has transaction cost, bargaining strength, and an
    attention-vote side payment;
  * low transaction cost lets attention votes and bargaining strength
    move an emitter toward the Coase optimum;
  * high transaction cost blocks the move even when the move would
    improve total social vibe value;
  * the same threshold is read as a 3-face Bule ledger
    (`waste = transactionCost`, `opportunity = bargainingStrength`,
    `diversity = attention votes`);
  * the 5-fold Bule lift records the visible ledger plus the hidden
    surplus/loss terms;
  * the American Frontier classifies the transaction-cost threshold as
    pre-frontier failure or at/post-frontier success.

  This sits between Nash and Skyrms: Nash is static best response,
  Coase is negotiated movement under transaction costs, Skyrms is the
  convention that hardens once the negotiated coordinate becomes stable.

  Imports `Gnosis.VibesHotellingVoting`,
  `Gnosis.Bridges.BuleyMeshAttentionBridge`, `Gnosis.BuleIsValue`,
  `Gnosis.AmericanFrontier`, and `Gnosis.NashSkyrmsBuleyGodLadder`.
  Zero `sorry`, zero new `axiom`.
-/


namespace VibesCoaseBargaining

open Gnosis.HotellingModel (natDist leftDemand4)
open VibesHotellingVoting (vibePosition)
open VibesAsWaveInference (VibeValence)
open Gnosis.SpectralNoiseEquilibrium (BuleyFace BuleyUnit buleyUnitScore)
open Gnosis.BuleyMeshAttentionBridge
  (MeshTally reachesQuorum)
open Gnosis
  (BuleFiveFold BuleThreeFaceOptimalMove
   buleFiveFoldValue visibleBuleProjection darkInterferenceLoad
   frontierBule frontierStreamCount frontierRegime frontierNoise)

/-! ## Terms of a Coase bargain -/

/-- Transaction-cost bargaining terms. `sidePayment` is measured in
    attention votes: a mesh-side payment to the moved emitter's
    `BuleyFace`. -/
structure BargainingTerms where
  transactionCost : Nat
  bargainingStrength : Nat
  sidePayment : Nat
  deriving DecidableEq, Repr

/-- Total power available to clear transaction costs: internal
    bargaining strength plus attention-vote side payments. -/
def effectiveBargainingPower (t : BargainingTerms) : Nat :=
  t.bargainingStrength + t.sidePayment

/-- The Coase threshold: transaction costs are low enough for the
    parties to bargain. -/
def CoaseClearsTransactionCost (t : BargainingTerms) : Prop :=
  t.transactionCost ≤ effectiveBargainingPower t

/-- Mesh side payment as a tally on the selected Bule face. -/
def sidePaymentTally (face : BuleyFace) (t : BargainingTerms) : MeshTally :=
  VibesHotellingVoting.popularityVotes face t.sidePayment

theorem side_payment_score_eq_votes (face : BuleyFace) (t : BargainingTerms) :
    buleyUnitScore (sidePaymentTally face t) = t.sidePayment := by
  unfold sidePaymentTally
  exact VibesHotellingVoting.popularity_score_eq_count face t.sidePayment

theorem side_payment_reaches_quorum
    (face : BuleyFace) (t : BargainingTerms) (threshold : Nat)
    (h : threshold ≤ t.sidePayment) :
    reachesQuorum (sidePaymentTally face t) threshold := by
  unfold sidePaymentTally
  exact VibesHotellingVoting.popularity_reaches_quorum face t.sidePayment threshold h

/-! ## Externality and social vibe value -/

/-- The right-to-quiet externality of a mood position: distance from
    the neutral coordinate `2`. -/
def quietExternality (position : Nat) : Nat :=
  natDist position (vibePosition VibeValence.neutral)

/-- Individual quiet-aligned value on the 5-point city. Maximal at
    neutral (`2`), lower at extremes. -/
def quietAlignedValue (position : Nat) : Nat :=
  4 - quietExternality position

/-- Total social vibe value for two emitters under the right-to-quiet
    reading. This deliberately ignores private demand capture: it is
    the social externality ledger, not the firm's private payoff. -/
def socialVibeValue (x y : Nat) : Nat :=
  quietAlignedValue x + quietAlignedValue y

/-- Moving from `start` to `target` against a fixed other emitter creates
    social surplus when the total social vibe value rises. -/
def SocialSurplus (start target other : Nat) : Prop :=
  socialVibeValue start other < socialVibeValue target other

/-- Numeric surplus generated by the move. -/
def socialSurplus (start target other : Nat) : Nat :=
  socialVibeValue target other - socialVibeValue start other

/-- Private Hotelling cost to the moved emitter: demand lost by
    changing location against a fixed other emitter. This saturates at
    zero when the move does not reduce private demand. -/
def moverPrivateCost (start target other : Nat) : Nat :=
  leftDemand4 start other - leftDemand4 target other

/-- A Coase bargain is feasible when bargaining power plus side
    payment covers transaction cost plus the mover's private loss. -/
def CoaseBargainFeasible
    (t : BargainingTerms) (start target other : Nat) : Prop :=
  t.transactionCost + moverPrivateCost start target other
    ≤ effectiveBargainingPower t

/-- A Coase move succeeds when it is feasible and raises social vibe
    value. -/
def CoaseMoveSucceeds
    (t : BargainingTerms) (start target other : Nat) : Prop :=
  CoaseBargainFeasible t start target other ∧ SocialSurplus start target other

/-- The Coase optimum for the two-emitter quiet-right game: both
    emitters stand at the neutral coordinate. -/
def IsCoaseOptimum (x y : Nat) : Prop :=
  x = vibePosition VibeValence.neutral ∧ y = vibePosition VibeValence.neutral

theorem neutral_pair_is_coase_optimum :
    IsCoaseOptimum (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.neutral) := by
  unfold IsCoaseOptimum
  exact ⟨rfl, rfl⟩

/-! ## Coase solves the Hotelling collocation caveat when costs clear -/

/-- The honest Hotelling caveat remains true: neutral does not globally
    strictly dominate the unhappy extreme when the opponent is also at
    the unhappy extreme. -/
theorem hotelling_collocation_caveat_still_holds :
    ¬ VibesHotellingVoting.AttentionDominates
        (vibePosition VibeValence.neutral)
        (vibePosition VibeValence.unhappy)
        (vibePosition VibeValence.unhappy) :=
  VibesHotellingVoting.neutral_does_not_strictly_dominate_unhappy_globally

/-- Moving one collocated unhappy emitter to neutral lowers private
    Hotelling demand by one city unit. This is the private loss that a
    Coase side payment has to cover. -/
theorem unhappy_to_neutral_private_cost_eq_one :
    moverPrivateCost
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) = 1 := by
  unfold moverPrivateCost leftDemand4 vibePosition
  native_decide

/-- The same move raises the social vibe value by two units. -/
theorem unhappy_to_neutral_social_surplus_eq_two :
    socialSurplus
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) = 2 := by
  unfold socialSurplus socialVibeValue quietAlignedValue quietExternality
    vibePosition natDist
  native_decide

/-- The same move is a genuine social surplus improvement. -/
theorem unhappy_to_neutral_is_social_surplus :
    SocialSurplus
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) := by
  unfold SocialSurplus socialVibeValue quietAlignedValue quietExternality
    vibePosition natDist
  native_decide

/-- Low transaction cost case: bargaining strength plus two attention
    votes covers cost plus private loss, so the Coase move succeeds. -/
def lowCostTerms : BargainingTerms where
  transactionCost := 2
  bargainingStrength := 1
  sidePayment := 2

/-- High transaction cost case: the same bargaining strength and side
    payment fail to cover cost plus private loss, so the move fails
    even though the social surplus is positive. -/
def highCostTerms : BargainingTerms where
  transactionCost := 4
  bargainingStrength := 1
  sidePayment := 2

theorem low_cost_terms_clear_transaction_cost :
    CoaseClearsTransactionCost lowCostTerms := by
  unfold CoaseClearsTransactionCost effectiveBargainingPower lowCostTerms
  decide

theorem high_cost_terms_do_not_clear_transaction_cost :
    ¬ CoaseClearsTransactionCost highCostTerms := by
  unfold CoaseClearsTransactionCost effectiveBargainingPower highCostTerms
  decide

theorem low_cost_coase_move_succeeds :
    CoaseMoveSucceeds lowCostTerms
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) := by
  unfold CoaseMoveSucceeds CoaseBargainFeasible SocialSurplus
    effectiveBargainingPower moverPrivateCost socialVibeValue
    quietAlignedValue quietExternality lowCostTerms leftDemand4
    vibePosition natDist
  refine ⟨?_, ?_⟩ <;> native_decide

theorem high_cost_coase_move_fails_despite_surplus :
    ¬ CoaseMoveSucceeds highCostTerms
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) ∧
    SocialSurplus
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) := by
  refine ⟨?_, unhappy_to_neutral_is_social_surplus⟩
  unfold CoaseMoveSucceeds CoaseBargainFeasible effectiveBargainingPower
    moverPrivateCost SocialSurplus socialVibeValue quietAlignedValue
    quietExternality highCostTerms leftDemand4 vibePosition natDist
  native_decide

/-! ## Three-face Bule reading: waste, opportunity, diversity -/

/-- The three-face Bule ledger of a bargain:
    `waste = transactionCost`,
    `opportunity = bargainingStrength`,
    `diversity = sidePayment`.

    The diversity face is the mesh-coordination channel: attention
    votes are not just money-like compensation; they are a diversity
    contribution to the bargaining surface. -/
def coaseThreeFaceBule (t : BargainingTerms) : BuleyUnit where
  waste := t.transactionCost
  opportunity := t.bargainingStrength
  diversity := t.sidePayment

theorem coase_three_face_components (t : BargainingTerms) :
    (coaseThreeFaceBule t).waste = t.transactionCost ∧
    (coaseThreeFaceBule t).opportunity = t.bargainingStrength ∧
    (coaseThreeFaceBule t).diversity = t.sidePayment := by
  exact ⟨rfl, rfl, rfl⟩

/-- Coase success at the transaction-cost level is exactly: the waste
    face is covered by opportunity plus diversity. -/
theorem coase_threshold_is_waste_covered_by_opportunity_and_diversity
    (t : BargainingTerms) :
    CoaseClearsTransactionCost t ↔
      (coaseThreeFaceBule t).waste
        ≤ (coaseThreeFaceBule t).opportunity + (coaseThreeFaceBule t).diversity := by
  unfold CoaseClearsTransactionCost effectiveBargainingPower coaseThreeFaceBule
  exact Iff.rfl

/-- Raising only the diversity face by one attention vote can convert
    the high-cost failure into threshold success. -/
def repairedHighCostTerms : BargainingTerms where
  transactionCost := 4
  bargainingStrength := 1
  sidePayment := 3

theorem one_more_attention_vote_repairs_high_cost_terms :
    ¬ CoaseClearsTransactionCost highCostTerms ∧
      CoaseClearsTransactionCost repairedHighCostTerms := by
  unfold CoaseClearsTransactionCost effectiveBargainingPower
    highCostTerms repairedHighCostTerms
  decide

theorem diversity_vote_is_bule_optimal_repair :
    BuleThreeFaceOptimalMove
      (coaseThreeFaceBule highCostTerms)
      { waste := (coaseThreeFaceBule highCostTerms).waste - 1
        opportunity := (coaseThreeFaceBule highCostTerms).opportunity - 1
        diversity := (coaseThreeFaceBule highCostTerms).diversity + 1 } := by
  refine ⟨?_, ?_, ?_⟩ <;>
    (unfold coaseThreeFaceBule highCostTerms; native_decide)

/-! ## Five-fold Bule lift: visible ledger plus hidden surplus/loss -/

/-- The five-fold Coase carrier. The visible three-face projection is
    the transaction ledger; constructive interference is the social
    surplus; destructive interference is the mover's private loss. -/
def coaseFiveFold
    (t : BargainingTerms) (start target other : Nat) : BuleFiveFold where
  visible := coaseThreeFaceBule t
  constructiveInterference := socialSurplus start target other
  destructiveInterference := moverPrivateCost start target other

theorem coase_five_fold_visible_projection
    (t : BargainingTerms) (start target other : Nat) :
    visibleBuleProjection (coaseFiveFold t start target other)
      = coaseThreeFaceBule t := rfl

theorem coase_five_fold_dark_load
    (t : BargainingTerms) (start target other : Nat) :
    darkInterferenceLoad (coaseFiveFold t start target other)
      = socialSurplus start target other + moverPrivateCost start target other := rfl

theorem low_cost_coase_five_fold_value :
    buleFiveFoldValue
      (coaseFiveFold lowCostTerms
        (vibePosition VibeValence.unhappy)
        (vibePosition VibeValence.neutral)
        (vibePosition VibeValence.unhappy)) = 8 := by
  unfold buleFiveFoldValue coaseFiveFold coaseThreeFaceBule
    lowCostTerms socialSurplus socialVibeValue quietAlignedValue
    quietExternality moverPrivateCost leftDemand4 vibePosition natDist
    Gnosis.buleTotalValue Gnosis.darkInterferenceLoad
  native_decide

/-! ## American Frontier bridge -/

/-- Read the transaction threshold as an American Frontier problem:
    path count is transaction cost; streams are effective bargaining
    power. -/
def coaseFrontierBule (t : BargainingTerms) : BuleyUnit :=
  frontierBule t.transactionCost (effectiveBargainingPower t)

theorem coase_frontier_bule_matches_three_face_threshold
    (t : BargainingTerms) :
    (coaseFrontierBule t).waste
      = t.transactionCost - effectiveBargainingPower t ∧
    (coaseFrontierBule t).diversity
      = effectiveBargainingPower t := by
  unfold coaseFrontierBule frontierBule frontierStreamCount
  exact ⟨rfl, rfl⟩

theorem low_cost_terms_at_frontier :
    frontierRegime lowCostTerms.transactionCost
      (effectiveBargainingPower lowCostTerms)
      = Gnosis.FrontierRegime.post := by
  unfold frontierRegime frontierStreamCount effectiveBargainingPower lowCostTerms
  decide

theorem high_cost_terms_pre_frontier :
    frontierRegime highCostTerms.transactionCost
      (effectiveBargainingPower highCostTerms)
      = Gnosis.FrontierRegime.pre := by
  unfold frontierRegime frontierStreamCount effectiveBargainingPower highCostTerms
  decide

theorem high_cost_terms_are_brown_noise :
    frontierNoise
      (frontierRegime highCostTerms.transactionCost
        (effectiveBargainingPower highCostTerms))
      = Gnosis.NoiseLedger.brown_noise := by
  rw [high_cost_terms_pre_frontier]
  rfl

theorem low_cost_terms_are_white_noise :
    frontierNoise
      (frontierRegime lowCostTerms.transactionCost
        (effectiveBargainingPower lowCostTerms))
      = Gnosis.NoiseLedger.white_noise := by
  rw [low_cost_terms_at_frontier]
  rfl

/-! ## Ladder placement: Nash < Coase < Skyrms -/

/-- Coase is placed as the bargaining bridge between Nash's static
    best response and Skyrms's hardened convention. Numerically this
    is the level between 4 and 6. -/
def coaseLevel : Nat := 5

theorem coase_sits_between_nash_and_skyrms :
    Gnosis.NashSkyrmsBuleyGodLadder.nashLevel < coaseLevel ∧
    coaseLevel < Gnosis.NashSkyrmsBuleyGodLadder.skyrmsLevel := by
  unfold Gnosis.NashSkyrmsBuleyGodLadder.nashLevel
    Gnosis.NashSkyrmsBuleyGodLadder.skyrmsLevel coaseLevel
  decide

/-- Full packaged witness: low transaction cost reaches the Coase
    optimum by attention-vote bargaining; high transaction cost fails
    despite social surplus; the threshold is exactly the Bule
    waste/opportunity/diversity coverage condition and the American
    Frontier regime boundary. -/
theorem coase_bargaining_threshold_for_vibes :
    CoaseMoveSucceeds lowCostTerms
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) ∧
    (¬ CoaseMoveSucceeds highCostTerms
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy)) ∧
    SocialSurplus
      (vibePosition VibeValence.unhappy)
      (vibePosition VibeValence.neutral)
      (vibePosition VibeValence.unhappy) ∧
    CoaseClearsTransactionCost lowCostTerms ∧
    ¬ CoaseClearsTransactionCost highCostTerms ∧
    frontierRegime highCostTerms.transactionCost
      (effectiveBargainingPower highCostTerms)
      = Gnosis.FrontierRegime.pre ∧
    frontierRegime lowCostTerms.transactionCost
      (effectiveBargainingPower lowCostTerms)
      = Gnosis.FrontierRegime.post ∧
    Gnosis.NashSkyrmsBuleyGodLadder.nashLevel < coaseLevel ∧
    coaseLevel < Gnosis.NashSkyrmsBuleyGodLadder.skyrmsLevel :=
  ⟨low_cost_coase_move_succeeds,
   high_cost_coase_move_fails_despite_surplus.1,
   high_cost_coase_move_fails_despite_surplus.2,
   low_cost_terms_clear_transaction_cost,
   high_cost_terms_do_not_clear_transaction_cost,
   high_cost_terms_pre_frontier,
   low_cost_terms_at_frontier,
   coase_sits_between_nash_and_skyrms.1,
   coase_sits_between_nash_and_skyrms.2⟩

/-! ## Honesty note

This module proves a threshold result, not a universal welfare
theorem. The chosen social-vibe value is the right-to-quiet ledger:
distance from neutral is treated as a social externality. Under that
ledger, moving an unhappy collocated emitter toward neutral generates
surplus, but the mover loses private Hotelling demand. Coase
bargaining succeeds exactly when bargaining strength plus attention
votes covers transaction cost plus that private loss.

The failure result is the important part: positive social surplus is
not enough. If transaction costs exceed the mesh's effective bargaining
power, the group stays stuck in the inefficient Hotelling caveat even
though everyone can point to the better coordinate. That is precisely
where Nash has not yet become Coase, and Coase has not yet hardened
into Skyrms convention.
-/

end VibesCoaseBargaining
