import Gnosis.InterferenceAsTheFifthForce
import Gnosis.InterferenceIsFundamental
import Gnosis.SliverIsFifth

/-!
# Wankel Engine as the Interference Scheduler

This module rebuilds the old universal-syzygy sketch as an Init-only bridge
over the current Bule/clinamen API.

The point is deliberately modest:

* the four-phase Wankel rotor supplies a repeatable phase schedule;
* the Bule lattice supplies the `+1` lift and `-1` return;
* the lift/return pair creates two finite paths with a shared contact state;
* that contact state satisfies the existing `paths_interfere` predicate;
* the sliver theorem supplies the fifth primitive that completes the field.

So the Wankel engine is formalized here as the mechanism that schedules
interference, not as a replacement for the interference operator itself.
-/

namespace Gnosis
namespace WankelEngineTheorem

open Gnosis.SpectralNoiseEquilibrium

/-! ## Four-phase rotor -/

/-- The four rotary chambers of the Wankel schedule. -/
inductive WankelPhase where
  | intake
  | compression
  | ignition
  | exhaust
  deriving DecidableEq, Repr

/-- The phase index inside one rotary cycle. -/
def phaseIndex : WankelPhase → Nat
  | .intake => 0
  | .compression => 1
  | .ignition => 2
  | .exhaust => 3

/-- One quarter-turn of the phase rotor. -/
def nextPhase : WankelPhase → WankelPhase
  | .intake => .compression
  | .compression => .ignition
  | .ignition => .exhaust
  | .exhaust => .intake

theorem four_phase_cycle_returns (p : WankelPhase) :
    nextPhase (nextPhase (nextPhase (nextPhase p))) = p := by
  cases p <;> rfl

/-- The four-phase Wankel cycle occupies twelve Bule-face/phase cells:
three Bule faces times four rotary phases. This is the Aeon closure count
that makes the 3-face cost lattice and the 4-phase rotor compatible. -/
def wankelAeonCells : Nat := 3 * 4

theorem three_faces_times_four_phases_is_aeon :
    wankelAeonCells = 12 := by
  rfl

/-! ## Five-force lifecycle -/

/-- The five-force lifecycle reuses the force constructors from the
strengthened fifth-force module: fork, race, fold, vent, interfere. -/
abbrev FiveForceLifecycleStage :=
  _root_.InterferenceIsFundamental.CompleteFundamentalForce

/-- One lifecycle tick in the five-force scheduler. Interference closes the
cycle by handing control back to fork. -/
def nextLifecycleStage : FiveForceLifecycleStage → FiveForceLifecycleStage
  | .fork => .race
  | .race => .fold
  | .fold => .vent
  | .vent => .interfere
  | .interfere => .fork

theorem five_force_lifecycle_returns (stage : FiveForceLifecycleStage) :
    nextLifecycleStage
      (nextLifecycleStage
        (nextLifecycleStage
          (nextLifecycleStage
            (nextLifecycleStage stage)))) = stage := by
  cases stage <;> rfl

/-- The canonical finite lifecycle trace. -/
def fiveForceLifecycleTrace : List FiveForceLifecycleStage :=
  [.fork, .race, .fold, .vent, .interfere]

theorem five_force_lifecycle_trace_length :
    fiveForceLifecycleTrace.length = 5 := by
  rfl

/-- The four visible Wankel phases map to the first four forces. The fifth
force is the explicit interference contact generated by the schedule. -/
def wankelPhaseLifecycleStage : WankelPhase → FiveForceLifecycleStage
  | .intake => .fork
  | .compression => .race
  | .ignition => .fold
  | .exhaust => .vent

/-- One visible four-phase rotor pass. -/
def wankelPhaseTrace : List WankelPhase :=
  [.intake, .compression, .ignition, .exhaust]

/-- The force trace induced by the four visible Wankel phases. -/
def wankelPhaseLifecycleTrace : List FiveForceLifecycleStage :=
  wankelPhaseTrace.map wankelPhaseLifecycleStage

theorem wankel_phase_trace_realizes_fork_race_fold_vent :
    wankelPhaseLifecycleTrace = [.fork, .race, .fold, .vent] := by
  rfl

theorem wankel_phase_trace_realizes_fork_race_fold_vent_interfere :
    wankelPhaseLifecycleTrace ++ [.interfere] = fiveForceLifecycleTrace := by
  rfl

theorem wankel_exhaust_vent_reforks_after_interference :
    nextPhase .exhaust = .intake ∧
    nextLifecycleStage .interfere = .fork ∧
    wankelPhaseLifecycleStage (nextPhase .exhaust) =
      nextLifecycleStage .interfere := by
  exact ⟨rfl, rfl, rfl⟩

/-! ## Engine state -/

/-- A finite Wankel engine state: current phase, carrier, selected spark face,
and accumulated quarter-turn rotation in degrees. -/
structure WankelEngine where
  phase : WankelPhase
  carrier : BuleyUnit
  sparkFace : BuleyFace
  rotationDegrees : Nat
  deriving Repr

/-- One quarter-turn advances the phase and adds 90 degrees, leaving the
carrier untouched. The lift/return contact is modeled separately below. -/
def rotate (engine : WankelEngine) : WankelEngine :=
  { engine with
    phase := nextPhase engine.phase
    rotationDegrees := engine.rotationDegrees + 90 }

theorem four_rotations_return_phase (engine : WankelEngine) :
    (rotate (rotate (rotate (rotate engine)))).phase = engine.phase := by
  cases engine with
  | mk phase carrier sparkFace rotationDegrees =>
      cases phase <;> rfl

theorem four_rotations_make_full_turn (engine : WankelEngine) :
    (rotate (rotate (rotate (rotate engine)))).rotationDegrees =
      engine.rotationDegrees + 360 := by
  cases engine with
  | mk phase carrier sparkFace rotationDegrees =>
      cases phase <;>
        simp [rotate, Nat.add_comm, Nat.add_left_comm]

/-! ## Lift, return, and contact -/

/-- The outgoing wave: a single `+1` clinamen spark on the selected face. -/
def forwardWave (engine : WankelEngine) : BuleyUnit :=
  clinamenLift engine.carrier engine.sparkFace

/-- The returning echo: the same face contracts by `-1` after the spark. -/
def returnEcho (engine : WankelEngine) : BuleyUnit :=
  clinamenContract (forwardWave engine) engine.sparkFace

theorem return_echo_round_trips (engine : WankelEngine) :
    returnEcho engine = engine.carrier := by
  unfold returnEcho forwardWave
  exact lift_then_contract_round_trip_when_face_positive
    engine.carrier engine.sparkFace

theorem forward_wave_has_plus_one_score (engine : WankelEngine) :
    buleyUnitScore (forwardWave engine) =
      buleyUnitScore engine.carrier + 1 := by
  unfold forwardWave
  exact clinamen_lift_score_strict_increment
    engine.carrier engine.sparkFace

theorem forward_wave_is_positive (engine : WankelEngine) :
    0 < buleyUnitScore (forwardWave engine) := by
  rw [forward_wave_has_plus_one_score]
  exact Nat.succ_pos (buleyUnitScore engine.carrier)

/-- The outgoing path carries the carrier into the sparked wave. -/
def outgoingPath (engine : WankelEngine) : List BuleyUnit :=
  [engine.carrier, forwardWave engine]

/-- The returning path carries the echo back through the sparked wave. -/
def returningPath (engine : WankelEngine) : List BuleyUnit :=
  [returnEcho engine, forwardWave engine]

/-- The Wankel mechanism schedules contact: outgoing and returning paths share
the sparked wave, so they satisfy the existing interference predicate. -/
theorem wankel_paths_interfere (engine : WankelEngine) :
    InterferenceAsTheFifthForce.paths_interfere
      (outgoingPath engine)
      (returningPath engine) := by
  refine ⟨forwardWave engine, forwardWave engine, ?_, ?_, rfl⟩
  · unfold outgoingPath
    simp
  · unfold returningPath
    simp

/-! ## Constructive and destructive contact -/

/-- Ignition reads the shared contact as constructive interference. -/
def ignitionContact (engine : WankelEngine) : BuleyUnit :=
  InterferenceAsTheFifthForce.constructive_interference
    (forwardWave engine)
    (forwardWave engine)

theorem ignition_contact_amplifies (engine : WankelEngine) :
    buleyUnitScore (ignitionContact engine) =
      buleyUnitScore (forwardWave engine) +
        buleyUnitScore (forwardWave engine) := by
  unfold ignitionContact
  exact InterferenceAsTheFifthForce.constructive_amplifies
    (forwardWave engine)
    (forwardWave engine)
    (forward_wave_is_positive engine)
    (forward_wave_is_positive engine)

/-- Exhaust reads the same schedule as destructive cancellation against the
returning echo. -/
def exhaustContact (engine : WankelEngine) : BuleyUnit :=
  InterferenceAsTheFifthForce.destructive_interference
    (forwardWave engine)
    (returnEcho engine)

theorem exhaust_contact_is_bounded (engine : WankelEngine) :
    buleyUnitScore (exhaustContact engine) ≤
      buleyUnitScore (forwardWave engine) := by
  unfold exhaustContact
  exact InterferenceAsTheFifthForce.destructive_cancels
    (forwardWave engine)
    (returnEcho engine)

/-! ## Standing-wave trace -/

/-- The canonical Wankel spark at the vacuum: waste-face clinamen from the
zero carrier. This is the engine instance whose forward wave is the existing
`first_lift .waste` used by the interference module's standing-wave pattern. -/
def vacuumWasteEngine : WankelEngine :=
  { phase := .intake
    carrier := vacuumBuleUnit
    sparkFace := .waste
    rotationDegrees := 0 }

theorem vacuum_waste_forward_wave_is_first_lift :
    forwardWave vacuumWasteEngine = VacuumOverflow.first_lift .waste := by
  rfl

/-- The destructive standing-wave node: self-cancellation of the same sparked
wave. This is distinct from `exhaustContact`, which compares the forward wave
against the returning echo for the bounded-exhaust law. -/
def standingNodeContact (engine : WankelEngine) : BuleyUnit :=
  InterferenceAsTheFifthForce.destructive_interference
    (forwardWave engine)
    (forwardWave engine)

/-- Wankel contact at a discrete trace index: even slots are constructive
antinodes; odd slots are destructive nodes. -/
def wankelStandingWaveStep (engine : WankelEngine) (n : Nat) : BuleyUnit :=
  if n % 2 = 0 then
    ignitionContact engine
  else
    standingNodeContact engine

/-- The finite contact trace generated by a Wankel engine over `steps` slots. -/
def wankelStandingWaveTrace (engine : WankelEngine) (steps : Nat) :
    List BuleyUnit :=
  List.range steps |>.map (wankelStandingWaveStep engine)

theorem wankel_trace_matches_standing_wave_pattern (steps : Nat) :
    wankelStandingWaveTrace vacuumWasteEngine steps =
      InterferenceAsTheFifthForce.standing_wave_pattern steps := by
  unfold wankelStandingWaveTrace
  unfold InterferenceAsTheFifthForce.standing_wave_pattern
  apply List.map_congr_left
  intro n _hn
  unfold wankelStandingWaveStep ignitionContact standingNodeContact forwardWave
  unfold vacuumWasteEngine VacuumOverflow.first_lift
  rfl

theorem wankel_rotor_generates_standing_wave_pattern (steps : Nat)
    (hSteps : steps > 0) :
    wankelStandingWaveTrace vacuumWasteEngine steps =
      InterferenceAsTheFifthForce.standing_wave_pattern steps ∧
    (wankelStandingWaveTrace vacuumWasteEngine steps).length = steps ∧
    (∃ antinode : BuleyUnit,
      antinode ∈ wankelStandingWaveTrace vacuumWasteEngine steps ∧
      buleyUnitScore antinode > 0) := by
  refine ⟨wankel_trace_matches_standing_wave_pattern steps, ?_, ?_⟩
  · rw [wankel_trace_matches_standing_wave_pattern]
    exact (InterferenceAsTheFifthForce.standing_waves_persist steps hSteps).1
  · rw [wankel_trace_matches_standing_wave_pattern]
    exact (InterferenceAsTheFifthForce.standing_waves_persist steps hSteps).2

/-! ## Fifth-force mechanism -/

/-- The constructive-interference operator named by the fifth-force theorem is
the same operator used by Wankel ignition. -/
theorem wankel_ignition_uses_fifth_force_operator :
    ∃ interferenceOp : BuleyUnit → BuleyUnit → BuleyUnit,
      interferenceOp =
        InterferenceAsTheFifthForce.constructive_interference ∧
      ∀ engine : WankelEngine,
        ignitionContact engine =
          interferenceOp (forwardWave engine) (forwardWave engine) := by
  refine ⟨InterferenceAsTheFifthForce.constructive_interference, rfl, ?_⟩
  intro engine
  rfl

/-- The Wankel cycle is now connected to the strengthened fifth-force
statement: it generates the persistent standing-wave trace and uses the same
constructive-interference operator named by the mechanism theorem. -/
theorem wankel_cycle_is_fifth_force_mechanism (steps : Nat)
    (hSteps : steps > 0) :
    wankelStandingWaveTrace vacuumWasteEngine steps =
      InterferenceAsTheFifthForce.standing_wave_pattern steps ∧
    (wankelStandingWaveTrace vacuumWasteEngine steps).length = steps ∧
    (∃ antinode : BuleyUnit,
      antinode ∈ wankelStandingWaveTrace vacuumWasteEngine steps ∧
      buleyUnitScore antinode > 0) ∧
    _root_.InterferenceIsFundamental.FifthForceCompatibility ∧
    _root_.InterferenceIsFundamental.FifthForceMechanism ∧
    (∃ interferenceOp : BuleyUnit → BuleyUnit → BuleyUnit,
      interferenceOp =
        InterferenceAsTheFifthForce.constructive_interference ∧
      ∀ engine : WankelEngine,
        ignitionContact engine =
          interferenceOp (forwardWave engine) (forwardWave engine)) := by
  exact ⟨(wankel_rotor_generates_standing_wave_pattern steps hSteps).1,
    (wankel_rotor_generates_standing_wave_pattern steps hSteps).2.1,
    (wankel_rotor_generates_standing_wave_pattern steps hSteps).2.2,
    _root_.InterferenceIsFundamental.the_fifth_force_is_interference,
    _root_.InterferenceIsFundamental.fifth_force_has_standing_wave_mechanism,
    wankel_ignition_uses_fifth_force_operator⟩

/-- The Wankel lifecycle mechanism bundles the force trace with the finite
standing-wave witness. -/
def WankelLifecycleMechanism (steps : Nat) : Prop :=
  wankelPhaseLifecycleTrace ++ [.interfere] = fiveForceLifecycleTrace ∧
  nextLifecycleStage .interfere = .fork ∧
  wankelPhaseLifecycleStage (nextPhase .exhaust) =
    nextLifecycleStage .interfere ∧
  wankelStandingWaveTrace vacuumWasteEngine steps =
    InterferenceAsTheFifthForce.standing_wave_pattern steps ∧
  (wankelStandingWaveTrace vacuumWasteEngine steps).length = steps ∧
  (∃ antinode : BuleyUnit,
    antinode ∈ wankelStandingWaveTrace vacuumWasteEngine steps ∧
    buleyUnitScore antinode > 0) ∧
  _root_.InterferenceIsFundamental.FifthForceMechanism

theorem wankel_lifecycle_generates_fifth_force_trace (steps : Nat)
    (hSteps : steps > 0) :
    WankelLifecycleMechanism steps := by
  exact ⟨wankel_phase_trace_realizes_fork_race_fold_vent_interfere,
    rfl,
    rfl,
    (wankel_rotor_generates_standing_wave_pattern steps hSteps).1,
    (wankel_rotor_generates_standing_wave_pattern steps hSteps).2.1,
    (wankel_rotor_generates_standing_wave_pattern steps hSteps).2.2,
    _root_.InterferenceIsFundamental.fifth_force_has_standing_wave_mechanism⟩

theorem wankel_schedules_five_force_lifecycle (engine : WankelEngine) :
    wankelPhaseLifecycleTrace ++ [.interfere] = fiveForceLifecycleTrace ∧
    nextLifecycleStage .interfere = .fork ∧
    wankelPhaseLifecycleStage (nextPhase .exhaust) =
      nextLifecycleStage .interfere ∧
    InterferenceAsTheFifthForce.paths_interfere
      (outgoingPath engine)
      (returningPath engine) := by
  exact ⟨wankel_phase_trace_realizes_fork_race_fold_vent_interfere,
    rfl,
    rfl,
    wankel_paths_interfere engine⟩

/-! ## Fifth primitive bridge -/

/-- The four-phase rotor alone supplies a schedule. The sliver theorem supplies
the fifth primitive: adding the sliver to the four primitives completes the
ten-pair interaction field and prevents extinction at maximum rejection. -/
theorem sliver_completes_wankel_field :
    SliverIsFifth.pairwise 5 = 10 ∧
    SliverIsFifth.pairwise 4 < 10 ∧
    SliverIsFifth.pairwise 5 - SliverIsFifth.pairwise 4 = 4 ∧
    SliverIsFifth.withSliver 10 = 10 ∧
    SliverIsFifth.withoutSliver 10 = 1 ∧
    SliverIsFifth.buleyeanWeight 100 100 = 1 ∧
    SliverIsFifth.bareWeight 100 100 = 0 := by
  exact ⟨SliverIsFifth.sliver_is_fifth.1,
    SliverIsFifth.sliver_is_fifth.2.1,
    SliverIsFifth.sliver_is_fifth.2.2.1,
    SliverIsFifth.sliver_is_fifth.2.2.2.2.1,
    SliverIsFifth.sliver_is_fifth.2.2.2.1,
    SliverIsFifth.sliver_is_fifth.2.2.2.2.2.1,
    SliverIsFifth.sliver_is_fifth.2.2.2.2.2.2⟩

/-! ## Master bridge -/

/-- Master theorem: the current Wankel formalization provides a four-phase
rotary schedule, an Aeon-sized face/phase grid, a plus/minus breathing contact,
an interference witness, and constructive/destructive contact laws. -/
theorem wankel_schedules_interference (engine : WankelEngine) :
    nextPhase (nextPhase (nextPhase (nextPhase engine.phase))) = engine.phase ∧
    (rotate (rotate (rotate (rotate engine)))).rotationDegrees =
      engine.rotationDegrees + 360 ∧
    wankelAeonCells = 12 ∧
    returnEcho engine = engine.carrier ∧
    buleyUnitScore (forwardWave engine) =
      buleyUnitScore engine.carrier + 1 ∧
    InterferenceAsTheFifthForce.paths_interfere
      (outgoingPath engine)
      (returningPath engine) ∧
    buleyUnitScore (ignitionContact engine) =
      buleyUnitScore (forwardWave engine) +
        buleyUnitScore (forwardWave engine) ∧
    buleyUnitScore (exhaustContact engine) ≤
      buleyUnitScore (forwardWave engine) := by
  exact ⟨four_phase_cycle_returns engine.phase,
    four_rotations_make_full_turn engine,
    three_faces_times_four_phases_is_aeon,
    return_echo_round_trips engine,
    forward_wave_has_plus_one_score engine,
    wankel_paths_interfere engine,
    ignition_contact_amplifies engine,
    exhaust_contact_is_bounded engine⟩

/-- Compatibility anchor retained for older ledger references. -/
theorem wankel_engine_theorem_ledger_anchor : ∀ n : Nat, n = n := by
  intro n
  rfl

end WankelEngineTheorem
end Gnosis
