import Init
-- LLMOutputSanitizationRisk.lean
-- Anti-thesis: LLM outputs are natural language text generated by a statistical
-- model; because no human authored the response, it contains no intentional
-- malicious content, and standard natural language processing pipelines
-- correctly treat it as safe display text requiring no special sanitization.
-- Refutation: LLM outputs are attacker-influenced when prompts contain
-- adversarial instructions. XSS payloads embedded in LLM responses render as
-- scripts when output is injected into HTML without escaping. Applications that
-- pass LLM output to eval() or exec() execute attacker-controlled code.
-- LLM-generated SQL interpolated without parameterization enables SQL injection
-- through the model as a proxy. Code-execution sandboxes are often misconfigured
-- for LLM workloads. Treating model output as a trusted authority violates the
-- trust boundary — the model is a probabilistic text predictor whose output
-- must be validated before being used in security-sensitive operations.

namespace Gnosis.Security.LLMOutputSanitizationRisk

-- XSS via LLM output: model response injected into HTML without escaping
def xssInLLMOutputRisk (llmOutputRenderedAsHTML : Bool)
    (outputHTMLEscaped : Bool) : Bool :=
  llmOutputRenderedAsHTML && !outputHTMLEscaped

theorem html_escaped_output_prevents_xss (rendered : Bool) :
    xssInLLMOutputRisk rendered true = false := by { simp [xssInLLMOutputRisk]

theorem llm_output_not_rendered_as_html_safe (escaped : Bool) :
    xssInLLMOutputRisk false escaped = false := by
  simp [xssInLLMOutputRisk]

theorem unescaped_html_rendered_llm_output_risky :
    xssInLLMOutputRisk true false = true := by
  simp [xssInLLMOutputRisk]

-- Eval of LLM output: model output executed as code without sandboxing
def evalOfLLMOutputRisk (llmOutputPassedToEval : Bool)
    (sandboxed : Bool)
    (outputValidatedAsCode : Bool) : Bool :=
  llmOutputPassedToEval && !sandboxed && !outputValidatedAsCode

theorem sandboxed_eval_prevents_rce (passed validated : Bool) :
    evalOfLLMOutputRisk passed true validated = false := by
  simp [evalOfLLMOutputRisk]

theorem validated_code_prevents_malicious_eval (passed sandboxed : Bool) :
    evalOfLLMOutputRisk passed sandboxed true = false := by
  simp [evalOfLLMOutputRisk]

theorem output_not_eval_safe (sandboxed validated : Bool) :
    evalOfLLMOutputRisk false sandboxed validated = false := by
  simp [evalOfLLMOutputRisk]

theorem unsandboxed_unvalidated_eval_risky :
    evalOfLLMOutputRisk true false false = true := by
  simp [evalOfLLMOutputRisk]

-- SQL from LLM output: model-generated queries used without parameterization
def sqlFromLLMOutputRisk (llmOutputUsedInSQLQuery : Bool)
    (queryParameterized : Bool) : Bool :=
  llmOutputUsedInSQLQuery && !queryParameterized

theorem parameterized_query_prevents_sql_injection (usedInSQL : Bool) :
    sqlFromLLMOutputRisk usedInSQL true = false := by
  simp [sqlFromLLMOutputRisk]

theorem llm_output_not_used_in_sql_safe (parameterized : Bool) :
    sqlFromLLMOutputRisk false parameterized = false := by
  simp [sqlFromLLMOutputRisk]

theorem llm_sql_not_parameterized_risky :
    sqlFromLLMOutputRisk true false = true := by
  simp [sqlFromLLMOutputRisk]

-- Code execution: LLM-generated code executed outside a secure sandbox
def codeExecFromLLMOutputRisk (llmGeneratesExecutableCode : Bool)
    (executionSandboxed : Bool)
    (resourceLimitEnforced : Bool) : Bool :=
  llmGeneratesExecutableCode && !executionSandboxed && !resourceLimitEnforced

theorem sandboxed_code_exec_safe (generates limits : Bool) :
    codeExecFromLLMOutputRisk generates true limits = false := by
  simp [codeExecFromLLMOutputRisk]

theorem resource_limits_prevent_abuse (generates sandboxed : Bool) :
    codeExecFromLLMOutputRisk generates sandboxed true = false := by
  simp [codeExecFromLLMOutputRisk]

theorem no_code_generation_safe (sandboxed limits : Bool) :
    codeExecFromLLMOutputRisk false sandboxed limits = false := by
  simp [codeExecFromLLMOutputRisk]

theorem unsandboxed_unlimited_code_exec_risky :
    codeExecFromLLMOutputRisk true false false = true := by
  simp [codeExecFromLLMOutputRisk]

-- Trust boundary violation: LLM output treated as authorized/trusted input downstream
def trustBoundaryViolationRisk (llmOutputUsedAsAuthorizedInput : Bool)
    (outputExplicitlyValidated : Bool) : Bool :=
  llmOutputUsedAsAuthorizedInput && !outputExplicitlyValidated

theorem explicit_validation_enforces_trust_boundary (usedAsAuth : Bool) :
    trustBoundaryViolationRisk usedAsAuth true = false := by
  simp [trustBoundaryViolationRisk]

theorem llm_output_not_used_as_auth_safe (validated : Bool) :
    trustBoundaryViolationRisk false validated = false := by
  simp [trustBoundaryViolationRisk]

theorem llm_output_authorized_without_validation_risky :
    trustBoundaryViolationRisk true false = true := by
  simp [trustBoundaryViolationRisk]

-- Aggregate LLM output sanitization risk count
def aggregateLLMOutputSanitizationRisk
    (renderedHTML htmlEscaped : Bool)
    (passedToEval evalSandboxed evalValidated : Bool)
    (usedInSQL parameterized : Bool)
    (generatesCode codeSandboxed resourceLimited : Bool)
    (usedAsAuth explicitlyValidated : Bool) : Nat :=
  (if xssInLLMOutputRisk renderedHTML htmlEscaped then 1 else 0) +
  (if evalOfLLMOutputRisk passedToEval evalSandboxed evalValidated then 1 else 0) +
  (if sqlFromLLMOutputRisk usedInSQL parameterized then 1 else 0) +
  (if codeExecFromLLMOutputRisk generatesCode codeSandboxed resourceLimited then 1 else 0) +
  (if trustBoundaryViolationRisk usedAsAuth explicitlyValidated then 1 else 0)

theorem fully_hardened_zero_llm_output_sanitization_risk :
    aggregateLLMOutputSanitizationRisk
      true true
      true true true
      true true
      true true true
      true true = 0 := by
  simp [aggregateLLMOutputSanitizationRisk, xssInLLMOutputRisk, evalOfLLMOutputRisk,
        sqlFromLLMOutputRisk, codeExecFromLLMOutputRisk, trustBoundaryViolationRisk]

theorem all_llm_output_sanitization_vectors_max_risk :
    aggregateLLMOutputSanitizationRisk
      true false
      true false false
      true false
      true false false
      true false = 5 := by
  simp [aggregateLLMOutputSanitizationRisk, xssInLLMOutputRisk, evalOfLLMOutputRisk,
        sqlFromLLMOutputRisk, codeExecFromLLMOutputRisk, trustBoundaryViolationRisk]

theorem llm_output_sanitization_risk_bounded
    (renderedHTML htmlEscaped : Bool)
    (passedToEval evalSandboxed evalValidated : Bool)
    (usedInSQL parameterized : Bool)
    (generatesCode codeSandboxed resourceLimited : Bool)
    (usedAsAuth explicitlyValidated : Bool) :
    aggregateLLMOutputSanitizationRisk
      renderedHTML htmlEscaped passedToEval evalSandboxed evalValidated
      usedInSQL parameterized generatesCode codeSandboxed resourceLimited
      usedAsAuth explicitlyValidated ≤ 5 := by
  simp [aggregateLLMOutputSanitizationRisk]
  split <;> split <;> split <;> split <;> split <;> decide

-- Scanner ROI: LLM output sanitization detection prevents XSS and RCE
def llmOutputSanitizationDetectionValueCents (rceBreachCostCents : Nat)
    (scannerCostCents : Nat) : Int :=
  (rceBreachCostCents : Int) - (scannerCostCents : Int)

theorem llm_output_sanitization_scanner_profitable (breach scan : Nat) (h : scan < breach) :
    0 < llmOutputSanitizationDetectionValueCents breach scan := by
  simp [llmOutputSanitizationDetectionValueCents]; repeat (first | assumption | constructor | rfl | split | intro | apply Nat.le_refl | apply Nat.zero_le | apply Nat.succ_pos | apply Nat.zero_lt_succ | apply Nat.le_add_right | apply Nat.le_add_left | apply Nat.mul_le_mul_left | apply Nat.mul_le_mul_right | apply Nat.mul_pos | apply Nat.div_le_div_right | apply Nat.min_le_min | apply Nat.le_trans | apply Nat.le_of_lt | decide) }

theorem llm_output_sanitization_scanner_break_even (cost : Nat) :
    0 ≤ llmOutputSanitizationDetectionValueCents cost cost := by
  simp [llmOutputSanitizationDetectionValueCents]

-- Fleet ROI: LLM output sanitization scan scales across all AI-integrated services
def llmOutputSanitizationFleetROI (detectionValueCents : Nat) (aiServices : Nat) : Nat :=
  detectionValueCents * aiServices

theorem llm_output_sanitization_fleet_roi_monotone (v s1 s2 : Nat) (h : s1 ≤ s2) :
    llmOutputSanitizationFleetROI v s1 ≤ llmOutputSanitizationFleetROI v s2 := by
  simp [llmOutputSanitizationFleetROI]
  exact Nat.mul_le_mul_left v h

theorem positive_llm_output_sanitization_fleet_roi (v s : Nat) (hv : 0 < v) (hs : 0 < s) :
    0 < llmOutputSanitizationFleetROI v s := by
  simp [llmOutputSanitizationFleetROI]
  exact Nat.mul_pos hv hs

end LLMOutputSanitizationRisk
