import Gnosis.GnosisTriptychBraid

namespace Gnosis.Witnesses.Gnostic
namespace TripartiteSaviorOrderingWitness

/-!
# Tripartite Tractate -- Savior Light and Ordered Use

Source text: `docs/ebooks/source-texts/tripartite-tractate.txt`;
text anchor `docs/ebooks/source-texts/tripartite-tractate.txt:520-835`.

Sat/unseen reading:

The Savior is generated by harmonious consent as aid for the defective one. His
light heals the Logos gradually from within, but strikes hostile orders suddenly
as lightning. The organization that follows does not romanticize hierarchy:
archons, ranks, laws, threats, rests, and punishments become ordered uses inside
a larger correction protocol.

Gap / counterproof:

The Demiurge mistakes borrowed motion and titles for essence. He is a hand and
mouth used by the Logos, not the source of the motion inside him.

No `sorry`, no new `axiom`.
-/

structure SaviorAgreement where
  pleromaConsentsJoyfully : Bool
  aidForDefectiveOne : Bool
  fruitOfHarmony : Bool
  sonAsGarment : Bool
  givesPerfectionToDefective : Bool
  knowledgeOfFather : Bool
deriving DecidableEq, Repr

def tripartiteSaviorAgreement : SaviorAgreement where
  pleromaConsentsJoyfully := true
  aidForDefectiveOne := true
  fruitOfHarmony := true
  sonAsGarment := true
  givesPerfectionToDefective := true
  knowledgeOfFather := true

def saviorFromHarmoniousConsent (s : SaviorAgreement) : Prop :=
  s.pleromaConsentsJoyfully = true ∧
  s.aidForDefectiveOne = true ∧
  s.fruitOfHarmony = true ∧
  s.sonAsGarment = true ∧
  s.givesPerfectionToDefective = true ∧
  s.knowledgeOfFather = true

structure LightDifferentiation where
  inwardFellowSufferer : Bool
  gradualRestGrowthLift : Bool
  lightningToHostileOrders : Bool
  thoughtWitnessesLight : Bool
  likenessFallsToChaos : Bool
  logosReceivesRest : Bool
deriving DecidableEq, Repr

def tripartiteLightDifferentiation : LightDifferentiation where
  inwardFellowSufferer := true
  gradualRestGrowthLift := true
  lightningToHostileOrders := true
  thoughtWitnessesLight := true
  likenessFallsToChaos := true
  logosReceivesRest := true

def lightHealsAndSeparates (l : LightDifferentiation) : Prop :=
  l.inwardFellowSufferer = true ∧
  l.gradualRestGrowthLift = true ∧
  l.lightningToHostileOrders = true ∧
  l.thoughtWitnessesLight = true ∧
  l.likenessFallsToChaos = true ∧
  l.logosReceivesRest = true

structure DemiurgeBorrowedMotion where
  archonReceivesTitles : Bool
  usedAsHandAndMouth : Bool
  thinksMotionHisOwn : Bool
  spiritMovesInvisibly : Bool
  ranksOrderedForUse : Bool
  noCommandLacking : Bool
deriving DecidableEq, Repr

def tripartiteDemiurgeBorrowedMotion : DemiurgeBorrowedMotion where
  archonReceivesTitles := true
  usedAsHandAndMouth := true
  thinksMotionHisOwn := true
  spiritMovesInvisibly := true
  ranksOrderedForUse := true
  noCommandLacking := true

def demiurgeIsInstrumentNotSource (d : DemiurgeBorrowedMotion) : Prop :=
  d.archonReceivesTitles = true ∧
  d.usedAsHandAndMouth = true ∧
  d.thinksMotionHisOwn = true ∧
  d.spiritMovesInvisibly = true ∧
  d.ranksOrderedForUse = true ∧
  d.noCommandLacking = true

theorem tripartite_savior_agreement :
    saviorFromHarmoniousConsent tripartiteSaviorAgreement := by
  unfold saviorFromHarmoniousConsent tripartiteSaviorAgreement
  exact ⟨rfl, rfl, rfl, rfl, rfl, rfl⟩

theorem tripartite_light_differentiates :
    lightHealsAndSeparates tripartiteLightDifferentiation := by
  unfold lightHealsAndSeparates tripartiteLightDifferentiation
  exact ⟨rfl, rfl, rfl, rfl, rfl, rfl⟩

theorem tripartite_demiurge_instrument :
    demiurgeIsInstrumentNotSource tripartiteDemiurgeBorrowedMotion := by
  unfold demiurgeIsInstrumentNotSource tripartiteDemiurgeBorrowedMotion
  exact ⟨rfl, rfl, rfl, rfl, rfl, rfl⟩

theorem tripartite_order_centroid :
    Gnosis.GnosisTriptychBraid.cycleSum = Gnosis.GnosisTriptychBraid.truth :=
  Gnosis.GnosisTriptychBraid.cycle_sum_zero

theorem tripartite_savior_ordering_witness :
    saviorFromHarmoniousConsent tripartiteSaviorAgreement ∧
    lightHealsAndSeparates tripartiteLightDifferentiation ∧
    demiurgeIsInstrumentNotSource tripartiteDemiurgeBorrowedMotion ∧
    Gnosis.GnosisTriptychBraid.cycleSum = Gnosis.GnosisTriptychBraid.truth := by
  exact ⟨tripartite_savior_agreement,
    tripartite_light_differentiates,
    tripartite_demiurge_instrument,
    tripartite_order_centroid⟩

end TripartiteSaviorOrderingWitness
end Gnosis.Witnesses.Gnostic
